/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MobileAppBanner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MobileAppBanner{}

// MobileAppBanner A banner shown in the mobile app.
type MobileAppBanner struct {
	Title string `json:"title"`
	Uuid string `json:"uuid"`
	Subtitle string `json:"subtitle"`
	// Full public URL of the banner image.
	Image string `json:"image"`
	// Destination URL opened when the banner is tapped.
	Url string `json:"url"`
}

type _MobileAppBanner MobileAppBanner

// NewMobileAppBanner instantiates a new MobileAppBanner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMobileAppBanner(title string, uuid string, subtitle string, image string, url string) *MobileAppBanner {
	this := MobileAppBanner{}
	this.Title = title
	this.Uuid = uuid
	this.Subtitle = subtitle
	this.Image = image
	this.Url = url
	return &this
}

// NewMobileAppBannerWithDefaults instantiates a new MobileAppBanner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMobileAppBannerWithDefaults() *MobileAppBanner {
	this := MobileAppBanner{}
	return &this
}

// GetTitle returns the Title field value
func (o *MobileAppBanner) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *MobileAppBanner) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *MobileAppBanner) SetTitle(v string) {
	o.Title = v
}

// GetUuid returns the Uuid field value
func (o *MobileAppBanner) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *MobileAppBanner) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *MobileAppBanner) SetUuid(v string) {
	o.Uuid = v
}

// GetSubtitle returns the Subtitle field value
func (o *MobileAppBanner) GetSubtitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subtitle
}

// GetSubtitleOk returns a tuple with the Subtitle field value
// and a boolean to check if the value has been set.
func (o *MobileAppBanner) GetSubtitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subtitle, true
}

// SetSubtitle sets field value
func (o *MobileAppBanner) SetSubtitle(v string) {
	o.Subtitle = v
}

// GetImage returns the Image field value
func (o *MobileAppBanner) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *MobileAppBanner) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *MobileAppBanner) SetImage(v string) {
	o.Image = v
}

// GetUrl returns the Url field value
func (o *MobileAppBanner) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *MobileAppBanner) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *MobileAppBanner) SetUrl(v string) {
	o.Url = v
}

func (o MobileAppBanner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MobileAppBanner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	toSerialize["uuid"] = o.Uuid
	toSerialize["subtitle"] = o.Subtitle
	toSerialize["image"] = o.Image
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *MobileAppBanner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"uuid",
		"subtitle",
		"image",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMobileAppBanner := _MobileAppBanner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMobileAppBanner)

	if err != nil {
		return err
	}

	*o = MobileAppBanner(varMobileAppBanner)

	return err
}

type NullableMobileAppBanner struct {
	value *MobileAppBanner
	isSet bool
}

func (v NullableMobileAppBanner) Get() *MobileAppBanner {
	return v.value
}

func (v *NullableMobileAppBanner) Set(val *MobileAppBanner) {
	v.value = val
	v.isSet = true
}

func (v NullableMobileAppBanner) IsSet() bool {
	return v.isSet
}

func (v *NullableMobileAppBanner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMobileAppBanner(val *MobileAppBanner) *NullableMobileAppBanner {
	return &NullableMobileAppBanner{value: val, isSet: true}
}

func (v NullableMobileAppBanner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMobileAppBanner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


