/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Overview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Overview{}

// Overview Provides a snapshot of the resort's current operational state including  today's scheduled hours (calculated from operating hour rules), run/lift  overview counts, the current season, and written news.
type Overview struct {
	// Current operational status of the resort (open or closed).  This is calculated based on the current time relative to today's scheduled hours.
	Status ResortStatus `json:"status"`
	// Today's scheduled opening time in 24-hour format (HH:MM).  `null` if the resort is not scheduled to open today.
	OpensAt NullableString `json:"opens_at,omitempty"`
	// Today's scheduled closing time in 24-hour format (HH:MM).  `null` if the resort is not scheduled to open today.
	ClosesAt NullableString `json:"closes_at,omitempty"`
	// Current operating season (winter, summer, or closed/off-season).
	Season SeasonType `json:"season"`
	// Written news — daily update, announcements, etc.
	News OverviewNews `json:"news"`
	// Run statistics: counts, acres, and last-updated timestamp.
	Runs OverviewRuns `json:"runs"`
	// Lift statistics: counts and last-updated timestamp.
	Lifts OverviewLifts `json:"lifts"`
	// Summer trail statistics: counts and last-updated timestamp.
	SummerTrails OverviewSummerTrails `json:"summer_trails"`
	// Terrain park statistics: counts and last-updated timestamp.
	TerrainParks OverviewTerrainParks `json:"terrain_parks"`
}

type _Overview Overview

// NewOverview instantiates a new Overview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOverview(status ResortStatus, season SeasonType, news OverviewNews, runs OverviewRuns, lifts OverviewLifts, summerTrails OverviewSummerTrails, terrainParks OverviewTerrainParks) *Overview {
	this := Overview{}
	this.Status = status
	this.Season = season
	this.News = news
	this.Runs = runs
	this.Lifts = lifts
	this.SummerTrails = summerTrails
	this.TerrainParks = terrainParks
	return &this
}

// NewOverviewWithDefaults instantiates a new Overview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOverviewWithDefaults() *Overview {
	this := Overview{}
	return &this
}

// GetStatus returns the Status field value
func (o *Overview) GetStatus() ResortStatus {
	if o == nil {
		var ret ResortStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Overview) GetStatusOk() (*ResortStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Overview) SetStatus(v ResortStatus) {
	o.Status = v
}

// GetOpensAt returns the OpensAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Overview) GetOpensAt() string {
	if o == nil || IsNil(o.OpensAt.Get()) {
		var ret string
		return ret
	}
	return *o.OpensAt.Get()
}

// GetOpensAtOk returns a tuple with the OpensAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Overview) GetOpensAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OpensAt.Get(), o.OpensAt.IsSet()
}

// HasOpensAt returns a boolean if a field has been set.
func (o *Overview) HasOpensAt() bool {
	if o != nil && o.OpensAt.IsSet() {
		return true
	}

	return false
}

// SetOpensAt gets a reference to the given NullableString and assigns it to the OpensAt field.
func (o *Overview) SetOpensAt(v string) {
	o.OpensAt.Set(&v)
}
// SetOpensAtNil sets the value for OpensAt to be an explicit nil
func (o *Overview) SetOpensAtNil() {
	o.OpensAt.Set(nil)
}

// UnsetOpensAt ensures that no value is present for OpensAt, not even an explicit nil
func (o *Overview) UnsetOpensAt() {
	o.OpensAt.Unset()
}

// GetClosesAt returns the ClosesAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Overview) GetClosesAt() string {
	if o == nil || IsNil(o.ClosesAt.Get()) {
		var ret string
		return ret
	}
	return *o.ClosesAt.Get()
}

// GetClosesAtOk returns a tuple with the ClosesAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Overview) GetClosesAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClosesAt.Get(), o.ClosesAt.IsSet()
}

// HasClosesAt returns a boolean if a field has been set.
func (o *Overview) HasClosesAt() bool {
	if o != nil && o.ClosesAt.IsSet() {
		return true
	}

	return false
}

// SetClosesAt gets a reference to the given NullableString and assigns it to the ClosesAt field.
func (o *Overview) SetClosesAt(v string) {
	o.ClosesAt.Set(&v)
}
// SetClosesAtNil sets the value for ClosesAt to be an explicit nil
func (o *Overview) SetClosesAtNil() {
	o.ClosesAt.Set(nil)
}

// UnsetClosesAt ensures that no value is present for ClosesAt, not even an explicit nil
func (o *Overview) UnsetClosesAt() {
	o.ClosesAt.Unset()
}

// GetSeason returns the Season field value
func (o *Overview) GetSeason() SeasonType {
	if o == nil {
		var ret SeasonType
		return ret
	}

	return o.Season
}

// GetSeasonOk returns a tuple with the Season field value
// and a boolean to check if the value has been set.
func (o *Overview) GetSeasonOk() (*SeasonType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Season, true
}

// SetSeason sets field value
func (o *Overview) SetSeason(v SeasonType) {
	o.Season = v
}

// GetNews returns the News field value
func (o *Overview) GetNews() OverviewNews {
	if o == nil {
		var ret OverviewNews
		return ret
	}

	return o.News
}

// GetNewsOk returns a tuple with the News field value
// and a boolean to check if the value has been set.
func (o *Overview) GetNewsOk() (*OverviewNews, bool) {
	if o == nil {
		return nil, false
	}
	return &o.News, true
}

// SetNews sets field value
func (o *Overview) SetNews(v OverviewNews) {
	o.News = v
}

// GetRuns returns the Runs field value
func (o *Overview) GetRuns() OverviewRuns {
	if o == nil {
		var ret OverviewRuns
		return ret
	}

	return o.Runs
}

// GetRunsOk returns a tuple with the Runs field value
// and a boolean to check if the value has been set.
func (o *Overview) GetRunsOk() (*OverviewRuns, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Runs, true
}

// SetRuns sets field value
func (o *Overview) SetRuns(v OverviewRuns) {
	o.Runs = v
}

// GetLifts returns the Lifts field value
func (o *Overview) GetLifts() OverviewLifts {
	if o == nil {
		var ret OverviewLifts
		return ret
	}

	return o.Lifts
}

// GetLiftsOk returns a tuple with the Lifts field value
// and a boolean to check if the value has been set.
func (o *Overview) GetLiftsOk() (*OverviewLifts, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lifts, true
}

// SetLifts sets field value
func (o *Overview) SetLifts(v OverviewLifts) {
	o.Lifts = v
}

// GetSummerTrails returns the SummerTrails field value
func (o *Overview) GetSummerTrails() OverviewSummerTrails {
	if o == nil {
		var ret OverviewSummerTrails
		return ret
	}

	return o.SummerTrails
}

// GetSummerTrailsOk returns a tuple with the SummerTrails field value
// and a boolean to check if the value has been set.
func (o *Overview) GetSummerTrailsOk() (*OverviewSummerTrails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SummerTrails, true
}

// SetSummerTrails sets field value
func (o *Overview) SetSummerTrails(v OverviewSummerTrails) {
	o.SummerTrails = v
}

// GetTerrainParks returns the TerrainParks field value
func (o *Overview) GetTerrainParks() OverviewTerrainParks {
	if o == nil {
		var ret OverviewTerrainParks
		return ret
	}

	return o.TerrainParks
}

// GetTerrainParksOk returns a tuple with the TerrainParks field value
// and a boolean to check if the value has been set.
func (o *Overview) GetTerrainParksOk() (*OverviewTerrainParks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TerrainParks, true
}

// SetTerrainParks sets field value
func (o *Overview) SetTerrainParks(v OverviewTerrainParks) {
	o.TerrainParks = v
}

func (o Overview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Overview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	if o.OpensAt.IsSet() {
		toSerialize["opens_at"] = o.OpensAt.Get()
	}
	if o.ClosesAt.IsSet() {
		toSerialize["closes_at"] = o.ClosesAt.Get()
	}
	toSerialize["season"] = o.Season
	toSerialize["news"] = o.News
	toSerialize["runs"] = o.Runs
	toSerialize["lifts"] = o.Lifts
	toSerialize["summer_trails"] = o.SummerTrails
	toSerialize["terrain_parks"] = o.TerrainParks
	return toSerialize, nil
}

func (o *Overview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"season",
		"news",
		"runs",
		"lifts",
		"summer_trails",
		"terrain_parks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOverview := _Overview{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOverview)

	if err != nil {
		return err
	}

	*o = Overview(varOverview)

	return err
}

type NullableOverview struct {
	value *Overview
	isSet bool
}

func (v NullableOverview) Get() *Overview {
	return v.value
}

func (v *NullableOverview) Set(val *Overview) {
	v.value = val
	v.isSet = true
}

func (v NullableOverview) IsSet() bool {
	return v.isSet
}

func (v *NullableOverview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverview(val *Overview) *NullableOverview {
	return &NullableOverview{value: val, isSet: true}
}

func (v NullableOverview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


