/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PointMarker - A point marker on a trail map, enriched with entity data where applicable.
type PointMarker struct {
	PointMarkerOneOf *PointMarkerOneOf
	PointMarkerOneOf1 *PointMarkerOneOf1
	PointMarkerOneOf2 *PointMarkerOneOf2
}

// PointMarkerOneOfAsPointMarker is a convenience function that returns PointMarkerOneOf wrapped in PointMarker
func PointMarkerOneOfAsPointMarker(v *PointMarkerOneOf) PointMarker {
	return PointMarker{
		PointMarkerOneOf: v,
	}
}

// PointMarkerOneOf1AsPointMarker is a convenience function that returns PointMarkerOneOf1 wrapped in PointMarker
func PointMarkerOneOf1AsPointMarker(v *PointMarkerOneOf1) PointMarker {
	return PointMarker{
		PointMarkerOneOf1: v,
	}
}

// PointMarkerOneOf2AsPointMarker is a convenience function that returns PointMarkerOneOf2 wrapped in PointMarker
func PointMarkerOneOf2AsPointMarker(v *PointMarkerOneOf2) PointMarker {
	return PointMarker{
		PointMarkerOneOf2: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PointMarker) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PointMarkerOneOf
	err = newStrictDecoder(data).Decode(&dst.PointMarkerOneOf)
	if err == nil {
		jsonPointMarkerOneOf, _ := json.Marshal(dst.PointMarkerOneOf)
		if string(jsonPointMarkerOneOf) == "{}" { // empty struct
			dst.PointMarkerOneOf = nil
		} else {
			if err = validator.Validate(dst.PointMarkerOneOf); err != nil {
				dst.PointMarkerOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.PointMarkerOneOf = nil
	}

	// try to unmarshal data into PointMarkerOneOf1
	err = newStrictDecoder(data).Decode(&dst.PointMarkerOneOf1)
	if err == nil {
		jsonPointMarkerOneOf1, _ := json.Marshal(dst.PointMarkerOneOf1)
		if string(jsonPointMarkerOneOf1) == "{}" { // empty struct
			dst.PointMarkerOneOf1 = nil
		} else {
			if err = validator.Validate(dst.PointMarkerOneOf1); err != nil {
				dst.PointMarkerOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PointMarkerOneOf1 = nil
	}

	// try to unmarshal data into PointMarkerOneOf2
	err = newStrictDecoder(data).Decode(&dst.PointMarkerOneOf2)
	if err == nil {
		jsonPointMarkerOneOf2, _ := json.Marshal(dst.PointMarkerOneOf2)
		if string(jsonPointMarkerOneOf2) == "{}" { // empty struct
			dst.PointMarkerOneOf2 = nil
		} else {
			if err = validator.Validate(dst.PointMarkerOneOf2); err != nil {
				dst.PointMarkerOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PointMarkerOneOf2 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PointMarkerOneOf = nil
		dst.PointMarkerOneOf1 = nil
		dst.PointMarkerOneOf2 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PointMarker)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PointMarker)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PointMarker) MarshalJSON() ([]byte, error) {
	if src.PointMarkerOneOf != nil {
		return json.Marshal(&src.PointMarkerOneOf)
	}

	if src.PointMarkerOneOf1 != nil {
		return json.Marshal(&src.PointMarkerOneOf1)
	}

	if src.PointMarkerOneOf2 != nil {
		return json.Marshal(&src.PointMarkerOneOf2)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PointMarker) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PointMarkerOneOf != nil {
		return obj.PointMarkerOneOf
	}

	if obj.PointMarkerOneOf1 != nil {
		return obj.PointMarkerOneOf1
	}

	if obj.PointMarkerOneOf2 != nil {
		return obj.PointMarkerOneOf2
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PointMarker) GetActualInstanceValue() (interface{}) {
	if obj.PointMarkerOneOf != nil {
		return *obj.PointMarkerOneOf
	}

	if obj.PointMarkerOneOf1 != nil {
		return *obj.PointMarkerOneOf1
	}

	if obj.PointMarkerOneOf2 != nil {
		return *obj.PointMarkerOneOf2
	}

	// all schemas are nil
	return nil
}

type NullablePointMarker struct {
	value *PointMarker
	isSet bool
}

func (v NullablePointMarker) Get() *PointMarker {
	return v.value
}

func (v *NullablePointMarker) Set(val *PointMarker) {
	v.value = val
	v.isSet = true
}

func (v NullablePointMarker) IsSet() bool {
	return v.isSet
}

func (v *NullablePointMarker) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointMarker(val *PointMarker) *NullablePointMarker {
	return &NullablePointMarker{value: val, isSet: true}
}

func (v NullablePointMarker) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointMarker) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


