/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrailMapElementOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrailMapElementOneOf3{}

// TrailMapElementOneOf3 struct for TrailMapElementOneOf3
type TrailMapElementOneOf3 struct {
	Type string `json:"type"`
	Uuid string `json:"uuid"`
	Points []float64 `json:"points"`
	Tension NullableFloat64 `json:"tension,omitempty"`
	SummerTrail NullableSummerTrail `json:"summer_trail,omitempty"`
}

type _TrailMapElementOneOf3 TrailMapElementOneOf3

// NewTrailMapElementOneOf3 instantiates a new TrailMapElementOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrailMapElementOneOf3(type_ string, uuid string, points []float64) *TrailMapElementOneOf3 {
	this := TrailMapElementOneOf3{}
	this.Type = type_
	this.Uuid = uuid
	this.Points = points
	return &this
}

// NewTrailMapElementOneOf3WithDefaults instantiates a new TrailMapElementOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrailMapElementOneOf3WithDefaults() *TrailMapElementOneOf3 {
	this := TrailMapElementOneOf3{}
	return &this
}

// GetType returns the Type field value
func (o *TrailMapElementOneOf3) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf3) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TrailMapElementOneOf3) SetType(v string) {
	o.Type = v
}

// GetUuid returns the Uuid field value
func (o *TrailMapElementOneOf3) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf3) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *TrailMapElementOneOf3) SetUuid(v string) {
	o.Uuid = v
}

// GetPoints returns the Points field value
func (o *TrailMapElementOneOf3) GetPoints() []float64 {
	if o == nil {
		var ret []float64
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf3) GetPointsOk() ([]float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Points, true
}

// SetPoints sets field value
func (o *TrailMapElementOneOf3) SetPoints(v []float64) {
	o.Points = v
}

// GetTension returns the Tension field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf3) GetTension() float64 {
	if o == nil || IsNil(o.Tension.Get()) {
		var ret float64
		return ret
	}
	return *o.Tension.Get()
}

// GetTensionOk returns a tuple with the Tension field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf3) GetTensionOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tension.Get(), o.Tension.IsSet()
}

// HasTension returns a boolean if a field has been set.
func (o *TrailMapElementOneOf3) HasTension() bool {
	if o != nil && o.Tension.IsSet() {
		return true
	}

	return false
}

// SetTension gets a reference to the given NullableFloat64 and assigns it to the Tension field.
func (o *TrailMapElementOneOf3) SetTension(v float64) {
	o.Tension.Set(&v)
}
// SetTensionNil sets the value for Tension to be an explicit nil
func (o *TrailMapElementOneOf3) SetTensionNil() {
	o.Tension.Set(nil)
}

// UnsetTension ensures that no value is present for Tension, not even an explicit nil
func (o *TrailMapElementOneOf3) UnsetTension() {
	o.Tension.Unset()
}

// GetSummerTrail returns the SummerTrail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf3) GetSummerTrail() SummerTrail {
	if o == nil || IsNil(o.SummerTrail.Get()) {
		var ret SummerTrail
		return ret
	}
	return *o.SummerTrail.Get()
}

// GetSummerTrailOk returns a tuple with the SummerTrail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf3) GetSummerTrailOk() (*SummerTrail, bool) {
	if o == nil {
		return nil, false
	}
	return o.SummerTrail.Get(), o.SummerTrail.IsSet()
}

// HasSummerTrail returns a boolean if a field has been set.
func (o *TrailMapElementOneOf3) HasSummerTrail() bool {
	if o != nil && o.SummerTrail.IsSet() {
		return true
	}

	return false
}

// SetSummerTrail gets a reference to the given NullableSummerTrail and assigns it to the SummerTrail field.
func (o *TrailMapElementOneOf3) SetSummerTrail(v SummerTrail) {
	o.SummerTrail.Set(&v)
}
// SetSummerTrailNil sets the value for SummerTrail to be an explicit nil
func (o *TrailMapElementOneOf3) SetSummerTrailNil() {
	o.SummerTrail.Set(nil)
}

// UnsetSummerTrail ensures that no value is present for SummerTrail, not even an explicit nil
func (o *TrailMapElementOneOf3) UnsetSummerTrail() {
	o.SummerTrail.Unset()
}

func (o TrailMapElementOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrailMapElementOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["uuid"] = o.Uuid
	toSerialize["points"] = o.Points
	if o.Tension.IsSet() {
		toSerialize["tension"] = o.Tension.Get()
	}
	if o.SummerTrail.IsSet() {
		toSerialize["summer_trail"] = o.SummerTrail.Get()
	}
	return toSerialize, nil
}

func (o *TrailMapElementOneOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"uuid",
		"points",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrailMapElementOneOf3 := _TrailMapElementOneOf3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrailMapElementOneOf3)

	if err != nil {
		return err
	}

	*o = TrailMapElementOneOf3(varTrailMapElementOneOf3)

	return err
}

type NullableTrailMapElementOneOf3 struct {
	value *TrailMapElementOneOf3
	isSet bool
}

func (v NullableTrailMapElementOneOf3) Get() *TrailMapElementOneOf3 {
	return v.value
}

func (v *NullableTrailMapElementOneOf3) Set(val *TrailMapElementOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableTrailMapElementOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableTrailMapElementOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrailMapElementOneOf3(val *TrailMapElementOneOf3) *NullableTrailMapElementOneOf3 {
	return &NullableTrailMapElementOneOf3{value: val, isSet: true}
}

func (v NullableTrailMapElementOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrailMapElementOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


