/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Schedule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Schedule{}

// Schedule Recurring schedule pattern with human-readable and machine-readable formats.   Describes a regular operating schedule (e.g., \"Weekends 10am-4pm\") with  both formatted strings for display and structured data for programmatic use.
type Schedule struct {
	// Human-readable description of which days this schedule applies to.  Examples: \"Daily\", \"Saturday & Sunday\", \"Monday, Wednesday, and Friday\"
	DaysString string `json:"days_string"`
	// Array of days of the week this schedule applies to.  For programmatic use.
	DaysOfWeek []DayOfWeek `json:"days_of_week"`
	// Human-readable time range.  Example: \"9:00 a.m. to 4:00 p.m.\"
	TimeString string `json:"time_string"`
	// Opening time in 24-hour format (HH:MM), in resort's local timezone.
	OpensAt string `json:"opens_at" validate:"regexp=^([01]\\\\d|2[0-3]):[0-5]\\\\d$"`
	// Closing time in 24-hour format (HH:MM), in resort's local timezone.
	ClosesAt string `json:"closes_at" validate:"regexp=^([01]\\\\d|2[0-3]):[0-5]\\\\d$"`
	// Whether this schedule is currently in effect.  `false` for upcoming schedules that haven't started yet.
	InEffect bool `json:"in_effect"`
	// Human-readable date range when this schedule is effective.  Example: \"November 1, 2024 to April 15, 2025\"
	EffectiveString string `json:"effective_string"`
	// Start date of the effective period (YYYY-MM-DD).
	EffectiveFrom string `json:"effective_from"`
	// End date of the effective period (YYYY-MM-DD).
	EffectiveTo string `json:"effective_to"`
}

type _Schedule Schedule

// NewSchedule instantiates a new Schedule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchedule(daysString string, daysOfWeek []DayOfWeek, timeString string, opensAt string, closesAt string, inEffect bool, effectiveString string, effectiveFrom string, effectiveTo string) *Schedule {
	this := Schedule{}
	this.DaysString = daysString
	this.DaysOfWeek = daysOfWeek
	this.TimeString = timeString
	this.OpensAt = opensAt
	this.ClosesAt = closesAt
	this.InEffect = inEffect
	this.EffectiveString = effectiveString
	this.EffectiveFrom = effectiveFrom
	this.EffectiveTo = effectiveTo
	return &this
}

// NewScheduleWithDefaults instantiates a new Schedule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScheduleWithDefaults() *Schedule {
	this := Schedule{}
	return &this
}

// GetDaysString returns the DaysString field value
func (o *Schedule) GetDaysString() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DaysString
}

// GetDaysStringOk returns a tuple with the DaysString field value
// and a boolean to check if the value has been set.
func (o *Schedule) GetDaysStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DaysString, true
}

// SetDaysString sets field value
func (o *Schedule) SetDaysString(v string) {
	o.DaysString = v
}

// GetDaysOfWeek returns the DaysOfWeek field value
func (o *Schedule) GetDaysOfWeek() []DayOfWeek {
	if o == nil {
		var ret []DayOfWeek
		return ret
	}

	return o.DaysOfWeek
}

// GetDaysOfWeekOk returns a tuple with the DaysOfWeek field value
// and a boolean to check if the value has been set.
func (o *Schedule) GetDaysOfWeekOk() ([]DayOfWeek, bool) {
	if o == nil {
		return nil, false
	}
	return o.DaysOfWeek, true
}

// SetDaysOfWeek sets field value
func (o *Schedule) SetDaysOfWeek(v []DayOfWeek) {
	o.DaysOfWeek = v
}

// GetTimeString returns the TimeString field value
func (o *Schedule) GetTimeString() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TimeString
}

// GetTimeStringOk returns a tuple with the TimeString field value
// and a boolean to check if the value has been set.
func (o *Schedule) GetTimeStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeString, true
}

// SetTimeString sets field value
func (o *Schedule) SetTimeString(v string) {
	o.TimeString = v
}

// GetOpensAt returns the OpensAt field value
func (o *Schedule) GetOpensAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OpensAt
}

// GetOpensAtOk returns a tuple with the OpensAt field value
// and a boolean to check if the value has been set.
func (o *Schedule) GetOpensAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OpensAt, true
}

// SetOpensAt sets field value
func (o *Schedule) SetOpensAt(v string) {
	o.OpensAt = v
}

// GetClosesAt returns the ClosesAt field value
func (o *Schedule) GetClosesAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClosesAt
}

// GetClosesAtOk returns a tuple with the ClosesAt field value
// and a boolean to check if the value has been set.
func (o *Schedule) GetClosesAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClosesAt, true
}

// SetClosesAt sets field value
func (o *Schedule) SetClosesAt(v string) {
	o.ClosesAt = v
}

// GetInEffect returns the InEffect field value
func (o *Schedule) GetInEffect() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.InEffect
}

// GetInEffectOk returns a tuple with the InEffect field value
// and a boolean to check if the value has been set.
func (o *Schedule) GetInEffectOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InEffect, true
}

// SetInEffect sets field value
func (o *Schedule) SetInEffect(v bool) {
	o.InEffect = v
}

// GetEffectiveString returns the EffectiveString field value
func (o *Schedule) GetEffectiveString() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EffectiveString
}

// GetEffectiveStringOk returns a tuple with the EffectiveString field value
// and a boolean to check if the value has been set.
func (o *Schedule) GetEffectiveStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveString, true
}

// SetEffectiveString sets field value
func (o *Schedule) SetEffectiveString(v string) {
	o.EffectiveString = v
}

// GetEffectiveFrom returns the EffectiveFrom field value
func (o *Schedule) GetEffectiveFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EffectiveFrom
}

// GetEffectiveFromOk returns a tuple with the EffectiveFrom field value
// and a boolean to check if the value has been set.
func (o *Schedule) GetEffectiveFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveFrom, true
}

// SetEffectiveFrom sets field value
func (o *Schedule) SetEffectiveFrom(v string) {
	o.EffectiveFrom = v
}

// GetEffectiveTo returns the EffectiveTo field value
func (o *Schedule) GetEffectiveTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EffectiveTo
}

// GetEffectiveToOk returns a tuple with the EffectiveTo field value
// and a boolean to check if the value has been set.
func (o *Schedule) GetEffectiveToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveTo, true
}

// SetEffectiveTo sets field value
func (o *Schedule) SetEffectiveTo(v string) {
	o.EffectiveTo = v
}

func (o Schedule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Schedule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["days_string"] = o.DaysString
	toSerialize["days_of_week"] = o.DaysOfWeek
	toSerialize["time_string"] = o.TimeString
	toSerialize["opens_at"] = o.OpensAt
	toSerialize["closes_at"] = o.ClosesAt
	toSerialize["in_effect"] = o.InEffect
	toSerialize["effective_string"] = o.EffectiveString
	toSerialize["effective_from"] = o.EffectiveFrom
	toSerialize["effective_to"] = o.EffectiveTo
	return toSerialize, nil
}

func (o *Schedule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"days_string",
		"days_of_week",
		"time_string",
		"opens_at",
		"closes_at",
		"in_effect",
		"effective_string",
		"effective_from",
		"effective_to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSchedule := _Schedule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSchedule)

	if err != nil {
		return err
	}

	*o = Schedule(varSchedule)

	return err
}

type NullableSchedule struct {
	value *Schedule
	isSet bool
}

func (v NullableSchedule) Get() *Schedule {
	return v.value
}

func (v *NullableSchedule) Set(val *Schedule) {
	v.value = val
	v.isSet = true
}

func (v NullableSchedule) IsSet() bool {
	return v.isSet
}

func (v *NullableSchedule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchedule(val *Schedule) *NullableSchedule {
	return &NullableSchedule{value: val, isSet: true}
}

func (v NullableSchedule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchedule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


