/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SeasonPeriod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SeasonPeriod{}

// SeasonPeriod A season the resort's operating hours define: its type and its days.
type SeasonPeriod struct {
	// The season's type (`winter` or `summer`; never `closed`).
	SeasonType SeasonType `json:"season_type"`
	// The season's first day (YYYY-MM-DD), in the resort's local timezone.
	StartsOn string `json:"starts_on"`
	// The season's last day (YYYY-MM-DD), in the resort's local timezone.
	EndsOn string `json:"ends_on"`
}

type _SeasonPeriod SeasonPeriod

// NewSeasonPeriod instantiates a new SeasonPeriod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSeasonPeriod(seasonType SeasonType, startsOn string, endsOn string) *SeasonPeriod {
	this := SeasonPeriod{}
	this.SeasonType = seasonType
	this.StartsOn = startsOn
	this.EndsOn = endsOn
	return &this
}

// NewSeasonPeriodWithDefaults instantiates a new SeasonPeriod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSeasonPeriodWithDefaults() *SeasonPeriod {
	this := SeasonPeriod{}
	return &this
}

// GetSeasonType returns the SeasonType field value
func (o *SeasonPeriod) GetSeasonType() SeasonType {
	if o == nil {
		var ret SeasonType
		return ret
	}

	return o.SeasonType
}

// GetSeasonTypeOk returns a tuple with the SeasonType field value
// and a boolean to check if the value has been set.
func (o *SeasonPeriod) GetSeasonTypeOk() (*SeasonType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SeasonType, true
}

// SetSeasonType sets field value
func (o *SeasonPeriod) SetSeasonType(v SeasonType) {
	o.SeasonType = v
}

// GetStartsOn returns the StartsOn field value
func (o *SeasonPeriod) GetStartsOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartsOn
}

// GetStartsOnOk returns a tuple with the StartsOn field value
// and a boolean to check if the value has been set.
func (o *SeasonPeriod) GetStartsOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartsOn, true
}

// SetStartsOn sets field value
func (o *SeasonPeriod) SetStartsOn(v string) {
	o.StartsOn = v
}

// GetEndsOn returns the EndsOn field value
func (o *SeasonPeriod) GetEndsOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndsOn
}

// GetEndsOnOk returns a tuple with the EndsOn field value
// and a boolean to check if the value has been set.
func (o *SeasonPeriod) GetEndsOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndsOn, true
}

// SetEndsOn sets field value
func (o *SeasonPeriod) SetEndsOn(v string) {
	o.EndsOn = v
}

func (o SeasonPeriod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SeasonPeriod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["season_type"] = o.SeasonType
	toSerialize["starts_on"] = o.StartsOn
	toSerialize["ends_on"] = o.EndsOn
	return toSerialize, nil
}

func (o *SeasonPeriod) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"season_type",
		"starts_on",
		"ends_on",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSeasonPeriod := _SeasonPeriod{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSeasonPeriod)

	if err != nil {
		return err
	}

	*o = SeasonPeriod(varSeasonPeriod)

	return err
}

type NullableSeasonPeriod struct {
	value *SeasonPeriod
	isSet bool
}

func (v NullableSeasonPeriod) Get() *SeasonPeriod {
	return v.value
}

func (v *NullableSeasonPeriod) Set(val *SeasonPeriod) {
	v.value = val
	v.isSet = true
}

func (v NullableSeasonPeriod) IsSet() bool {
	return v.isSet
}

func (v *NullableSeasonPeriod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSeasonPeriod(val *SeasonPeriod) *NullableSeasonPeriod {
	return &NullableSeasonPeriod{value: val, isSet: true}
}

func (v NullableSeasonPeriod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSeasonPeriod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


