/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SnowMetrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnowMetrics{}

// SnowMetrics Contains snowfall totals for various time periods. Values are provided  in the unit indicated by the parent field name (cm or inches).
type SnowMetrics struct {
	// Snowfall during the overnight window (midnight to 9 AM local timezone).
	Overnight int32 `json:"overnight"`
	// Snowfall in the last 24 hours.
	Last24h int32 `json:"last_24h"`
	// Snowfall in the last 48 hours.
	Last48h int32 `json:"last_48h"`
	// Snowfall in the last 7 days.
	Last7days int32 `json:"last_7days"`
	// Total snowfall for the current season.
	SeasonTotal int32 `json:"season_total"`
}

type _SnowMetrics SnowMetrics

// NewSnowMetrics instantiates a new SnowMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnowMetrics(overnight int32, last24h int32, last48h int32, last7days int32, seasonTotal int32) *SnowMetrics {
	this := SnowMetrics{}
	this.Overnight = overnight
	this.Last24h = last24h
	this.Last48h = last48h
	this.Last7days = last7days
	this.SeasonTotal = seasonTotal
	return &this
}

// NewSnowMetricsWithDefaults instantiates a new SnowMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnowMetricsWithDefaults() *SnowMetrics {
	this := SnowMetrics{}
	return &this
}

// GetOvernight returns the Overnight field value
func (o *SnowMetrics) GetOvernight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Overnight
}

// GetOvernightOk returns a tuple with the Overnight field value
// and a boolean to check if the value has been set.
func (o *SnowMetrics) GetOvernightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Overnight, true
}

// SetOvernight sets field value
func (o *SnowMetrics) SetOvernight(v int32) {
	o.Overnight = v
}

// GetLast24h returns the Last24h field value
func (o *SnowMetrics) GetLast24h() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Last24h
}

// GetLast24hOk returns a tuple with the Last24h field value
// and a boolean to check if the value has been set.
func (o *SnowMetrics) GetLast24hOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Last24h, true
}

// SetLast24h sets field value
func (o *SnowMetrics) SetLast24h(v int32) {
	o.Last24h = v
}

// GetLast48h returns the Last48h field value
func (o *SnowMetrics) GetLast48h() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Last48h
}

// GetLast48hOk returns a tuple with the Last48h field value
// and a boolean to check if the value has been set.
func (o *SnowMetrics) GetLast48hOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Last48h, true
}

// SetLast48h sets field value
func (o *SnowMetrics) SetLast48h(v int32) {
	o.Last48h = v
}

// GetLast7days returns the Last7days field value
func (o *SnowMetrics) GetLast7days() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Last7days
}

// GetLast7daysOk returns a tuple with the Last7days field value
// and a boolean to check if the value has been set.
func (o *SnowMetrics) GetLast7daysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Last7days, true
}

// SetLast7days sets field value
func (o *SnowMetrics) SetLast7days(v int32) {
	o.Last7days = v
}

// GetSeasonTotal returns the SeasonTotal field value
func (o *SnowMetrics) GetSeasonTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SeasonTotal
}

// GetSeasonTotalOk returns a tuple with the SeasonTotal field value
// and a boolean to check if the value has been set.
func (o *SnowMetrics) GetSeasonTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SeasonTotal, true
}

// SetSeasonTotal sets field value
func (o *SnowMetrics) SetSeasonTotal(v int32) {
	o.SeasonTotal = v
}

func (o SnowMetrics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SnowMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["overnight"] = o.Overnight
	toSerialize["last_24h"] = o.Last24h
	toSerialize["last_48h"] = o.Last48h
	toSerialize["last_7days"] = o.Last7days
	toSerialize["season_total"] = o.SeasonTotal
	return toSerialize, nil
}

func (o *SnowMetrics) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"overnight",
		"last_24h",
		"last_48h",
		"last_7days",
		"season_total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSnowMetrics := _SnowMetrics{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSnowMetrics)

	if err != nil {
		return err
	}

	*o = SnowMetrics(varSnowMetrics)

	return err
}

type NullableSnowMetrics struct {
	value *SnowMetrics
	isSet bool
}

func (v NullableSnowMetrics) Get() *SnowMetrics {
	return v.value
}

func (v *NullableSnowMetrics) Set(val *SnowMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableSnowMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableSnowMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnowMetrics(val *SnowMetrics) *NullableSnowMetrics {
	return &NullableSnowMetrics{value: val, isSet: true}
}

func (v NullableSnowMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnowMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


