/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// GeometryMode the model 'GeometryMode'
type GeometryMode string

// List of GeometryMode
const (
	PATH GeometryMode = "path"
	POLYGON GeometryMode = "polygon"
	GEOMETRYMODE_UNKNOWN_DEFAULT_OPEN_API GeometryMode = "unknown_default_open_api"
)

// All allowed values of GeometryMode enum
var AllowedGeometryModeEnumValues = []GeometryMode{
	"path",
	"polygon",
	"unknown_default_open_api",
}

func (v *GeometryMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GeometryMode(value)
	for _, existing := range AllowedGeometryModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = GEOMETRYMODE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewGeometryModeFromValue returns a pointer to a valid GeometryMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGeometryModeFromValue(v string) (*GeometryMode, error) {
	ev := GeometryMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GeometryMode: valid values are %v", v, AllowedGeometryModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GeometryMode) IsValid() bool {
	for _, existing := range AllowedGeometryModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GeometryMode value
func (v GeometryMode) Ptr() *GeometryMode {
	return &v
}

type NullableGeometryMode struct {
	value *GeometryMode
	isSet bool
}

func (v NullableGeometryMode) Get() *GeometryMode {
	return v.value
}

func (v *NullableGeometryMode) Set(val *GeometryMode) {
	v.value = val
	v.isSet = true
}

func (v NullableGeometryMode) IsSet() bool {
	return v.isSet
}

func (v *NullableGeometryMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeometryMode(val *GeometryMode) *NullableGeometryMode {
	return &NullableGeometryMode{value: val, isSet: true}
}

func (v NullableGeometryMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeometryMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

