/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// SeasonType - Current operating season of the resort.
type SeasonType struct {
	String *string
}

// stringAsSeasonType is a convenience function that returns string wrapped in SeasonType
func StringAsSeasonType(v *string) SeasonType {
	return SeasonType{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *SeasonType) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(SeasonType)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(SeasonType)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SeasonType) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SeasonType) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj SeasonType) GetActualInstanceValue() (interface{}) {
	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableSeasonType struct {
	value *SeasonType
	isSet bool
}

func (v NullableSeasonType) Get() *SeasonType {
	return v.value
}

func (v *NullableSeasonType) Set(val *SeasonType) {
	v.value = val
	v.isSet = true
}

func (v NullableSeasonType) IsSet() bool {
	return v.isSet
}

func (v *NullableSeasonType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSeasonType(val *SeasonType) *NullableSeasonType {
	return &NullableSeasonType{value: val, isSet: true}
}

func (v NullableSeasonType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSeasonType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


