/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LabelOffset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelOffset{}

// LabelOffset struct for LabelOffset
type LabelOffset struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type _LabelOffset LabelOffset

// NewLabelOffset instantiates a new LabelOffset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelOffset(x float64, y float64) *LabelOffset {
	this := LabelOffset{}
	this.X = x
	this.Y = y
	return &this
}

// NewLabelOffsetWithDefaults instantiates a new LabelOffset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelOffsetWithDefaults() *LabelOffset {
	this := LabelOffset{}
	return &this
}

// GetX returns the X field value
func (o *LabelOffset) GetX() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *LabelOffset) GetXOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *LabelOffset) SetX(v float64) {
	o.X = v
}

// GetY returns the Y field value
func (o *LabelOffset) GetY() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *LabelOffset) GetYOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *LabelOffset) SetY(v float64) {
	o.Y = v
}

func (o LabelOffset) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelOffset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y
	return toSerialize, nil
}

func (o *LabelOffset) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"x",
		"y",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLabelOffset := _LabelOffset{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLabelOffset)

	if err != nil {
		return err
	}

	*o = LabelOffset(varLabelOffset)

	return err
}

type NullableLabelOffset struct {
	value *LabelOffset
	isSet bool
}

func (v NullableLabelOffset) Get() *LabelOffset {
	return v.value
}

func (v *NullableLabelOffset) Set(val *LabelOffset) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelOffset) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelOffset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelOffset(val *LabelOffset) *NullableLabelOffset {
	return &NullableLabelOffset{value: val, isSet: true}
}

func (v NullableLabelOffset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelOffset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


