/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// TerrainParkFeatureStatus Operational status of a terrain park feature.
type TerrainParkFeatureStatus string

// List of TerrainParkFeatureStatus
const (
	OPEN TerrainParkFeatureStatus = "open"
	CLOSED TerrainParkFeatureStatus = "closed"
	UNKNOWN TerrainParkFeatureStatus = "unknown"
)

// All allowed values of TerrainParkFeatureStatus enum
var AllowedTerrainParkFeatureStatusEnumValues = []TerrainParkFeatureStatus{
	"open",
	"closed",
	"unknown",
}

func (v *TerrainParkFeatureStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TerrainParkFeatureStatus(value)
	for _, existing := range AllowedTerrainParkFeatureStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TerrainParkFeatureStatus", value)
}

// NewTerrainParkFeatureStatusFromValue returns a pointer to a valid TerrainParkFeatureStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTerrainParkFeatureStatusFromValue(v string) (*TerrainParkFeatureStatus, error) {
	ev := TerrainParkFeatureStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TerrainParkFeatureStatus: valid values are %v", v, AllowedTerrainParkFeatureStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TerrainParkFeatureStatus) IsValid() bool {
	for _, existing := range AllowedTerrainParkFeatureStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TerrainParkFeatureStatus value
func (v TerrainParkFeatureStatus) Ptr() *TerrainParkFeatureStatus {
	return &v
}

type NullableTerrainParkFeatureStatus struct {
	value *TerrainParkFeatureStatus
	isSet bool
}

func (v NullableTerrainParkFeatureStatus) Get() *TerrainParkFeatureStatus {
	return v.value
}

func (v *NullableTerrainParkFeatureStatus) Set(val *TerrainParkFeatureStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableTerrainParkFeatureStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableTerrainParkFeatureStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerrainParkFeatureStatus(val *TerrainParkFeatureStatus) *NullableTerrainParkFeatureStatus {
	return &NullableTerrainParkFeatureStatus{value: val, isSet: true}
}

func (v NullableTerrainParkFeatureStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerrainParkFeatureStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

