/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrailMapStaticElementOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrailMapStaticElementOneOf2{}

// TrailMapStaticElementOneOf2 struct for TrailMapStaticElementOneOf2
type TrailMapStaticElementOneOf2 struct {
	Type string `json:"type"`
	Uuid string `json:"uuid"`
	Points []float64 `json:"points"`
	Tension NullableFloat64 `json:"tension,omitempty"`
	Geometry NullableGeometryMode `json:"geometry,omitempty"`
	LabelOffset NullableLabelOffset `json:"label_offset,omitempty"`
	TerrainParkUuid string `json:"terrain_park_uuid"`
}

type _TrailMapStaticElementOneOf2 TrailMapStaticElementOneOf2

// NewTrailMapStaticElementOneOf2 instantiates a new TrailMapStaticElementOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrailMapStaticElementOneOf2(type_ string, uuid string, points []float64, terrainParkUuid string) *TrailMapStaticElementOneOf2 {
	this := TrailMapStaticElementOneOf2{}
	this.Type = type_
	this.Uuid = uuid
	this.Points = points
	this.TerrainParkUuid = terrainParkUuid
	return &this
}

// NewTrailMapStaticElementOneOf2WithDefaults instantiates a new TrailMapStaticElementOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrailMapStaticElementOneOf2WithDefaults() *TrailMapStaticElementOneOf2 {
	this := TrailMapStaticElementOneOf2{}
	return &this
}

// GetType returns the Type field value
func (o *TrailMapStaticElementOneOf2) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TrailMapStaticElementOneOf2) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TrailMapStaticElementOneOf2) SetType(v string) {
	o.Type = v
}

// GetUuid returns the Uuid field value
func (o *TrailMapStaticElementOneOf2) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *TrailMapStaticElementOneOf2) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *TrailMapStaticElementOneOf2) SetUuid(v string) {
	o.Uuid = v
}

// GetPoints returns the Points field value
func (o *TrailMapStaticElementOneOf2) GetPoints() []float64 {
	if o == nil {
		var ret []float64
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *TrailMapStaticElementOneOf2) GetPointsOk() ([]float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Points, true
}

// SetPoints sets field value
func (o *TrailMapStaticElementOneOf2) SetPoints(v []float64) {
	o.Points = v
}

// GetTension returns the Tension field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapStaticElementOneOf2) GetTension() float64 {
	if o == nil || IsNil(o.Tension.Get()) {
		var ret float64
		return ret
	}
	return *o.Tension.Get()
}

// GetTensionOk returns a tuple with the Tension field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapStaticElementOneOf2) GetTensionOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tension.Get(), o.Tension.IsSet()
}

// HasTension returns a boolean if a field has been set.
func (o *TrailMapStaticElementOneOf2) HasTension() bool {
	if o != nil && o.Tension.IsSet() {
		return true
	}

	return false
}

// SetTension gets a reference to the given NullableFloat64 and assigns it to the Tension field.
func (o *TrailMapStaticElementOneOf2) SetTension(v float64) {
	o.Tension.Set(&v)
}
// SetTensionNil sets the value for Tension to be an explicit nil
func (o *TrailMapStaticElementOneOf2) SetTensionNil() {
	o.Tension.Set(nil)
}

// UnsetTension ensures that no value is present for Tension, not even an explicit nil
func (o *TrailMapStaticElementOneOf2) UnsetTension() {
	o.Tension.Unset()
}

// GetGeometry returns the Geometry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapStaticElementOneOf2) GetGeometry() GeometryMode {
	if o == nil || IsNil(o.Geometry.Get()) {
		var ret GeometryMode
		return ret
	}
	return *o.Geometry.Get()
}

// GetGeometryOk returns a tuple with the Geometry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapStaticElementOneOf2) GetGeometryOk() (*GeometryMode, bool) {
	if o == nil {
		return nil, false
	}
	return o.Geometry.Get(), o.Geometry.IsSet()
}

// HasGeometry returns a boolean if a field has been set.
func (o *TrailMapStaticElementOneOf2) HasGeometry() bool {
	if o != nil && o.Geometry.IsSet() {
		return true
	}

	return false
}

// SetGeometry gets a reference to the given NullableGeometryMode and assigns it to the Geometry field.
func (o *TrailMapStaticElementOneOf2) SetGeometry(v GeometryMode) {
	o.Geometry.Set(&v)
}
// SetGeometryNil sets the value for Geometry to be an explicit nil
func (o *TrailMapStaticElementOneOf2) SetGeometryNil() {
	o.Geometry.Set(nil)
}

// UnsetGeometry ensures that no value is present for Geometry, not even an explicit nil
func (o *TrailMapStaticElementOneOf2) UnsetGeometry() {
	o.Geometry.Unset()
}

// GetLabelOffset returns the LabelOffset field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapStaticElementOneOf2) GetLabelOffset() LabelOffset {
	if o == nil || IsNil(o.LabelOffset.Get()) {
		var ret LabelOffset
		return ret
	}
	return *o.LabelOffset.Get()
}

// GetLabelOffsetOk returns a tuple with the LabelOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapStaticElementOneOf2) GetLabelOffsetOk() (*LabelOffset, bool) {
	if o == nil {
		return nil, false
	}
	return o.LabelOffset.Get(), o.LabelOffset.IsSet()
}

// HasLabelOffset returns a boolean if a field has been set.
func (o *TrailMapStaticElementOneOf2) HasLabelOffset() bool {
	if o != nil && o.LabelOffset.IsSet() {
		return true
	}

	return false
}

// SetLabelOffset gets a reference to the given NullableLabelOffset and assigns it to the LabelOffset field.
func (o *TrailMapStaticElementOneOf2) SetLabelOffset(v LabelOffset) {
	o.LabelOffset.Set(&v)
}
// SetLabelOffsetNil sets the value for LabelOffset to be an explicit nil
func (o *TrailMapStaticElementOneOf2) SetLabelOffsetNil() {
	o.LabelOffset.Set(nil)
}

// UnsetLabelOffset ensures that no value is present for LabelOffset, not even an explicit nil
func (o *TrailMapStaticElementOneOf2) UnsetLabelOffset() {
	o.LabelOffset.Unset()
}

// GetTerrainParkUuid returns the TerrainParkUuid field value
func (o *TrailMapStaticElementOneOf2) GetTerrainParkUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TerrainParkUuid
}

// GetTerrainParkUuidOk returns a tuple with the TerrainParkUuid field value
// and a boolean to check if the value has been set.
func (o *TrailMapStaticElementOneOf2) GetTerrainParkUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TerrainParkUuid, true
}

// SetTerrainParkUuid sets field value
func (o *TrailMapStaticElementOneOf2) SetTerrainParkUuid(v string) {
	o.TerrainParkUuid = v
}

func (o TrailMapStaticElementOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrailMapStaticElementOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["uuid"] = o.Uuid
	toSerialize["points"] = o.Points
	if o.Tension.IsSet() {
		toSerialize["tension"] = o.Tension.Get()
	}
	if o.Geometry.IsSet() {
		toSerialize["geometry"] = o.Geometry.Get()
	}
	if o.LabelOffset.IsSet() {
		toSerialize["label_offset"] = o.LabelOffset.Get()
	}
	toSerialize["terrain_park_uuid"] = o.TerrainParkUuid
	return toSerialize, nil
}

func (o *TrailMapStaticElementOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"uuid",
		"points",
		"terrain_park_uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrailMapStaticElementOneOf2 := _TrailMapStaticElementOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrailMapStaticElementOneOf2)

	if err != nil {
		return err
	}

	*o = TrailMapStaticElementOneOf2(varTrailMapStaticElementOneOf2)

	return err
}

type NullableTrailMapStaticElementOneOf2 struct {
	value *TrailMapStaticElementOneOf2
	isSet bool
}

func (v NullableTrailMapStaticElementOneOf2) Get() *TrailMapStaticElementOneOf2 {
	return v.value
}

func (v *NullableTrailMapStaticElementOneOf2) Set(val *TrailMapStaticElementOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableTrailMapStaticElementOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableTrailMapStaticElementOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrailMapStaticElementOneOf2(val *TrailMapStaticElementOneOf2) *NullableTrailMapStaticElementOneOf2 {
	return &NullableTrailMapStaticElementOneOf2{value: val, isSet: true}
}

func (v NullableTrailMapStaticElementOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrailMapStaticElementOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


