/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CalendarDay type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalendarDay{}

// CalendarDay Operating hours for a specific calendar date.   Represents the calculated open/close times for a single day, combining  information from recurring schedules and any single-day overrides.
type CalendarDay struct {
	// Calendar date (YYYY-MM-DD).
	Date string `json:"date"`
	// Day of the week.
	DayOfWeek DayOfWeek `json:"day_of_week"`
	// Whether the resort is open on this day.
	IsOpen bool `json:"is_open"`
	// Opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if closed on this day.
	OpensAt NullableString `json:"opens_at,omitempty" validate:"regexp=^([01]\\\\d|2[0-3]):[0-5]\\\\d$"`
	// Closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if closed on this day.
	ClosesAt NullableString `json:"closes_at,omitempty" validate:"regexp=^([01]\\\\d|2[0-3]):[0-5]\\\\d$"`
	ClosureReason NullableClosureReason `json:"closure_reason,omitempty"`
	// Special event for this day.
	SpecialEvent NullableString `json:"special_event,omitempty"`
}

type _CalendarDay CalendarDay

// NewCalendarDay instantiates a new CalendarDay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalendarDay(date string, dayOfWeek DayOfWeek, isOpen bool) *CalendarDay {
	this := CalendarDay{}
	this.Date = date
	this.DayOfWeek = dayOfWeek
	this.IsOpen = isOpen
	return &this
}

// NewCalendarDayWithDefaults instantiates a new CalendarDay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalendarDayWithDefaults() *CalendarDay {
	this := CalendarDay{}
	return &this
}

// GetDate returns the Date field value
func (o *CalendarDay) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *CalendarDay) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *CalendarDay) SetDate(v string) {
	o.Date = v
}

// GetDayOfWeek returns the DayOfWeek field value
func (o *CalendarDay) GetDayOfWeek() DayOfWeek {
	if o == nil {
		var ret DayOfWeek
		return ret
	}

	return o.DayOfWeek
}

// GetDayOfWeekOk returns a tuple with the DayOfWeek field value
// and a boolean to check if the value has been set.
func (o *CalendarDay) GetDayOfWeekOk() (*DayOfWeek, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DayOfWeek, true
}

// SetDayOfWeek sets field value
func (o *CalendarDay) SetDayOfWeek(v DayOfWeek) {
	o.DayOfWeek = v
}

// GetIsOpen returns the IsOpen field value
func (o *CalendarDay) GetIsOpen() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsOpen
}

// GetIsOpenOk returns a tuple with the IsOpen field value
// and a boolean to check if the value has been set.
func (o *CalendarDay) GetIsOpenOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsOpen, true
}

// SetIsOpen sets field value
func (o *CalendarDay) SetIsOpen(v bool) {
	o.IsOpen = v
}

// GetOpensAt returns the OpensAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CalendarDay) GetOpensAt() string {
	if o == nil || IsNil(o.OpensAt.Get()) {
		var ret string
		return ret
	}
	return *o.OpensAt.Get()
}

// GetOpensAtOk returns a tuple with the OpensAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CalendarDay) GetOpensAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OpensAt.Get(), o.OpensAt.IsSet()
}

// HasOpensAt returns a boolean if a field has been set.
func (o *CalendarDay) HasOpensAt() bool {
	if o != nil && o.OpensAt.IsSet() {
		return true
	}

	return false
}

// SetOpensAt gets a reference to the given NullableString and assigns it to the OpensAt field.
func (o *CalendarDay) SetOpensAt(v string) {
	o.OpensAt.Set(&v)
}
// SetOpensAtNil sets the value for OpensAt to be an explicit nil
func (o *CalendarDay) SetOpensAtNil() {
	o.OpensAt.Set(nil)
}

// UnsetOpensAt ensures that no value is present for OpensAt, not even an explicit nil
func (o *CalendarDay) UnsetOpensAt() {
	o.OpensAt.Unset()
}

// GetClosesAt returns the ClosesAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CalendarDay) GetClosesAt() string {
	if o == nil || IsNil(o.ClosesAt.Get()) {
		var ret string
		return ret
	}
	return *o.ClosesAt.Get()
}

// GetClosesAtOk returns a tuple with the ClosesAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CalendarDay) GetClosesAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClosesAt.Get(), o.ClosesAt.IsSet()
}

// HasClosesAt returns a boolean if a field has been set.
func (o *CalendarDay) HasClosesAt() bool {
	if o != nil && o.ClosesAt.IsSet() {
		return true
	}

	return false
}

// SetClosesAt gets a reference to the given NullableString and assigns it to the ClosesAt field.
func (o *CalendarDay) SetClosesAt(v string) {
	o.ClosesAt.Set(&v)
}
// SetClosesAtNil sets the value for ClosesAt to be an explicit nil
func (o *CalendarDay) SetClosesAtNil() {
	o.ClosesAt.Set(nil)
}

// UnsetClosesAt ensures that no value is present for ClosesAt, not even an explicit nil
func (o *CalendarDay) UnsetClosesAt() {
	o.ClosesAt.Unset()
}

// GetClosureReason returns the ClosureReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CalendarDay) GetClosureReason() ClosureReason {
	if o == nil || IsNil(o.ClosureReason.Get()) {
		var ret ClosureReason
		return ret
	}
	return *o.ClosureReason.Get()
}

// GetClosureReasonOk returns a tuple with the ClosureReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CalendarDay) GetClosureReasonOk() (*ClosureReason, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClosureReason.Get(), o.ClosureReason.IsSet()
}

// HasClosureReason returns a boolean if a field has been set.
func (o *CalendarDay) HasClosureReason() bool {
	if o != nil && o.ClosureReason.IsSet() {
		return true
	}

	return false
}

// SetClosureReason gets a reference to the given NullableClosureReason and assigns it to the ClosureReason field.
func (o *CalendarDay) SetClosureReason(v ClosureReason) {
	o.ClosureReason.Set(&v)
}
// SetClosureReasonNil sets the value for ClosureReason to be an explicit nil
func (o *CalendarDay) SetClosureReasonNil() {
	o.ClosureReason.Set(nil)
}

// UnsetClosureReason ensures that no value is present for ClosureReason, not even an explicit nil
func (o *CalendarDay) UnsetClosureReason() {
	o.ClosureReason.Unset()
}

// GetSpecialEvent returns the SpecialEvent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CalendarDay) GetSpecialEvent() string {
	if o == nil || IsNil(o.SpecialEvent.Get()) {
		var ret string
		return ret
	}
	return *o.SpecialEvent.Get()
}

// GetSpecialEventOk returns a tuple with the SpecialEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CalendarDay) GetSpecialEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpecialEvent.Get(), o.SpecialEvent.IsSet()
}

// HasSpecialEvent returns a boolean if a field has been set.
func (o *CalendarDay) HasSpecialEvent() bool {
	if o != nil && o.SpecialEvent.IsSet() {
		return true
	}

	return false
}

// SetSpecialEvent gets a reference to the given NullableString and assigns it to the SpecialEvent field.
func (o *CalendarDay) SetSpecialEvent(v string) {
	o.SpecialEvent.Set(&v)
}
// SetSpecialEventNil sets the value for SpecialEvent to be an explicit nil
func (o *CalendarDay) SetSpecialEventNil() {
	o.SpecialEvent.Set(nil)
}

// UnsetSpecialEvent ensures that no value is present for SpecialEvent, not even an explicit nil
func (o *CalendarDay) UnsetSpecialEvent() {
	o.SpecialEvent.Unset()
}

func (o CalendarDay) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalendarDay) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["day_of_week"] = o.DayOfWeek
	toSerialize["is_open"] = o.IsOpen
	if o.OpensAt.IsSet() {
		toSerialize["opens_at"] = o.OpensAt.Get()
	}
	if o.ClosesAt.IsSet() {
		toSerialize["closes_at"] = o.ClosesAt.Get()
	}
	if o.ClosureReason.IsSet() {
		toSerialize["closure_reason"] = o.ClosureReason.Get()
	}
	if o.SpecialEvent.IsSet() {
		toSerialize["special_event"] = o.SpecialEvent.Get()
	}
	return toSerialize, nil
}

func (o *CalendarDay) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"day_of_week",
		"is_open",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCalendarDay := _CalendarDay{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCalendarDay)

	if err != nil {
		return err
	}

	*o = CalendarDay(varCalendarDay)

	return err
}

type NullableCalendarDay struct {
	value *CalendarDay
	isSet bool
}

func (v NullableCalendarDay) Get() *CalendarDay {
	return v.value
}

func (v *NullableCalendarDay) Set(val *CalendarDay) {
	v.value = val
	v.isSet = true
}

func (v NullableCalendarDay) IsSet() bool {
	return v.isSet
}

func (v *NullableCalendarDay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalendarDay(val *CalendarDay) *NullableCalendarDay {
	return &NullableCalendarDay{value: val, isSet: true}
}

func (v NullableCalendarDay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalendarDay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


