/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrailMapElementOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrailMapElementOneOf1{}

// TrailMapElementOneOf1 struct for TrailMapElementOneOf1
type TrailMapElementOneOf1 struct {
	Type string `json:"type"`
	Uuid string `json:"uuid"`
	Points []float64 `json:"points"`
	Tension NullableFloat64 `json:"tension,omitempty"`
	Run NullableRun `json:"run,omitempty"`
}

type _TrailMapElementOneOf1 TrailMapElementOneOf1

// NewTrailMapElementOneOf1 instantiates a new TrailMapElementOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrailMapElementOneOf1(type_ string, uuid string, points []float64) *TrailMapElementOneOf1 {
	this := TrailMapElementOneOf1{}
	this.Type = type_
	this.Uuid = uuid
	this.Points = points
	return &this
}

// NewTrailMapElementOneOf1WithDefaults instantiates a new TrailMapElementOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrailMapElementOneOf1WithDefaults() *TrailMapElementOneOf1 {
	this := TrailMapElementOneOf1{}
	return &this
}

// GetType returns the Type field value
func (o *TrailMapElementOneOf1) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf1) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TrailMapElementOneOf1) SetType(v string) {
	o.Type = v
}

// GetUuid returns the Uuid field value
func (o *TrailMapElementOneOf1) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf1) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *TrailMapElementOneOf1) SetUuid(v string) {
	o.Uuid = v
}

// GetPoints returns the Points field value
func (o *TrailMapElementOneOf1) GetPoints() []float64 {
	if o == nil {
		var ret []float64
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf1) GetPointsOk() ([]float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Points, true
}

// SetPoints sets field value
func (o *TrailMapElementOneOf1) SetPoints(v []float64) {
	o.Points = v
}

// GetTension returns the Tension field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf1) GetTension() float64 {
	if o == nil || IsNil(o.Tension.Get()) {
		var ret float64
		return ret
	}
	return *o.Tension.Get()
}

// GetTensionOk returns a tuple with the Tension field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf1) GetTensionOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tension.Get(), o.Tension.IsSet()
}

// HasTension returns a boolean if a field has been set.
func (o *TrailMapElementOneOf1) HasTension() bool {
	if o != nil && o.Tension.IsSet() {
		return true
	}

	return false
}

// SetTension gets a reference to the given NullableFloat64 and assigns it to the Tension field.
func (o *TrailMapElementOneOf1) SetTension(v float64) {
	o.Tension.Set(&v)
}
// SetTensionNil sets the value for Tension to be an explicit nil
func (o *TrailMapElementOneOf1) SetTensionNil() {
	o.Tension.Set(nil)
}

// UnsetTension ensures that no value is present for Tension, not even an explicit nil
func (o *TrailMapElementOneOf1) UnsetTension() {
	o.Tension.Unset()
}

// GetRun returns the Run field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf1) GetRun() Run {
	if o == nil || IsNil(o.Run.Get()) {
		var ret Run
		return ret
	}
	return *o.Run.Get()
}

// GetRunOk returns a tuple with the Run field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf1) GetRunOk() (*Run, bool) {
	if o == nil {
		return nil, false
	}
	return o.Run.Get(), o.Run.IsSet()
}

// HasRun returns a boolean if a field has been set.
func (o *TrailMapElementOneOf1) HasRun() bool {
	if o != nil && o.Run.IsSet() {
		return true
	}

	return false
}

// SetRun gets a reference to the given NullableRun and assigns it to the Run field.
func (o *TrailMapElementOneOf1) SetRun(v Run) {
	o.Run.Set(&v)
}
// SetRunNil sets the value for Run to be an explicit nil
func (o *TrailMapElementOneOf1) SetRunNil() {
	o.Run.Set(nil)
}

// UnsetRun ensures that no value is present for Run, not even an explicit nil
func (o *TrailMapElementOneOf1) UnsetRun() {
	o.Run.Unset()
}

func (o TrailMapElementOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrailMapElementOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["uuid"] = o.Uuid
	toSerialize["points"] = o.Points
	if o.Tension.IsSet() {
		toSerialize["tension"] = o.Tension.Get()
	}
	if o.Run.IsSet() {
		toSerialize["run"] = o.Run.Get()
	}
	return toSerialize, nil
}

func (o *TrailMapElementOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"uuid",
		"points",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrailMapElementOneOf1 := _TrailMapElementOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrailMapElementOneOf1)

	if err != nil {
		return err
	}

	*o = TrailMapElementOneOf1(varTrailMapElementOneOf1)

	return err
}

type NullableTrailMapElementOneOf1 struct {
	value *TrailMapElementOneOf1
	isSet bool
}

func (v NullableTrailMapElementOneOf1) Get() *TrailMapElementOneOf1 {
	return v.value
}

func (v *NullableTrailMapElementOneOf1) Set(val *TrailMapElementOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableTrailMapElementOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableTrailMapElementOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrailMapElementOneOf1(val *TrailMapElementOneOf1) *NullableTrailMapElementOneOf1 {
	return &NullableTrailMapElementOneOf1{value: val, isSet: true}
}

func (v NullableTrailMapElementOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrailMapElementOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


