/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// TerrainParkStatus Operational status of a terrain park.
type TerrainParkStatus string

// List of TerrainParkStatus
const (
	OPEN TerrainParkStatus = "open"
	CLOSED TerrainParkStatus = "closed"
	UNKNOWN TerrainParkStatus = "unknown"
)

// All allowed values of TerrainParkStatus enum
var AllowedTerrainParkStatusEnumValues = []TerrainParkStatus{
	"open",
	"closed",
	"unknown",
}

func (v *TerrainParkStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TerrainParkStatus(value)
	for _, existing := range AllowedTerrainParkStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TerrainParkStatus", value)
}

// NewTerrainParkStatusFromValue returns a pointer to a valid TerrainParkStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTerrainParkStatusFromValue(v string) (*TerrainParkStatus, error) {
	ev := TerrainParkStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TerrainParkStatus: valid values are %v", v, AllowedTerrainParkStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TerrainParkStatus) IsValid() bool {
	for _, existing := range AllowedTerrainParkStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TerrainParkStatus value
func (v TerrainParkStatus) Ptr() *TerrainParkStatus {
	return &v
}

type NullableTerrainParkStatus struct {
	value *TerrainParkStatus
	isSet bool
}

func (v NullableTerrainParkStatus) Get() *TerrainParkStatus {
	return v.value
}

func (v *NullableTerrainParkStatus) Set(val *TerrainParkStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableTerrainParkStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableTerrainParkStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerrainParkStatus(val *TerrainParkStatus) *NullableTerrainParkStatus {
	return &NullableTerrainParkStatus{value: val, isSet: true}
}

func (v NullableTerrainParkStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerrainParkStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

