/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// SummerTrailType the model 'SummerTrailType'
type SummerTrailType string

// List of SummerTrailType
const (
	HIKING SummerTrailType = "hiking"
	MOUNTAIN_BIKING SummerTrailType = "mountain_biking"
)

// All allowed values of SummerTrailType enum
var AllowedSummerTrailTypeEnumValues = []SummerTrailType{
	"hiking",
	"mountain_biking",
}

func (v *SummerTrailType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SummerTrailType(value)
	for _, existing := range AllowedSummerTrailTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SummerTrailType", value)
}

// NewSummerTrailTypeFromValue returns a pointer to a valid SummerTrailType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSummerTrailTypeFromValue(v string) (*SummerTrailType, error) {
	ev := SummerTrailType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SummerTrailType: valid values are %v", v, AllowedSummerTrailTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SummerTrailType) IsValid() bool {
	for _, existing := range AllowedSummerTrailTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SummerTrailType value
func (v SummerTrailType) Ptr() *SummerTrailType {
	return &v
}

type NullableSummerTrailType struct {
	value *SummerTrailType
	isSet bool
}

func (v NullableSummerTrailType) Get() *SummerTrailType {
	return v.value
}

func (v *NullableSummerTrailType) Set(val *SummerTrailType) {
	v.value = val
	v.isSet = true
}

func (v NullableSummerTrailType) IsSet() bool {
	return v.isSet
}

func (v *NullableSummerTrailType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummerTrailType(val *SummerTrailType) *NullableSummerTrailType {
	return &NullableSummerTrailType{value: val, isSet: true}
}

func (v NullableSummerTrailType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummerTrailType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

