/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrailMapElementOneOf6 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrailMapElementOneOf6{}

// TrailMapElementOneOf6 struct for TrailMapElementOneOf6
type TrailMapElementOneOf6 struct {
	Type string `json:"type"`
	Uuid string `json:"uuid"`
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Icon NullableMarkerIcon `json:"icon,omitempty"`
	Color NullableString `json:"color,omitempty"`
	Label string `json:"label"`
	Searchable NullableBool `json:"searchable,omitempty"`
}

type _TrailMapElementOneOf6 TrailMapElementOneOf6

// NewTrailMapElementOneOf6 instantiates a new TrailMapElementOneOf6 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrailMapElementOneOf6(type_ string, uuid string, x float64, y float64, label string) *TrailMapElementOneOf6 {
	this := TrailMapElementOneOf6{}
	this.Type = type_
	this.Uuid = uuid
	this.X = x
	this.Y = y
	this.Label = label
	return &this
}

// NewTrailMapElementOneOf6WithDefaults instantiates a new TrailMapElementOneOf6 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrailMapElementOneOf6WithDefaults() *TrailMapElementOneOf6 {
	this := TrailMapElementOneOf6{}
	return &this
}

// GetType returns the Type field value
func (o *TrailMapElementOneOf6) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf6) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TrailMapElementOneOf6) SetType(v string) {
	o.Type = v
}

// GetUuid returns the Uuid field value
func (o *TrailMapElementOneOf6) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf6) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *TrailMapElementOneOf6) SetUuid(v string) {
	o.Uuid = v
}

// GetX returns the X field value
func (o *TrailMapElementOneOf6) GetX() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf6) GetXOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *TrailMapElementOneOf6) SetX(v float64) {
	o.X = v
}

// GetY returns the Y field value
func (o *TrailMapElementOneOf6) GetY() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf6) GetYOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *TrailMapElementOneOf6) SetY(v float64) {
	o.Y = v
}

// GetIcon returns the Icon field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf6) GetIcon() MarkerIcon {
	if o == nil || IsNil(o.Icon.Get()) {
		var ret MarkerIcon
		return ret
	}
	return *o.Icon.Get()
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf6) GetIconOk() (*MarkerIcon, bool) {
	if o == nil {
		return nil, false
	}
	return o.Icon.Get(), o.Icon.IsSet()
}

// HasIcon returns a boolean if a field has been set.
func (o *TrailMapElementOneOf6) HasIcon() bool {
	if o != nil && o.Icon.IsSet() {
		return true
	}

	return false
}

// SetIcon gets a reference to the given NullableMarkerIcon and assigns it to the Icon field.
func (o *TrailMapElementOneOf6) SetIcon(v MarkerIcon) {
	o.Icon.Set(&v)
}
// SetIconNil sets the value for Icon to be an explicit nil
func (o *TrailMapElementOneOf6) SetIconNil() {
	o.Icon.Set(nil)
}

// UnsetIcon ensures that no value is present for Icon, not even an explicit nil
func (o *TrailMapElementOneOf6) UnsetIcon() {
	o.Icon.Unset()
}

// GetColor returns the Color field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf6) GetColor() string {
	if o == nil || IsNil(o.Color.Get()) {
		var ret string
		return ret
	}
	return *o.Color.Get()
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf6) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Color.Get(), o.Color.IsSet()
}

// HasColor returns a boolean if a field has been set.
func (o *TrailMapElementOneOf6) HasColor() bool {
	if o != nil && o.Color.IsSet() {
		return true
	}

	return false
}

// SetColor gets a reference to the given NullableString and assigns it to the Color field.
func (o *TrailMapElementOneOf6) SetColor(v string) {
	o.Color.Set(&v)
}
// SetColorNil sets the value for Color to be an explicit nil
func (o *TrailMapElementOneOf6) SetColorNil() {
	o.Color.Set(nil)
}

// UnsetColor ensures that no value is present for Color, not even an explicit nil
func (o *TrailMapElementOneOf6) UnsetColor() {
	o.Color.Unset()
}

// GetLabel returns the Label field value
func (o *TrailMapElementOneOf6) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf6) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *TrailMapElementOneOf6) SetLabel(v string) {
	o.Label = v
}

// GetSearchable returns the Searchable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf6) GetSearchable() bool {
	if o == nil || IsNil(o.Searchable.Get()) {
		var ret bool
		return ret
	}
	return *o.Searchable.Get()
}

// GetSearchableOk returns a tuple with the Searchable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf6) GetSearchableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Searchable.Get(), o.Searchable.IsSet()
}

// HasSearchable returns a boolean if a field has been set.
func (o *TrailMapElementOneOf6) HasSearchable() bool {
	if o != nil && o.Searchable.IsSet() {
		return true
	}

	return false
}

// SetSearchable gets a reference to the given NullableBool and assigns it to the Searchable field.
func (o *TrailMapElementOneOf6) SetSearchable(v bool) {
	o.Searchable.Set(&v)
}
// SetSearchableNil sets the value for Searchable to be an explicit nil
func (o *TrailMapElementOneOf6) SetSearchableNil() {
	o.Searchable.Set(nil)
}

// UnsetSearchable ensures that no value is present for Searchable, not even an explicit nil
func (o *TrailMapElementOneOf6) UnsetSearchable() {
	o.Searchable.Unset()
}

func (o TrailMapElementOneOf6) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrailMapElementOneOf6) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["uuid"] = o.Uuid
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y
	if o.Icon.IsSet() {
		toSerialize["icon"] = o.Icon.Get()
	}
	if o.Color.IsSet() {
		toSerialize["color"] = o.Color.Get()
	}
	toSerialize["label"] = o.Label
	if o.Searchable.IsSet() {
		toSerialize["searchable"] = o.Searchable.Get()
	}
	return toSerialize, nil
}

func (o *TrailMapElementOneOf6) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"uuid",
		"x",
		"y",
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrailMapElementOneOf6 := _TrailMapElementOneOf6{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrailMapElementOneOf6)

	if err != nil {
		return err
	}

	*o = TrailMapElementOneOf6(varTrailMapElementOneOf6)

	return err
}

type NullableTrailMapElementOneOf6 struct {
	value *TrailMapElementOneOf6
	isSet bool
}

func (v NullableTrailMapElementOneOf6) Get() *TrailMapElementOneOf6 {
	return v.value
}

func (v *NullableTrailMapElementOneOf6) Set(val *TrailMapElementOneOf6) {
	v.value = val
	v.isSet = true
}

func (v NullableTrailMapElementOneOf6) IsSet() bool {
	return v.isSet
}

func (v *NullableTrailMapElementOneOf6) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrailMapElementOneOf6(val *TrailMapElementOneOf6) *NullableTrailMapElementOneOf6 {
	return &NullableTrailMapElementOneOf6{value: val, isSet: true}
}

func (v NullableTrailMapElementOneOf6) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrailMapElementOneOf6) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


