/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SnowReport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SnowReport{}

// SnowReport Provides current snow conditions for a specific area or the entire resort,  including base depth, surface conditions, and snowfall totals in both  metric and imperial units.
type SnowReport struct {
	// Unique identifier for this snow report.
	Uuid string `json:"uuid"`
	// UUID of the area this report covers, if area-specific.  `null` for resort-wide reports.
	AreaUuid NullableString `json:"area_uuid,omitempty"`
	// Name of the area this report covers, if area-specific.
	AreaName NullableString `json:"area_name,omitempty"`
	// Display order of the area this report covers, if area-specific, for sorting purposes.
	AreaDisplayOrder NullableInt32 `json:"area_display_order,omitempty"`
	// Current base depth in centimeters.  Not included if the base depth feature is disabled.
	BaseDepthCm NullableInt32 `json:"base_depth_cm,omitempty"`
	// Current base depth in inches.  Not included if the base depth feature is disabled.
	BaseDepthIn NullableInt32 `json:"base_depth_in,omitempty"`
	SurfaceCondition NullableSurfaceCondition `json:"surface_condition,omitempty"`
	SecondarySurfaceCondition NullableSurfaceCondition `json:"secondary_surface_condition,omitempty"`
	// Additional notes about current snow conditions, e.g. groomer's notes
	ConditionNotes string `json:"condition_notes"`
	// Snowfall accumulation metrics in centimeters.
	SnowfallCm SnowMetrics `json:"snowfall_cm"`
	// Snowfall accumulation metrics in inches.
	SnowfallIn SnowMetrics `json:"snowfall_in"`
	// When this snow report was last updated.
	ReportedAt time.Time `json:"reported_at"`
}

type _SnowReport SnowReport

// NewSnowReport instantiates a new SnowReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnowReport(uuid string, conditionNotes string, snowfallCm SnowMetrics, snowfallIn SnowMetrics, reportedAt time.Time) *SnowReport {
	this := SnowReport{}
	this.Uuid = uuid
	this.ConditionNotes = conditionNotes
	this.SnowfallCm = snowfallCm
	this.SnowfallIn = snowfallIn
	this.ReportedAt = reportedAt
	return &this
}

// NewSnowReportWithDefaults instantiates a new SnowReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnowReportWithDefaults() *SnowReport {
	this := SnowReport{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *SnowReport) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *SnowReport) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *SnowReport) SetUuid(v string) {
	o.Uuid = v
}

// GetAreaUuid returns the AreaUuid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SnowReport) GetAreaUuid() string {
	if o == nil || IsNil(o.AreaUuid.Get()) {
		var ret string
		return ret
	}
	return *o.AreaUuid.Get()
}

// GetAreaUuidOk returns a tuple with the AreaUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SnowReport) GetAreaUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaUuid.Get(), o.AreaUuid.IsSet()
}

// HasAreaUuid returns a boolean if a field has been set.
func (o *SnowReport) HasAreaUuid() bool {
	if o != nil && o.AreaUuid.IsSet() {
		return true
	}

	return false
}

// SetAreaUuid gets a reference to the given NullableString and assigns it to the AreaUuid field.
func (o *SnowReport) SetAreaUuid(v string) {
	o.AreaUuid.Set(&v)
}
// SetAreaUuidNil sets the value for AreaUuid to be an explicit nil
func (o *SnowReport) SetAreaUuidNil() {
	o.AreaUuid.Set(nil)
}

// UnsetAreaUuid ensures that no value is present for AreaUuid, not even an explicit nil
func (o *SnowReport) UnsetAreaUuid() {
	o.AreaUuid.Unset()
}

// GetAreaName returns the AreaName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SnowReport) GetAreaName() string {
	if o == nil || IsNil(o.AreaName.Get()) {
		var ret string
		return ret
	}
	return *o.AreaName.Get()
}

// GetAreaNameOk returns a tuple with the AreaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SnowReport) GetAreaNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaName.Get(), o.AreaName.IsSet()
}

// HasAreaName returns a boolean if a field has been set.
func (o *SnowReport) HasAreaName() bool {
	if o != nil && o.AreaName.IsSet() {
		return true
	}

	return false
}

// SetAreaName gets a reference to the given NullableString and assigns it to the AreaName field.
func (o *SnowReport) SetAreaName(v string) {
	o.AreaName.Set(&v)
}
// SetAreaNameNil sets the value for AreaName to be an explicit nil
func (o *SnowReport) SetAreaNameNil() {
	o.AreaName.Set(nil)
}

// UnsetAreaName ensures that no value is present for AreaName, not even an explicit nil
func (o *SnowReport) UnsetAreaName() {
	o.AreaName.Unset()
}

// GetAreaDisplayOrder returns the AreaDisplayOrder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SnowReport) GetAreaDisplayOrder() int32 {
	if o == nil || IsNil(o.AreaDisplayOrder.Get()) {
		var ret int32
		return ret
	}
	return *o.AreaDisplayOrder.Get()
}

// GetAreaDisplayOrderOk returns a tuple with the AreaDisplayOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SnowReport) GetAreaDisplayOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaDisplayOrder.Get(), o.AreaDisplayOrder.IsSet()
}

// HasAreaDisplayOrder returns a boolean if a field has been set.
func (o *SnowReport) HasAreaDisplayOrder() bool {
	if o != nil && o.AreaDisplayOrder.IsSet() {
		return true
	}

	return false
}

// SetAreaDisplayOrder gets a reference to the given NullableInt32 and assigns it to the AreaDisplayOrder field.
func (o *SnowReport) SetAreaDisplayOrder(v int32) {
	o.AreaDisplayOrder.Set(&v)
}
// SetAreaDisplayOrderNil sets the value for AreaDisplayOrder to be an explicit nil
func (o *SnowReport) SetAreaDisplayOrderNil() {
	o.AreaDisplayOrder.Set(nil)
}

// UnsetAreaDisplayOrder ensures that no value is present for AreaDisplayOrder, not even an explicit nil
func (o *SnowReport) UnsetAreaDisplayOrder() {
	o.AreaDisplayOrder.Unset()
}

// GetBaseDepthCm returns the BaseDepthCm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SnowReport) GetBaseDepthCm() int32 {
	if o == nil || IsNil(o.BaseDepthCm.Get()) {
		var ret int32
		return ret
	}
	return *o.BaseDepthCm.Get()
}

// GetBaseDepthCmOk returns a tuple with the BaseDepthCm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SnowReport) GetBaseDepthCmOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseDepthCm.Get(), o.BaseDepthCm.IsSet()
}

// HasBaseDepthCm returns a boolean if a field has been set.
func (o *SnowReport) HasBaseDepthCm() bool {
	if o != nil && o.BaseDepthCm.IsSet() {
		return true
	}

	return false
}

// SetBaseDepthCm gets a reference to the given NullableInt32 and assigns it to the BaseDepthCm field.
func (o *SnowReport) SetBaseDepthCm(v int32) {
	o.BaseDepthCm.Set(&v)
}
// SetBaseDepthCmNil sets the value for BaseDepthCm to be an explicit nil
func (o *SnowReport) SetBaseDepthCmNil() {
	o.BaseDepthCm.Set(nil)
}

// UnsetBaseDepthCm ensures that no value is present for BaseDepthCm, not even an explicit nil
func (o *SnowReport) UnsetBaseDepthCm() {
	o.BaseDepthCm.Unset()
}

// GetBaseDepthIn returns the BaseDepthIn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SnowReport) GetBaseDepthIn() int32 {
	if o == nil || IsNil(o.BaseDepthIn.Get()) {
		var ret int32
		return ret
	}
	return *o.BaseDepthIn.Get()
}

// GetBaseDepthInOk returns a tuple with the BaseDepthIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SnowReport) GetBaseDepthInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseDepthIn.Get(), o.BaseDepthIn.IsSet()
}

// HasBaseDepthIn returns a boolean if a field has been set.
func (o *SnowReport) HasBaseDepthIn() bool {
	if o != nil && o.BaseDepthIn.IsSet() {
		return true
	}

	return false
}

// SetBaseDepthIn gets a reference to the given NullableInt32 and assigns it to the BaseDepthIn field.
func (o *SnowReport) SetBaseDepthIn(v int32) {
	o.BaseDepthIn.Set(&v)
}
// SetBaseDepthInNil sets the value for BaseDepthIn to be an explicit nil
func (o *SnowReport) SetBaseDepthInNil() {
	o.BaseDepthIn.Set(nil)
}

// UnsetBaseDepthIn ensures that no value is present for BaseDepthIn, not even an explicit nil
func (o *SnowReport) UnsetBaseDepthIn() {
	o.BaseDepthIn.Unset()
}

// GetSurfaceCondition returns the SurfaceCondition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SnowReport) GetSurfaceCondition() SurfaceCondition {
	if o == nil || IsNil(o.SurfaceCondition.Get()) {
		var ret SurfaceCondition
		return ret
	}
	return *o.SurfaceCondition.Get()
}

// GetSurfaceConditionOk returns a tuple with the SurfaceCondition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SnowReport) GetSurfaceConditionOk() (*SurfaceCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.SurfaceCondition.Get(), o.SurfaceCondition.IsSet()
}

// HasSurfaceCondition returns a boolean if a field has been set.
func (o *SnowReport) HasSurfaceCondition() bool {
	if o != nil && o.SurfaceCondition.IsSet() {
		return true
	}

	return false
}

// SetSurfaceCondition gets a reference to the given NullableSurfaceCondition and assigns it to the SurfaceCondition field.
func (o *SnowReport) SetSurfaceCondition(v SurfaceCondition) {
	o.SurfaceCondition.Set(&v)
}
// SetSurfaceConditionNil sets the value for SurfaceCondition to be an explicit nil
func (o *SnowReport) SetSurfaceConditionNil() {
	o.SurfaceCondition.Set(nil)
}

// UnsetSurfaceCondition ensures that no value is present for SurfaceCondition, not even an explicit nil
func (o *SnowReport) UnsetSurfaceCondition() {
	o.SurfaceCondition.Unset()
}

// GetSecondarySurfaceCondition returns the SecondarySurfaceCondition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SnowReport) GetSecondarySurfaceCondition() SurfaceCondition {
	if o == nil || IsNil(o.SecondarySurfaceCondition.Get()) {
		var ret SurfaceCondition
		return ret
	}
	return *o.SecondarySurfaceCondition.Get()
}

// GetSecondarySurfaceConditionOk returns a tuple with the SecondarySurfaceCondition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SnowReport) GetSecondarySurfaceConditionOk() (*SurfaceCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecondarySurfaceCondition.Get(), o.SecondarySurfaceCondition.IsSet()
}

// HasSecondarySurfaceCondition returns a boolean if a field has been set.
func (o *SnowReport) HasSecondarySurfaceCondition() bool {
	if o != nil && o.SecondarySurfaceCondition.IsSet() {
		return true
	}

	return false
}

// SetSecondarySurfaceCondition gets a reference to the given NullableSurfaceCondition and assigns it to the SecondarySurfaceCondition field.
func (o *SnowReport) SetSecondarySurfaceCondition(v SurfaceCondition) {
	o.SecondarySurfaceCondition.Set(&v)
}
// SetSecondarySurfaceConditionNil sets the value for SecondarySurfaceCondition to be an explicit nil
func (o *SnowReport) SetSecondarySurfaceConditionNil() {
	o.SecondarySurfaceCondition.Set(nil)
}

// UnsetSecondarySurfaceCondition ensures that no value is present for SecondarySurfaceCondition, not even an explicit nil
func (o *SnowReport) UnsetSecondarySurfaceCondition() {
	o.SecondarySurfaceCondition.Unset()
}

// GetConditionNotes returns the ConditionNotes field value
func (o *SnowReport) GetConditionNotes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConditionNotes
}

// GetConditionNotesOk returns a tuple with the ConditionNotes field value
// and a boolean to check if the value has been set.
func (o *SnowReport) GetConditionNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionNotes, true
}

// SetConditionNotes sets field value
func (o *SnowReport) SetConditionNotes(v string) {
	o.ConditionNotes = v
}

// GetSnowfallCm returns the SnowfallCm field value
func (o *SnowReport) GetSnowfallCm() SnowMetrics {
	if o == nil {
		var ret SnowMetrics
		return ret
	}

	return o.SnowfallCm
}

// GetSnowfallCmOk returns a tuple with the SnowfallCm field value
// and a boolean to check if the value has been set.
func (o *SnowReport) GetSnowfallCmOk() (*SnowMetrics, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SnowfallCm, true
}

// SetSnowfallCm sets field value
func (o *SnowReport) SetSnowfallCm(v SnowMetrics) {
	o.SnowfallCm = v
}

// GetSnowfallIn returns the SnowfallIn field value
func (o *SnowReport) GetSnowfallIn() SnowMetrics {
	if o == nil {
		var ret SnowMetrics
		return ret
	}

	return o.SnowfallIn
}

// GetSnowfallInOk returns a tuple with the SnowfallIn field value
// and a boolean to check if the value has been set.
func (o *SnowReport) GetSnowfallInOk() (*SnowMetrics, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SnowfallIn, true
}

// SetSnowfallIn sets field value
func (o *SnowReport) SetSnowfallIn(v SnowMetrics) {
	o.SnowfallIn = v
}

// GetReportedAt returns the ReportedAt field value
func (o *SnowReport) GetReportedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ReportedAt
}

// GetReportedAtOk returns a tuple with the ReportedAt field value
// and a boolean to check if the value has been set.
func (o *SnowReport) GetReportedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReportedAt, true
}

// SetReportedAt sets field value
func (o *SnowReport) SetReportedAt(v time.Time) {
	o.ReportedAt = v
}

func (o SnowReport) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SnowReport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	if o.AreaUuid.IsSet() {
		toSerialize["area_uuid"] = o.AreaUuid.Get()
	}
	if o.AreaName.IsSet() {
		toSerialize["area_name"] = o.AreaName.Get()
	}
	if o.AreaDisplayOrder.IsSet() {
		toSerialize["area_display_order"] = o.AreaDisplayOrder.Get()
	}
	if o.BaseDepthCm.IsSet() {
		toSerialize["base_depth_cm"] = o.BaseDepthCm.Get()
	}
	if o.BaseDepthIn.IsSet() {
		toSerialize["base_depth_in"] = o.BaseDepthIn.Get()
	}
	if o.SurfaceCondition.IsSet() {
		toSerialize["surface_condition"] = o.SurfaceCondition.Get()
	}
	if o.SecondarySurfaceCondition.IsSet() {
		toSerialize["secondary_surface_condition"] = o.SecondarySurfaceCondition.Get()
	}
	toSerialize["condition_notes"] = o.ConditionNotes
	toSerialize["snowfall_cm"] = o.SnowfallCm
	toSerialize["snowfall_in"] = o.SnowfallIn
	toSerialize["reported_at"] = o.ReportedAt
	return toSerialize, nil
}

func (o *SnowReport) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"condition_notes",
		"snowfall_cm",
		"snowfall_in",
		"reported_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSnowReport := _SnowReport{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSnowReport)

	if err != nil {
		return err
	}

	*o = SnowReport(varSnowReport)

	return err
}

type NullableSnowReport struct {
	value *SnowReport
	isSet bool
}

func (v NullableSnowReport) Get() *SnowReport {
	return v.value
}

func (v *NullableSnowReport) Set(val *SnowReport) {
	v.value = val
	v.isSet = true
}

func (v NullableSnowReport) IsSet() bool {
	return v.isSet
}

func (v *NullableSnowReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnowReport(val *SnowReport) *NullableSnowReport {
	return &NullableSnowReport{value: val, isSet: true}
}

func (v NullableSnowReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnowReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


