/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrailMapElementOneOf4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrailMapElementOneOf4{}

// TrailMapElementOneOf4 struct for TrailMapElementOneOf4
type TrailMapElementOneOf4 struct {
	PointMarker
	Type string `json:"type"`
}

type _TrailMapElementOneOf4 TrailMapElementOneOf4

// NewTrailMapElementOneOf4 instantiates a new TrailMapElementOneOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrailMapElementOneOf4(type_ string) *TrailMapElementOneOf4 {
	this := TrailMapElementOneOf4{}
	this.Type = type_
	return &this
}

// NewTrailMapElementOneOf4WithDefaults instantiates a new TrailMapElementOneOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrailMapElementOneOf4WithDefaults() *TrailMapElementOneOf4 {
	this := TrailMapElementOneOf4{}
	return &this
}

// GetType returns the Type field value
func (o *TrailMapElementOneOf4) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf4) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TrailMapElementOneOf4) SetType(v string) {
	o.Type = v
}

func (o TrailMapElementOneOf4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrailMapElementOneOf4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *TrailMapElementOneOf4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrailMapElementOneOf4 := _TrailMapElementOneOf4{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrailMapElementOneOf4)

	if err != nil {
		return err
	}

	*o = TrailMapElementOneOf4(varTrailMapElementOneOf4)

	return err
}

type NullableTrailMapElementOneOf4 struct {
	value *TrailMapElementOneOf4
	isSet bool
}

func (v NullableTrailMapElementOneOf4) Get() *TrailMapElementOneOf4 {
	return v.value
}

func (v *NullableTrailMapElementOneOf4) Set(val *TrailMapElementOneOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableTrailMapElementOneOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableTrailMapElementOneOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrailMapElementOneOf4(val *TrailMapElementOneOf4) *NullableTrailMapElementOneOf4 {
	return &NullableTrailMapElementOneOf4{value: val, isSet: true}
}

func (v NullableTrailMapElementOneOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrailMapElementOneOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


