/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrailMapSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrailMapSummary{}

// TrailMapSummary Summary metadata for a trail map.
type TrailMapSummary struct {
	Uuid string `json:"uuid"`
	Name string `json:"name"`
	Season SeasonType `json:"season"`
	DisplayOrder int64 `json:"display_order"`
	HostedUrl string `json:"hosted_url"`
}

type _TrailMapSummary TrailMapSummary

// NewTrailMapSummary instantiates a new TrailMapSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrailMapSummary(uuid string, name string, season SeasonType, displayOrder int64, hostedUrl string) *TrailMapSummary {
	this := TrailMapSummary{}
	this.Uuid = uuid
	this.Name = name
	this.Season = season
	this.DisplayOrder = displayOrder
	this.HostedUrl = hostedUrl
	return &this
}

// NewTrailMapSummaryWithDefaults instantiates a new TrailMapSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrailMapSummaryWithDefaults() *TrailMapSummary {
	this := TrailMapSummary{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *TrailMapSummary) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *TrailMapSummary) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *TrailMapSummary) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *TrailMapSummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TrailMapSummary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TrailMapSummary) SetName(v string) {
	o.Name = v
}

// GetSeason returns the Season field value
func (o *TrailMapSummary) GetSeason() SeasonType {
	if o == nil {
		var ret SeasonType
		return ret
	}

	return o.Season
}

// GetSeasonOk returns a tuple with the Season field value
// and a boolean to check if the value has been set.
func (o *TrailMapSummary) GetSeasonOk() (*SeasonType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Season, true
}

// SetSeason sets field value
func (o *TrailMapSummary) SetSeason(v SeasonType) {
	o.Season = v
}

// GetDisplayOrder returns the DisplayOrder field value
func (o *TrailMapSummary) GetDisplayOrder() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DisplayOrder
}

// GetDisplayOrderOk returns a tuple with the DisplayOrder field value
// and a boolean to check if the value has been set.
func (o *TrailMapSummary) GetDisplayOrderOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayOrder, true
}

// SetDisplayOrder sets field value
func (o *TrailMapSummary) SetDisplayOrder(v int64) {
	o.DisplayOrder = v
}

// GetHostedUrl returns the HostedUrl field value
func (o *TrailMapSummary) GetHostedUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HostedUrl
}

// GetHostedUrlOk returns a tuple with the HostedUrl field value
// and a boolean to check if the value has been set.
func (o *TrailMapSummary) GetHostedUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostedUrl, true
}

// SetHostedUrl sets field value
func (o *TrailMapSummary) SetHostedUrl(v string) {
	o.HostedUrl = v
}

func (o TrailMapSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrailMapSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["season"] = o.Season
	toSerialize["display_order"] = o.DisplayOrder
	toSerialize["hosted_url"] = o.HostedUrl
	return toSerialize, nil
}

func (o *TrailMapSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
		"season",
		"display_order",
		"hosted_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrailMapSummary := _TrailMapSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrailMapSummary)

	if err != nil {
		return err
	}

	*o = TrailMapSummary(varTrailMapSummary)

	return err
}

type NullableTrailMapSummary struct {
	value *TrailMapSummary
	isSet bool
}

func (v NullableTrailMapSummary) Get() *TrailMapSummary {
	return v.value
}

func (v *NullableTrailMapSummary) Set(val *TrailMapSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableTrailMapSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableTrailMapSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrailMapSummary(val *TrailMapSummary) *NullableTrailMapSummary {
	return &NullableTrailMapSummary{value: val, isSet: true}
}

func (v NullableTrailMapSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrailMapSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


