/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// MarkerIcon the model 'MarkerIcon'
type MarkerIcon string

// List of MarkerIcon
const (
	RESTAURANT MarkerIcon = "restaurant"
	COFFEE MarkerIcon = "coffee"
	BAR MarkerIcon = "bar"
	WATER MarkerIcon = "water"
	SKI_SCHOOL MarkerIcon = "ski_school"
	RENTAL_SHOP MarkerIcon = "rental_shop"
	TUBING MarkerIcon = "tubing"
	DAYCARE MarkerIcon = "daycare"
	TICKETING MarkerIcon = "ticketing"
	LODGE MarkerIcon = "lodge"
	HOTEL MarkerIcon = "hotel"
	RESTROOM MarkerIcon = "restroom"
	LOCKERS MarkerIcon = "lockers"
	FIRST_AID MarkerIcon = "first_aid"
	PARKING MarkerIcon = "parking"
	BUS MarkerIcon = "bus"
	INFO MarkerIcon = "info"
	HELP MarkerIcon = "help"
	PHONE MarkerIcon = "phone"
	RETAIL MarkerIcon = "retail"
	ATM MarkerIcon = "atm"
	STAR MarkerIcon = "star"
)

// All allowed values of MarkerIcon enum
var AllowedMarkerIconEnumValues = []MarkerIcon{
	"restaurant",
	"coffee",
	"bar",
	"water",
	"ski_school",
	"rental_shop",
	"tubing",
	"daycare",
	"ticketing",
	"lodge",
	"hotel",
	"restroom",
	"lockers",
	"first_aid",
	"parking",
	"bus",
	"info",
	"help",
	"phone",
	"retail",
	"atm",
	"star",
}

func (v *MarkerIcon) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MarkerIcon(value)
	for _, existing := range AllowedMarkerIconEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MarkerIcon", value)
}

// NewMarkerIconFromValue returns a pointer to a valid MarkerIcon
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMarkerIconFromValue(v string) (*MarkerIcon, error) {
	ev := MarkerIcon(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MarkerIcon: valid values are %v", v, AllowedMarkerIconEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MarkerIcon) IsValid() bool {
	for _, existing := range AllowedMarkerIconEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MarkerIcon value
func (v MarkerIcon) Ptr() *MarkerIcon {
	return &v
}

type NullableMarkerIcon struct {
	value *MarkerIcon
	isSet bool
}

func (v NullableMarkerIcon) Get() *MarkerIcon {
	return v.value
}

func (v *NullableMarkerIcon) Set(val *MarkerIcon) {
	v.value = val
	v.isSet = true
}

func (v NullableMarkerIcon) IsSet() bool {
	return v.isSet
}

func (v *NullableMarkerIcon) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarkerIcon(val *MarkerIcon) *NullableMarkerIcon {
	return &NullableMarkerIcon{value: val, isSet: true}
}

func (v NullableMarkerIcon) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarkerIcon) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

