/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DailyForecastImperial type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DailyForecastImperial{}

// DailyForecastImperial Daily forecast measurements in imperial units
type DailyForecastImperial struct {
	// High temperature in Fahrenheit
	TemperatureHigh int32 `json:"temperature_high"`
	// Low temperature in Fahrenheit
	TemperatureLow int32 `json:"temperature_low"`
	// Total snowfall expected in inches
	SnowfallTotal NullableInt32 `json:"snowfall_total,omitempty"`
	// Total precipitation expected in inches
	PrecipitationTotal NullableInt32 `json:"precipitation_total,omitempty"`
	// Maximum wind speed in mph
	WindSpeedMax NullableInt32 `json:"wind_speed_max,omitempty"`
	// Maximum wind gust in mph
	WindGustMax NullableInt32 `json:"wind_gust_max,omitempty"`
}

type _DailyForecastImperial DailyForecastImperial

// NewDailyForecastImperial instantiates a new DailyForecastImperial object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDailyForecastImperial(temperatureHigh int32, temperatureLow int32) *DailyForecastImperial {
	this := DailyForecastImperial{}
	this.TemperatureHigh = temperatureHigh
	this.TemperatureLow = temperatureLow
	return &this
}

// NewDailyForecastImperialWithDefaults instantiates a new DailyForecastImperial object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDailyForecastImperialWithDefaults() *DailyForecastImperial {
	this := DailyForecastImperial{}
	return &this
}

// GetTemperatureHigh returns the TemperatureHigh field value
func (o *DailyForecastImperial) GetTemperatureHigh() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TemperatureHigh
}

// GetTemperatureHighOk returns a tuple with the TemperatureHigh field value
// and a boolean to check if the value has been set.
func (o *DailyForecastImperial) GetTemperatureHighOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemperatureHigh, true
}

// SetTemperatureHigh sets field value
func (o *DailyForecastImperial) SetTemperatureHigh(v int32) {
	o.TemperatureHigh = v
}

// GetTemperatureLow returns the TemperatureLow field value
func (o *DailyForecastImperial) GetTemperatureLow() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TemperatureLow
}

// GetTemperatureLowOk returns a tuple with the TemperatureLow field value
// and a boolean to check if the value has been set.
func (o *DailyForecastImperial) GetTemperatureLowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemperatureLow, true
}

// SetTemperatureLow sets field value
func (o *DailyForecastImperial) SetTemperatureLow(v int32) {
	o.TemperatureLow = v
}

// GetSnowfallTotal returns the SnowfallTotal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DailyForecastImperial) GetSnowfallTotal() int32 {
	if o == nil || IsNil(o.SnowfallTotal.Get()) {
		var ret int32
		return ret
	}
	return *o.SnowfallTotal.Get()
}

// GetSnowfallTotalOk returns a tuple with the SnowfallTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DailyForecastImperial) GetSnowfallTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SnowfallTotal.Get(), o.SnowfallTotal.IsSet()
}

// HasSnowfallTotal returns a boolean if a field has been set.
func (o *DailyForecastImperial) HasSnowfallTotal() bool {
	if o != nil && o.SnowfallTotal.IsSet() {
		return true
	}

	return false
}

// SetSnowfallTotal gets a reference to the given NullableInt32 and assigns it to the SnowfallTotal field.
func (o *DailyForecastImperial) SetSnowfallTotal(v int32) {
	o.SnowfallTotal.Set(&v)
}
// SetSnowfallTotalNil sets the value for SnowfallTotal to be an explicit nil
func (o *DailyForecastImperial) SetSnowfallTotalNil() {
	o.SnowfallTotal.Set(nil)
}

// UnsetSnowfallTotal ensures that no value is present for SnowfallTotal, not even an explicit nil
func (o *DailyForecastImperial) UnsetSnowfallTotal() {
	o.SnowfallTotal.Unset()
}

// GetPrecipitationTotal returns the PrecipitationTotal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DailyForecastImperial) GetPrecipitationTotal() int32 {
	if o == nil || IsNil(o.PrecipitationTotal.Get()) {
		var ret int32
		return ret
	}
	return *o.PrecipitationTotal.Get()
}

// GetPrecipitationTotalOk returns a tuple with the PrecipitationTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DailyForecastImperial) GetPrecipitationTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrecipitationTotal.Get(), o.PrecipitationTotal.IsSet()
}

// HasPrecipitationTotal returns a boolean if a field has been set.
func (o *DailyForecastImperial) HasPrecipitationTotal() bool {
	if o != nil && o.PrecipitationTotal.IsSet() {
		return true
	}

	return false
}

// SetPrecipitationTotal gets a reference to the given NullableInt32 and assigns it to the PrecipitationTotal field.
func (o *DailyForecastImperial) SetPrecipitationTotal(v int32) {
	o.PrecipitationTotal.Set(&v)
}
// SetPrecipitationTotalNil sets the value for PrecipitationTotal to be an explicit nil
func (o *DailyForecastImperial) SetPrecipitationTotalNil() {
	o.PrecipitationTotal.Set(nil)
}

// UnsetPrecipitationTotal ensures that no value is present for PrecipitationTotal, not even an explicit nil
func (o *DailyForecastImperial) UnsetPrecipitationTotal() {
	o.PrecipitationTotal.Unset()
}

// GetWindSpeedMax returns the WindSpeedMax field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DailyForecastImperial) GetWindSpeedMax() int32 {
	if o == nil || IsNil(o.WindSpeedMax.Get()) {
		var ret int32
		return ret
	}
	return *o.WindSpeedMax.Get()
}

// GetWindSpeedMaxOk returns a tuple with the WindSpeedMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DailyForecastImperial) GetWindSpeedMaxOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WindSpeedMax.Get(), o.WindSpeedMax.IsSet()
}

// HasWindSpeedMax returns a boolean if a field has been set.
func (o *DailyForecastImperial) HasWindSpeedMax() bool {
	if o != nil && o.WindSpeedMax.IsSet() {
		return true
	}

	return false
}

// SetWindSpeedMax gets a reference to the given NullableInt32 and assigns it to the WindSpeedMax field.
func (o *DailyForecastImperial) SetWindSpeedMax(v int32) {
	o.WindSpeedMax.Set(&v)
}
// SetWindSpeedMaxNil sets the value for WindSpeedMax to be an explicit nil
func (o *DailyForecastImperial) SetWindSpeedMaxNil() {
	o.WindSpeedMax.Set(nil)
}

// UnsetWindSpeedMax ensures that no value is present for WindSpeedMax, not even an explicit nil
func (o *DailyForecastImperial) UnsetWindSpeedMax() {
	o.WindSpeedMax.Unset()
}

// GetWindGustMax returns the WindGustMax field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DailyForecastImperial) GetWindGustMax() int32 {
	if o == nil || IsNil(o.WindGustMax.Get()) {
		var ret int32
		return ret
	}
	return *o.WindGustMax.Get()
}

// GetWindGustMaxOk returns a tuple with the WindGustMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DailyForecastImperial) GetWindGustMaxOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WindGustMax.Get(), o.WindGustMax.IsSet()
}

// HasWindGustMax returns a boolean if a field has been set.
func (o *DailyForecastImperial) HasWindGustMax() bool {
	if o != nil && o.WindGustMax.IsSet() {
		return true
	}

	return false
}

// SetWindGustMax gets a reference to the given NullableInt32 and assigns it to the WindGustMax field.
func (o *DailyForecastImperial) SetWindGustMax(v int32) {
	o.WindGustMax.Set(&v)
}
// SetWindGustMaxNil sets the value for WindGustMax to be an explicit nil
func (o *DailyForecastImperial) SetWindGustMaxNil() {
	o.WindGustMax.Set(nil)
}

// UnsetWindGustMax ensures that no value is present for WindGustMax, not even an explicit nil
func (o *DailyForecastImperial) UnsetWindGustMax() {
	o.WindGustMax.Unset()
}

func (o DailyForecastImperial) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DailyForecastImperial) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["temperature_high"] = o.TemperatureHigh
	toSerialize["temperature_low"] = o.TemperatureLow
	if o.SnowfallTotal.IsSet() {
		toSerialize["snowfall_total"] = o.SnowfallTotal.Get()
	}
	if o.PrecipitationTotal.IsSet() {
		toSerialize["precipitation_total"] = o.PrecipitationTotal.Get()
	}
	if o.WindSpeedMax.IsSet() {
		toSerialize["wind_speed_max"] = o.WindSpeedMax.Get()
	}
	if o.WindGustMax.IsSet() {
		toSerialize["wind_gust_max"] = o.WindGustMax.Get()
	}
	return toSerialize, nil
}

func (o *DailyForecastImperial) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"temperature_high",
		"temperature_low",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDailyForecastImperial := _DailyForecastImperial{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDailyForecastImperial)

	if err != nil {
		return err
	}

	*o = DailyForecastImperial(varDailyForecastImperial)

	return err
}

type NullableDailyForecastImperial struct {
	value *DailyForecastImperial
	isSet bool
}

func (v NullableDailyForecastImperial) Get() *DailyForecastImperial {
	return v.value
}

func (v *NullableDailyForecastImperial) Set(val *DailyForecastImperial) {
	v.value = val
	v.isSet = true
}

func (v NullableDailyForecastImperial) IsSet() bool {
	return v.isSet
}

func (v *NullableDailyForecastImperial) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDailyForecastImperial(val *DailyForecastImperial) *NullableDailyForecastImperial {
	return &NullableDailyForecastImperial{value: val, isSet: true}
}

func (v NullableDailyForecastImperial) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDailyForecastImperial) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


