/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// SeasonType Current operating season of the resort.
type SeasonType string

// List of SeasonType
const (
	WINTER SeasonType = "winter"
	SUMMER SeasonType = "summer"
	CLOSED SeasonType = "closed"
)

// All allowed values of SeasonType enum
var AllowedSeasonTypeEnumValues = []SeasonType{
	"winter",
	"summer",
	"closed",
}

func (v *SeasonType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SeasonType(value)
	for _, existing := range AllowedSeasonTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SeasonType", value)
}

// NewSeasonTypeFromValue returns a pointer to a valid SeasonType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSeasonTypeFromValue(v string) (*SeasonType, error) {
	ev := SeasonType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SeasonType: valid values are %v", v, AllowedSeasonTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SeasonType) IsValid() bool {
	for _, existing := range AllowedSeasonTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SeasonType value
func (v SeasonType) Ptr() *SeasonType {
	return &v
}

type NullableSeasonType struct {
	value *SeasonType
	isSet bool
}

func (v NullableSeasonType) Get() *SeasonType {
	return v.value
}

func (v *NullableSeasonType) Set(val *SeasonType) {
	v.value = val
	v.isSet = true
}

func (v NullableSeasonType) IsSet() bool {
	return v.isSet
}

func (v *NullableSeasonType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSeasonType(val *SeasonType) *NullableSeasonType {
	return &NullableSeasonType{value: val, isSet: true}
}

func (v NullableSeasonType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSeasonType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

