/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// AmenityCategory Category classification for amenities
type AmenityCategory string

// List of AmenityCategory
const (
	RESTAURANT AmenityCategory = "restaurant"
	COFFEE AmenityCategory = "coffee"
	BAR AmenityCategory = "bar"
	TUBING AmenityCategory = "tubing"
	SKI_SCHOOL AmenityCategory = "ski_school"
	RENTAL_SHOP AmenityCategory = "rental_shop"
	DAYCARE AmenityCategory = "daycare"
	TICKETING AmenityCategory = "ticketing"
	LODGE AmenityCategory = "lodge"
	HOTEL AmenityCategory = "hotel"
	LOCKERS AmenityCategory = "lockers"
	RETAIL AmenityCategory = "retail"
	OTHER AmenityCategory = "other"
)

// All allowed values of AmenityCategory enum
var AllowedAmenityCategoryEnumValues = []AmenityCategory{
	"restaurant",
	"coffee",
	"bar",
	"tubing",
	"ski_school",
	"rental_shop",
	"daycare",
	"ticketing",
	"lodge",
	"hotel",
	"lockers",
	"retail",
	"other",
}

func (v *AmenityCategory) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AmenityCategory(value)
	for _, existing := range AllowedAmenityCategoryEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AmenityCategory", value)
}

// NewAmenityCategoryFromValue returns a pointer to a valid AmenityCategory
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAmenityCategoryFromValue(v string) (*AmenityCategory, error) {
	ev := AmenityCategory(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AmenityCategory: valid values are %v", v, AllowedAmenityCategoryEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AmenityCategory) IsValid() bool {
	for _, existing := range AllowedAmenityCategoryEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AmenityCategory value
func (v AmenityCategory) Ptr() *AmenityCategory {
	return &v
}

type NullableAmenityCategory struct {
	value *AmenityCategory
	isSet bool
}

func (v NullableAmenityCategory) Get() *AmenityCategory {
	return v.value
}

func (v *NullableAmenityCategory) Set(val *AmenityCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableAmenityCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableAmenityCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmenityCategory(val *AmenityCategory) *NullableAmenityCategory {
	return &NullableAmenityCategory{value: val, isSet: true}
}

func (v NullableAmenityCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmenityCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

