/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DailyForecast type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DailyForecast{}

// DailyForecast Daily weather summary with both unit systems
type DailyForecast struct {
	// Date of forecast (YYYY-MM-DD format)
	Date string `json:"date"`
	// Measurements in imperial units
	Imperial DailyForecastImperial `json:"imperial"`
	// Measurements in metric units
	Metric DailyForecastMetric `json:"metric"`
	// Human-readable condition
	Condition string `json:"condition"`
	// Condition code
	ConditionCode WeatherConditionCode `json:"condition_code"`
	// Probability of precipitation (0-100%)
	PrecipitationProbability NullableInt32 `json:"precipitation_probability,omitempty"`
	// Sunrise time
	Sunrise time.Time `json:"sunrise"`
	// Sunset time
	Sunset time.Time `json:"sunset"`
}

type _DailyForecast DailyForecast

// NewDailyForecast instantiates a new DailyForecast object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDailyForecast(date string, imperial DailyForecastImperial, metric DailyForecastMetric, condition string, conditionCode WeatherConditionCode, sunrise time.Time, sunset time.Time) *DailyForecast {
	this := DailyForecast{}
	this.Date = date
	this.Imperial = imperial
	this.Metric = metric
	this.Condition = condition
	this.ConditionCode = conditionCode
	this.Sunrise = sunrise
	this.Sunset = sunset
	return &this
}

// NewDailyForecastWithDefaults instantiates a new DailyForecast object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDailyForecastWithDefaults() *DailyForecast {
	this := DailyForecast{}
	return &this
}

// GetDate returns the Date field value
func (o *DailyForecast) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *DailyForecast) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *DailyForecast) SetDate(v string) {
	o.Date = v
}

// GetImperial returns the Imperial field value
func (o *DailyForecast) GetImperial() DailyForecastImperial {
	if o == nil {
		var ret DailyForecastImperial
		return ret
	}

	return o.Imperial
}

// GetImperialOk returns a tuple with the Imperial field value
// and a boolean to check if the value has been set.
func (o *DailyForecast) GetImperialOk() (*DailyForecastImperial, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Imperial, true
}

// SetImperial sets field value
func (o *DailyForecast) SetImperial(v DailyForecastImperial) {
	o.Imperial = v
}

// GetMetric returns the Metric field value
func (o *DailyForecast) GetMetric() DailyForecastMetric {
	if o == nil {
		var ret DailyForecastMetric
		return ret
	}

	return o.Metric
}

// GetMetricOk returns a tuple with the Metric field value
// and a boolean to check if the value has been set.
func (o *DailyForecast) GetMetricOk() (*DailyForecastMetric, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metric, true
}

// SetMetric sets field value
func (o *DailyForecast) SetMetric(v DailyForecastMetric) {
	o.Metric = v
}

// GetCondition returns the Condition field value
func (o *DailyForecast) GetCondition() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *DailyForecast) GetConditionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Condition, true
}

// SetCondition sets field value
func (o *DailyForecast) SetCondition(v string) {
	o.Condition = v
}

// GetConditionCode returns the ConditionCode field value
func (o *DailyForecast) GetConditionCode() WeatherConditionCode {
	if o == nil {
		var ret WeatherConditionCode
		return ret
	}

	return o.ConditionCode
}

// GetConditionCodeOk returns a tuple with the ConditionCode field value
// and a boolean to check if the value has been set.
func (o *DailyForecast) GetConditionCodeOk() (*WeatherConditionCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionCode, true
}

// SetConditionCode sets field value
func (o *DailyForecast) SetConditionCode(v WeatherConditionCode) {
	o.ConditionCode = v
}

// GetPrecipitationProbability returns the PrecipitationProbability field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DailyForecast) GetPrecipitationProbability() int32 {
	if o == nil || IsNil(o.PrecipitationProbability.Get()) {
		var ret int32
		return ret
	}
	return *o.PrecipitationProbability.Get()
}

// GetPrecipitationProbabilityOk returns a tuple with the PrecipitationProbability field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DailyForecast) GetPrecipitationProbabilityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrecipitationProbability.Get(), o.PrecipitationProbability.IsSet()
}

// HasPrecipitationProbability returns a boolean if a field has been set.
func (o *DailyForecast) HasPrecipitationProbability() bool {
	if o != nil && o.PrecipitationProbability.IsSet() {
		return true
	}

	return false
}

// SetPrecipitationProbability gets a reference to the given NullableInt32 and assigns it to the PrecipitationProbability field.
func (o *DailyForecast) SetPrecipitationProbability(v int32) {
	o.PrecipitationProbability.Set(&v)
}
// SetPrecipitationProbabilityNil sets the value for PrecipitationProbability to be an explicit nil
func (o *DailyForecast) SetPrecipitationProbabilityNil() {
	o.PrecipitationProbability.Set(nil)
}

// UnsetPrecipitationProbability ensures that no value is present for PrecipitationProbability, not even an explicit nil
func (o *DailyForecast) UnsetPrecipitationProbability() {
	o.PrecipitationProbability.Unset()
}

// GetSunrise returns the Sunrise field value
func (o *DailyForecast) GetSunrise() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Sunrise
}

// GetSunriseOk returns a tuple with the Sunrise field value
// and a boolean to check if the value has been set.
func (o *DailyForecast) GetSunriseOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sunrise, true
}

// SetSunrise sets field value
func (o *DailyForecast) SetSunrise(v time.Time) {
	o.Sunrise = v
}

// GetSunset returns the Sunset field value
func (o *DailyForecast) GetSunset() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Sunset
}

// GetSunsetOk returns a tuple with the Sunset field value
// and a boolean to check if the value has been set.
func (o *DailyForecast) GetSunsetOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sunset, true
}

// SetSunset sets field value
func (o *DailyForecast) SetSunset(v time.Time) {
	o.Sunset = v
}

func (o DailyForecast) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DailyForecast) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["imperial"] = o.Imperial
	toSerialize["metric"] = o.Metric
	toSerialize["condition"] = o.Condition
	toSerialize["condition_code"] = o.ConditionCode
	if o.PrecipitationProbability.IsSet() {
		toSerialize["precipitation_probability"] = o.PrecipitationProbability.Get()
	}
	toSerialize["sunrise"] = o.Sunrise
	toSerialize["sunset"] = o.Sunset
	return toSerialize, nil
}

func (o *DailyForecast) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"imperial",
		"metric",
		"condition",
		"condition_code",
		"sunrise",
		"sunset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDailyForecast := _DailyForecast{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDailyForecast)

	if err != nil {
		return err
	}

	*o = DailyForecast(varDailyForecast)

	return err
}

type NullableDailyForecast struct {
	value *DailyForecast
	isSet bool
}

func (v NullableDailyForecast) Get() *DailyForecast {
	return v.value
}

func (v *NullableDailyForecast) Set(val *DailyForecast) {
	v.value = val
	v.isSet = true
}

func (v NullableDailyForecast) IsSet() bool {
	return v.isSet
}

func (v *NullableDailyForecast) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDailyForecast(val *DailyForecast) *NullableDailyForecast {
	return &NullableDailyForecast{value: val, isSet: true}
}

func (v NullableDailyForecast) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDailyForecast) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


