/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Weather type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Weather{}

// Weather Current and forecasted weather conditions for the resort's location.  Only included/available if the weather feature is enabled and GPS coordinates are configured.
type Weather struct {
	// Current weather conditions
	Current CurrentWeather `json:"current"`
	// Hourly forecast for next 24 hours (including current hour)
	HourlyForecast []HourlyForecast `json:"hourly_forecast"`
	// Daily forecast for next 7 days (including today)
	DailyForecast []DailyForecast `json:"daily_forecast"`
	// Data source attribution
	Attribution string `json:"attribution"`
	// When this data was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

type _Weather Weather

// NewWeather instantiates a new Weather object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWeather(current CurrentWeather, hourlyForecast []HourlyForecast, dailyForecast []DailyForecast, attribution string, updatedAt time.Time) *Weather {
	this := Weather{}
	this.Current = current
	this.HourlyForecast = hourlyForecast
	this.DailyForecast = dailyForecast
	this.Attribution = attribution
	this.UpdatedAt = updatedAt
	return &this
}

// NewWeatherWithDefaults instantiates a new Weather object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWeatherWithDefaults() *Weather {
	this := Weather{}
	return &this
}

// GetCurrent returns the Current field value
func (o *Weather) GetCurrent() CurrentWeather {
	if o == nil {
		var ret CurrentWeather
		return ret
	}

	return o.Current
}

// GetCurrentOk returns a tuple with the Current field value
// and a boolean to check if the value has been set.
func (o *Weather) GetCurrentOk() (*CurrentWeather, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Current, true
}

// SetCurrent sets field value
func (o *Weather) SetCurrent(v CurrentWeather) {
	o.Current = v
}

// GetHourlyForecast returns the HourlyForecast field value
func (o *Weather) GetHourlyForecast() []HourlyForecast {
	if o == nil {
		var ret []HourlyForecast
		return ret
	}

	return o.HourlyForecast
}

// GetHourlyForecastOk returns a tuple with the HourlyForecast field value
// and a boolean to check if the value has been set.
func (o *Weather) GetHourlyForecastOk() ([]HourlyForecast, bool) {
	if o == nil {
		return nil, false
	}
	return o.HourlyForecast, true
}

// SetHourlyForecast sets field value
func (o *Weather) SetHourlyForecast(v []HourlyForecast) {
	o.HourlyForecast = v
}

// GetDailyForecast returns the DailyForecast field value
func (o *Weather) GetDailyForecast() []DailyForecast {
	if o == nil {
		var ret []DailyForecast
		return ret
	}

	return o.DailyForecast
}

// GetDailyForecastOk returns a tuple with the DailyForecast field value
// and a boolean to check if the value has been set.
func (o *Weather) GetDailyForecastOk() ([]DailyForecast, bool) {
	if o == nil {
		return nil, false
	}
	return o.DailyForecast, true
}

// SetDailyForecast sets field value
func (o *Weather) SetDailyForecast(v []DailyForecast) {
	o.DailyForecast = v
}

// GetAttribution returns the Attribution field value
func (o *Weather) GetAttribution() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Attribution
}

// GetAttributionOk returns a tuple with the Attribution field value
// and a boolean to check if the value has been set.
func (o *Weather) GetAttributionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attribution, true
}

// SetAttribution sets field value
func (o *Weather) SetAttribution(v string) {
	o.Attribution = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Weather) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Weather) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Weather) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o Weather) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Weather) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["current"] = o.Current
	toSerialize["hourly_forecast"] = o.HourlyForecast
	toSerialize["daily_forecast"] = o.DailyForecast
	toSerialize["attribution"] = o.Attribution
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *Weather) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"current",
		"hourly_forecast",
		"daily_forecast",
		"attribution",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWeather := _Weather{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWeather)

	if err != nil {
		return err
	}

	*o = Weather(varWeather)

	return err
}

type NullableWeather struct {
	value *Weather
	isSet bool
}

func (v NullableWeather) Get() *Weather {
	return v.value
}

func (v *NullableWeather) Set(val *Weather) {
	v.value = val
	v.isSet = true
}

func (v NullableWeather) IsSet() bool {
	return v.isSet
}

func (v *NullableWeather) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWeather(val *Weather) *NullableWeather {
	return &NullableWeather{value: val, isSet: true}
}

func (v NullableWeather) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWeather) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


