/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrailMapStaticElementOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrailMapStaticElementOneOf{}

// TrailMapStaticElementOneOf struct for TrailMapStaticElementOneOf
type TrailMapStaticElementOneOf struct {
	Type string `json:"type"`
	Uuid string `json:"uuid"`
	Points []float64 `json:"points"`
	Tension NullableFloat64 `json:"tension,omitempty"`
	LiftUuid string `json:"lift_uuid"`
}

type _TrailMapStaticElementOneOf TrailMapStaticElementOneOf

// NewTrailMapStaticElementOneOf instantiates a new TrailMapStaticElementOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrailMapStaticElementOneOf(type_ string, uuid string, points []float64, liftUuid string) *TrailMapStaticElementOneOf {
	this := TrailMapStaticElementOneOf{}
	this.Type = type_
	this.Uuid = uuid
	this.Points = points
	this.LiftUuid = liftUuid
	return &this
}

// NewTrailMapStaticElementOneOfWithDefaults instantiates a new TrailMapStaticElementOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrailMapStaticElementOneOfWithDefaults() *TrailMapStaticElementOneOf {
	this := TrailMapStaticElementOneOf{}
	return &this
}

// GetType returns the Type field value
func (o *TrailMapStaticElementOneOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TrailMapStaticElementOneOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TrailMapStaticElementOneOf) SetType(v string) {
	o.Type = v
}

// GetUuid returns the Uuid field value
func (o *TrailMapStaticElementOneOf) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *TrailMapStaticElementOneOf) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *TrailMapStaticElementOneOf) SetUuid(v string) {
	o.Uuid = v
}

// GetPoints returns the Points field value
func (o *TrailMapStaticElementOneOf) GetPoints() []float64 {
	if o == nil {
		var ret []float64
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *TrailMapStaticElementOneOf) GetPointsOk() ([]float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Points, true
}

// SetPoints sets field value
func (o *TrailMapStaticElementOneOf) SetPoints(v []float64) {
	o.Points = v
}

// GetTension returns the Tension field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapStaticElementOneOf) GetTension() float64 {
	if o == nil || IsNil(o.Tension.Get()) {
		var ret float64
		return ret
	}
	return *o.Tension.Get()
}

// GetTensionOk returns a tuple with the Tension field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapStaticElementOneOf) GetTensionOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tension.Get(), o.Tension.IsSet()
}

// HasTension returns a boolean if a field has been set.
func (o *TrailMapStaticElementOneOf) HasTension() bool {
	if o != nil && o.Tension.IsSet() {
		return true
	}

	return false
}

// SetTension gets a reference to the given NullableFloat64 and assigns it to the Tension field.
func (o *TrailMapStaticElementOneOf) SetTension(v float64) {
	o.Tension.Set(&v)
}
// SetTensionNil sets the value for Tension to be an explicit nil
func (o *TrailMapStaticElementOneOf) SetTensionNil() {
	o.Tension.Set(nil)
}

// UnsetTension ensures that no value is present for Tension, not even an explicit nil
func (o *TrailMapStaticElementOneOf) UnsetTension() {
	o.Tension.Unset()
}

// GetLiftUuid returns the LiftUuid field value
func (o *TrailMapStaticElementOneOf) GetLiftUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LiftUuid
}

// GetLiftUuidOk returns a tuple with the LiftUuid field value
// and a boolean to check if the value has been set.
func (o *TrailMapStaticElementOneOf) GetLiftUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LiftUuid, true
}

// SetLiftUuid sets field value
func (o *TrailMapStaticElementOneOf) SetLiftUuid(v string) {
	o.LiftUuid = v
}

func (o TrailMapStaticElementOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrailMapStaticElementOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["uuid"] = o.Uuid
	toSerialize["points"] = o.Points
	if o.Tension.IsSet() {
		toSerialize["tension"] = o.Tension.Get()
	}
	toSerialize["lift_uuid"] = o.LiftUuid
	return toSerialize, nil
}

func (o *TrailMapStaticElementOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"uuid",
		"points",
		"lift_uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrailMapStaticElementOneOf := _TrailMapStaticElementOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrailMapStaticElementOneOf)

	if err != nil {
		return err
	}

	*o = TrailMapStaticElementOneOf(varTrailMapStaticElementOneOf)

	return err
}

type NullableTrailMapStaticElementOneOf struct {
	value *TrailMapStaticElementOneOf
	isSet bool
}

func (v NullableTrailMapStaticElementOneOf) Get() *TrailMapStaticElementOneOf {
	return v.value
}

func (v *NullableTrailMapStaticElementOneOf) Set(val *TrailMapStaticElementOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTrailMapStaticElementOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTrailMapStaticElementOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrailMapStaticElementOneOf(val *TrailMapStaticElementOneOf) *NullableTrailMapStaticElementOneOf {
	return &NullableTrailMapStaticElementOneOf{value: val, isSet: true}
}

func (v NullableTrailMapStaticElementOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrailMapStaticElementOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


