/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MobileAppResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MobileAppResponse{}

// MobileAppResponse Aggregated mobile-app data for the resort. New mobile-app surface area is  added as additional fields on this response.
type MobileAppResponse struct {
	// Banners shown in the mobile app, in display order.
	Banners []MobileAppBanner `json:"banners"`
}

type _MobileAppResponse MobileAppResponse

// NewMobileAppResponse instantiates a new MobileAppResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMobileAppResponse(banners []MobileAppBanner) *MobileAppResponse {
	this := MobileAppResponse{}
	this.Banners = banners
	return &this
}

// NewMobileAppResponseWithDefaults instantiates a new MobileAppResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMobileAppResponseWithDefaults() *MobileAppResponse {
	this := MobileAppResponse{}
	return &this
}

// GetBanners returns the Banners field value
func (o *MobileAppResponse) GetBanners() []MobileAppBanner {
	if o == nil {
		var ret []MobileAppBanner
		return ret
	}

	return o.Banners
}

// GetBannersOk returns a tuple with the Banners field value
// and a boolean to check if the value has been set.
func (o *MobileAppResponse) GetBannersOk() ([]MobileAppBanner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Banners, true
}

// SetBanners sets field value
func (o *MobileAppResponse) SetBanners(v []MobileAppBanner) {
	o.Banners = v
}

func (o MobileAppResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MobileAppResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["banners"] = o.Banners
	return toSerialize, nil
}

func (o *MobileAppResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"banners",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMobileAppResponse := _MobileAppResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMobileAppResponse)

	if err != nil {
		return err
	}

	*o = MobileAppResponse(varMobileAppResponse)

	return err
}

type NullableMobileAppResponse struct {
	value *MobileAppResponse
	isSet bool
}

func (v NullableMobileAppResponse) Get() *MobileAppResponse {
	return v.value
}

func (v *NullableMobileAppResponse) Set(val *MobileAppResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMobileAppResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMobileAppResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMobileAppResponse(val *MobileAppResponse) *NullableMobileAppResponse {
	return &NullableMobileAppResponse{value: val, isSet: true}
}

func (v NullableMobileAppResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMobileAppResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


