/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
)

// checks if the WebcamHistoryQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebcamHistoryQuery{}

// WebcamHistoryQuery Query parameters for the history endpoint.
type WebcamHistoryQuery struct {
	// Inclusive lower bound on `captured_at` (RFC 3339).
	From NullableString `json:"from,omitempty"`
	// Inclusive upper bound on `captured_at` (RFC 3339).
	To NullableString `json:"to,omitempty"`
}

// NewWebcamHistoryQuery instantiates a new WebcamHistoryQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebcamHistoryQuery() *WebcamHistoryQuery {
	this := WebcamHistoryQuery{}
	return &this
}

// NewWebcamHistoryQueryWithDefaults instantiates a new WebcamHistoryQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebcamHistoryQueryWithDefaults() *WebcamHistoryQuery {
	this := WebcamHistoryQuery{}
	return &this
}

// GetFrom returns the From field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebcamHistoryQuery) GetFrom() string {
	if o == nil || IsNil(o.From.Get()) {
		var ret string
		return ret
	}
	return *o.From.Get()
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebcamHistoryQuery) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.From.Get(), o.From.IsSet()
}

// HasFrom returns a boolean if a field has been set.
func (o *WebcamHistoryQuery) HasFrom() bool {
	if o != nil && o.From.IsSet() {
		return true
	}

	return false
}

// SetFrom gets a reference to the given NullableString and assigns it to the From field.
func (o *WebcamHistoryQuery) SetFrom(v string) {
	o.From.Set(&v)
}
// SetFromNil sets the value for From to be an explicit nil
func (o *WebcamHistoryQuery) SetFromNil() {
	o.From.Set(nil)
}

// UnsetFrom ensures that no value is present for From, not even an explicit nil
func (o *WebcamHistoryQuery) UnsetFrom() {
	o.From.Unset()
}

// GetTo returns the To field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebcamHistoryQuery) GetTo() string {
	if o == nil || IsNil(o.To.Get()) {
		var ret string
		return ret
	}
	return *o.To.Get()
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebcamHistoryQuery) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.To.Get(), o.To.IsSet()
}

// HasTo returns a boolean if a field has been set.
func (o *WebcamHistoryQuery) HasTo() bool {
	if o != nil && o.To.IsSet() {
		return true
	}

	return false
}

// SetTo gets a reference to the given NullableString and assigns it to the To field.
func (o *WebcamHistoryQuery) SetTo(v string) {
	o.To.Set(&v)
}
// SetToNil sets the value for To to be an explicit nil
func (o *WebcamHistoryQuery) SetToNil() {
	o.To.Set(nil)
}

// UnsetTo ensures that no value is present for To, not even an explicit nil
func (o *WebcamHistoryQuery) UnsetTo() {
	o.To.Unset()
}

func (o WebcamHistoryQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebcamHistoryQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.From.IsSet() {
		toSerialize["from"] = o.From.Get()
	}
	if o.To.IsSet() {
		toSerialize["to"] = o.To.Get()
	}
	return toSerialize, nil
}

type NullableWebcamHistoryQuery struct {
	value *WebcamHistoryQuery
	isSet bool
}

func (v NullableWebcamHistoryQuery) Get() *WebcamHistoryQuery {
	return v.value
}

func (v *NullableWebcamHistoryQuery) Set(val *WebcamHistoryQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableWebcamHistoryQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableWebcamHistoryQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebcamHistoryQuery(val *WebcamHistoryQuery) *NullableWebcamHistoryQuery {
	return &NullableWebcamHistoryQuery{value: val, isSet: true}
}

func (v NullableWebcamHistoryQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebcamHistoryQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


