/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// ParkingLotStatus Operational status of a parking lot.
type ParkingLotStatus string

// List of ParkingLotStatus
const (
	OPEN ParkingLotStatus = "open"
	CLOSED ParkingLotStatus = "closed"
	FULL ParkingLotStatus = "full"
)

// All allowed values of ParkingLotStatus enum
var AllowedParkingLotStatusEnumValues = []ParkingLotStatus{
	"open",
	"closed",
	"full",
}

func (v *ParkingLotStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ParkingLotStatus(value)
	for _, existing := range AllowedParkingLotStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ParkingLotStatus", value)
}

// NewParkingLotStatusFromValue returns a pointer to a valid ParkingLotStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewParkingLotStatusFromValue(v string) (*ParkingLotStatus, error) {
	ev := ParkingLotStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ParkingLotStatus: valid values are %v", v, AllowedParkingLotStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ParkingLotStatus) IsValid() bool {
	for _, existing := range AllowedParkingLotStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ParkingLotStatus value
func (v ParkingLotStatus) Ptr() *ParkingLotStatus {
	return &v
}

type NullableParkingLotStatus struct {
	value *ParkingLotStatus
	isSet bool
}

func (v NullableParkingLotStatus) Get() *ParkingLotStatus {
	return v.value
}

func (v *NullableParkingLotStatus) Set(val *ParkingLotStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableParkingLotStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableParkingLotStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParkingLotStatus(val *ParkingLotStatus) *NullableParkingLotStatus {
	return &NullableParkingLotStatus{value: val, isSet: true}
}

func (v NullableParkingLotStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParkingLotStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

