/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// WeatherConditionCode Weather condition code
type WeatherConditionCode string

// List of WeatherConditionCode
const (
	CLEAR WeatherConditionCode = "Clear"
	MOSTLY_CLEAR WeatherConditionCode = "MostlyClear"
	PARTLY_CLOUDY WeatherConditionCode = "PartlyCloudy"
	MOSTLY_CLOUDY WeatherConditionCode = "MostlyCloudy"
	CLOUDY WeatherConditionCode = "Cloudy"
	DUST WeatherConditionCode = "Dust"
	FOG WeatherConditionCode = "Fog"
	HAZE WeatherConditionCode = "Haze"
	SMOKE WeatherConditionCode = "Smoke"
	BREEZY WeatherConditionCode = "Breezy"
	WINDY WeatherConditionCode = "Windy"
	DRIZZLE WeatherConditionCode = "Drizzle"
	RAIN WeatherConditionCode = "Rain"
	SHOWERS WeatherConditionCode = "Showers"
	SCATTERED_SHOWERS WeatherConditionCode = "ScatteredShowers"
	HEAVY_RAIN WeatherConditionCode = "HeavyRain"
	FLURRIES WeatherConditionCode = "Flurries"
	SNOW WeatherConditionCode = "Snow"
	SNOW_SHOWERS WeatherConditionCode = "SnowShowers"
	SCATTERED_SNOW_SHOWERS WeatherConditionCode = "ScatteredSnowShowers"
	HEAVY_SNOW WeatherConditionCode = "HeavySnow"
	BLIZZARD WeatherConditionCode = "Blizzard"
	BLOWING_SNOW WeatherConditionCode = "BlowingSnow"
	MIXED_RAIN_AND_SLEET WeatherConditionCode = "MixedRainAndSleet"
	MIXED_RAIN_AND_SNOW WeatherConditionCode = "MixedRainAndSnow"
	MIXED_RAINFALL WeatherConditionCode = "MixedRainfall"
	MIXED_SNOW_AND_SLEET WeatherConditionCode = "MixedSnowAndSleet"
	SLEET WeatherConditionCode = "Sleet"
	FREEZING_DRIZZLE WeatherConditionCode = "FreezingDrizzle"
	FREEZING_RAIN WeatherConditionCode = "FreezingRain"
	FRIGID WeatherConditionCode = "Frigid"
	HAIL WeatherConditionCode = "Hail"
	SCATTERED_THUNDERSTORMS WeatherConditionCode = "ScatteredThunderstorms"
	ISOLATED_THUNDERSTORMS WeatherConditionCode = "IsolatedThunderstorms"
	THUNDERSTORM WeatherConditionCode = "Thunderstorm"
	SEVERE_THUNDERSTORM WeatherConditionCode = "SevereThunderstorm"
	HURRICANE WeatherConditionCode = "Hurricane"
	TORNADO WeatherConditionCode = "Tornado"
	TROPICAL_STORM WeatherConditionCode = "TropicalStorm"
	HOT WeatherConditionCode = "Hot"
	UNKNOWN WeatherConditionCode = "Unknown"
)

// All allowed values of WeatherConditionCode enum
var AllowedWeatherConditionCodeEnumValues = []WeatherConditionCode{
	"Clear",
	"MostlyClear",
	"PartlyCloudy",
	"MostlyCloudy",
	"Cloudy",
	"Dust",
	"Fog",
	"Haze",
	"Smoke",
	"Breezy",
	"Windy",
	"Drizzle",
	"Rain",
	"Showers",
	"ScatteredShowers",
	"HeavyRain",
	"Flurries",
	"Snow",
	"SnowShowers",
	"ScatteredSnowShowers",
	"HeavySnow",
	"Blizzard",
	"BlowingSnow",
	"MixedRainAndSleet",
	"MixedRainAndSnow",
	"MixedRainfall",
	"MixedSnowAndSleet",
	"Sleet",
	"FreezingDrizzle",
	"FreezingRain",
	"Frigid",
	"Hail",
	"ScatteredThunderstorms",
	"IsolatedThunderstorms",
	"Thunderstorm",
	"SevereThunderstorm",
	"Hurricane",
	"Tornado",
	"TropicalStorm",
	"Hot",
	"Unknown",
}

func (v *WeatherConditionCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WeatherConditionCode(value)
	for _, existing := range AllowedWeatherConditionCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid WeatherConditionCode", value)
}

// NewWeatherConditionCodeFromValue returns a pointer to a valid WeatherConditionCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWeatherConditionCodeFromValue(v string) (*WeatherConditionCode, error) {
	ev := WeatherConditionCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WeatherConditionCode: valid values are %v", v, AllowedWeatherConditionCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WeatherConditionCode) IsValid() bool {
	for _, existing := range AllowedWeatherConditionCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to WeatherConditionCode value
func (v WeatherConditionCode) Ptr() *WeatherConditionCode {
	return &v
}

type NullableWeatherConditionCode struct {
	value *WeatherConditionCode
	isSet bool
}

func (v NullableWeatherConditionCode) Get() *WeatherConditionCode {
	return v.value
}

func (v *NullableWeatherConditionCode) Set(val *WeatherConditionCode) {
	v.value = val
	v.isSet = true
}

func (v NullableWeatherConditionCode) IsSet() bool {
	return v.isSet
}

func (v *NullableWeatherConditionCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWeatherConditionCode(val *WeatherConditionCode) *NullableWeatherConditionCode {
	return &NullableWeatherConditionCode{value: val, isSet: true}
}

func (v NullableWeatherConditionCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWeatherConditionCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

