/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PathUuid type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PathUuid{}

// PathUuid struct for PathUuid
type PathUuid struct {
	// Resource UUID
	Uuid string `json:"uuid"`
}

type _PathUuid PathUuid

// NewPathUuid instantiates a new PathUuid object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPathUuid(uuid string) *PathUuid {
	this := PathUuid{}
	this.Uuid = uuid
	return &this
}

// NewPathUuidWithDefaults instantiates a new PathUuid object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPathUuidWithDefaults() *PathUuid {
	this := PathUuid{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *PathUuid) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *PathUuid) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *PathUuid) SetUuid(v string) {
	o.Uuid = v
}

func (o PathUuid) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PathUuid) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *PathUuid) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPathUuid := _PathUuid{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPathUuid)

	if err != nil {
		return err
	}

	*o = PathUuid(varPathUuid)

	return err
}

type NullablePathUuid struct {
	value *PathUuid
	isSet bool
}

func (v NullablePathUuid) Get() *PathUuid {
	return v.value
}

func (v *NullablePathUuid) Set(val *PathUuid) {
	v.value = val
	v.isSet = true
}

func (v NullablePathUuid) IsSet() bool {
	return v.isSet
}

func (v *NullablePathUuid) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePathUuid(val *PathUuid) *NullablePathUuid {
	return &NullablePathUuid{value: val, isSet: true}
}

func (v NullablePathUuid) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePathUuid) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


