/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrailMapElementOneOf5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrailMapElementOneOf5{}

// TrailMapElementOneOf5 struct for TrailMapElementOneOf5
type TrailMapElementOneOf5 struct {
	Type string `json:"type"`
	Uuid string `json:"uuid"`
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Icon NullableMarkerIcon `json:"icon,omitempty"`
	Color NullableString `json:"color,omitempty"`
	ParkingLot NullableParkingLot `json:"parking_lot,omitempty"`
	GroupLabel NullableString `json:"group_label,omitempty"`
}

type _TrailMapElementOneOf5 TrailMapElementOneOf5

// NewTrailMapElementOneOf5 instantiates a new TrailMapElementOneOf5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrailMapElementOneOf5(type_ string, uuid string, x float64, y float64) *TrailMapElementOneOf5 {
	this := TrailMapElementOneOf5{}
	this.Type = type_
	this.Uuid = uuid
	this.X = x
	this.Y = y
	return &this
}

// NewTrailMapElementOneOf5WithDefaults instantiates a new TrailMapElementOneOf5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrailMapElementOneOf5WithDefaults() *TrailMapElementOneOf5 {
	this := TrailMapElementOneOf5{}
	return &this
}

// GetType returns the Type field value
func (o *TrailMapElementOneOf5) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf5) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TrailMapElementOneOf5) SetType(v string) {
	o.Type = v
}

// GetUuid returns the Uuid field value
func (o *TrailMapElementOneOf5) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf5) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *TrailMapElementOneOf5) SetUuid(v string) {
	o.Uuid = v
}

// GetX returns the X field value
func (o *TrailMapElementOneOf5) GetX() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf5) GetXOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *TrailMapElementOneOf5) SetX(v float64) {
	o.X = v
}

// GetY returns the Y field value
func (o *TrailMapElementOneOf5) GetY() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf5) GetYOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *TrailMapElementOneOf5) SetY(v float64) {
	o.Y = v
}

// GetIcon returns the Icon field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf5) GetIcon() MarkerIcon {
	if o == nil || IsNil(o.Icon.Get()) {
		var ret MarkerIcon
		return ret
	}
	return *o.Icon.Get()
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf5) GetIconOk() (*MarkerIcon, bool) {
	if o == nil {
		return nil, false
	}
	return o.Icon.Get(), o.Icon.IsSet()
}

// HasIcon returns a boolean if a field has been set.
func (o *TrailMapElementOneOf5) HasIcon() bool {
	if o != nil && o.Icon.IsSet() {
		return true
	}

	return false
}

// SetIcon gets a reference to the given NullableMarkerIcon and assigns it to the Icon field.
func (o *TrailMapElementOneOf5) SetIcon(v MarkerIcon) {
	o.Icon.Set(&v)
}
// SetIconNil sets the value for Icon to be an explicit nil
func (o *TrailMapElementOneOf5) SetIconNil() {
	o.Icon.Set(nil)
}

// UnsetIcon ensures that no value is present for Icon, not even an explicit nil
func (o *TrailMapElementOneOf5) UnsetIcon() {
	o.Icon.Unset()
}

// GetColor returns the Color field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf5) GetColor() string {
	if o == nil || IsNil(o.Color.Get()) {
		var ret string
		return ret
	}
	return *o.Color.Get()
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf5) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Color.Get(), o.Color.IsSet()
}

// HasColor returns a boolean if a field has been set.
func (o *TrailMapElementOneOf5) HasColor() bool {
	if o != nil && o.Color.IsSet() {
		return true
	}

	return false
}

// SetColor gets a reference to the given NullableString and assigns it to the Color field.
func (o *TrailMapElementOneOf5) SetColor(v string) {
	o.Color.Set(&v)
}
// SetColorNil sets the value for Color to be an explicit nil
func (o *TrailMapElementOneOf5) SetColorNil() {
	o.Color.Set(nil)
}

// UnsetColor ensures that no value is present for Color, not even an explicit nil
func (o *TrailMapElementOneOf5) UnsetColor() {
	o.Color.Unset()
}

// GetParkingLot returns the ParkingLot field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf5) GetParkingLot() ParkingLot {
	if o == nil || IsNil(o.ParkingLot.Get()) {
		var ret ParkingLot
		return ret
	}
	return *o.ParkingLot.Get()
}

// GetParkingLotOk returns a tuple with the ParkingLot field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf5) GetParkingLotOk() (*ParkingLot, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParkingLot.Get(), o.ParkingLot.IsSet()
}

// HasParkingLot returns a boolean if a field has been set.
func (o *TrailMapElementOneOf5) HasParkingLot() bool {
	if o != nil && o.ParkingLot.IsSet() {
		return true
	}

	return false
}

// SetParkingLot gets a reference to the given NullableParkingLot and assigns it to the ParkingLot field.
func (o *TrailMapElementOneOf5) SetParkingLot(v ParkingLot) {
	o.ParkingLot.Set(&v)
}
// SetParkingLotNil sets the value for ParkingLot to be an explicit nil
func (o *TrailMapElementOneOf5) SetParkingLotNil() {
	o.ParkingLot.Set(nil)
}

// UnsetParkingLot ensures that no value is present for ParkingLot, not even an explicit nil
func (o *TrailMapElementOneOf5) UnsetParkingLot() {
	o.ParkingLot.Unset()
}

// GetGroupLabel returns the GroupLabel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf5) GetGroupLabel() string {
	if o == nil || IsNil(o.GroupLabel.Get()) {
		var ret string
		return ret
	}
	return *o.GroupLabel.Get()
}

// GetGroupLabelOk returns a tuple with the GroupLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf5) GetGroupLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GroupLabel.Get(), o.GroupLabel.IsSet()
}

// HasGroupLabel returns a boolean if a field has been set.
func (o *TrailMapElementOneOf5) HasGroupLabel() bool {
	if o != nil && o.GroupLabel.IsSet() {
		return true
	}

	return false
}

// SetGroupLabel gets a reference to the given NullableString and assigns it to the GroupLabel field.
func (o *TrailMapElementOneOf5) SetGroupLabel(v string) {
	o.GroupLabel.Set(&v)
}
// SetGroupLabelNil sets the value for GroupLabel to be an explicit nil
func (o *TrailMapElementOneOf5) SetGroupLabelNil() {
	o.GroupLabel.Set(nil)
}

// UnsetGroupLabel ensures that no value is present for GroupLabel, not even an explicit nil
func (o *TrailMapElementOneOf5) UnsetGroupLabel() {
	o.GroupLabel.Unset()
}

func (o TrailMapElementOneOf5) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrailMapElementOneOf5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["uuid"] = o.Uuid
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y
	if o.Icon.IsSet() {
		toSerialize["icon"] = o.Icon.Get()
	}
	if o.Color.IsSet() {
		toSerialize["color"] = o.Color.Get()
	}
	if o.ParkingLot.IsSet() {
		toSerialize["parking_lot"] = o.ParkingLot.Get()
	}
	if o.GroupLabel.IsSet() {
		toSerialize["group_label"] = o.GroupLabel.Get()
	}
	return toSerialize, nil
}

func (o *TrailMapElementOneOf5) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"uuid",
		"x",
		"y",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrailMapElementOneOf5 := _TrailMapElementOneOf5{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrailMapElementOneOf5)

	if err != nil {
		return err
	}

	*o = TrailMapElementOneOf5(varTrailMapElementOneOf5)

	return err
}

type NullableTrailMapElementOneOf5 struct {
	value *TrailMapElementOneOf5
	isSet bool
}

func (v NullableTrailMapElementOneOf5) Get() *TrailMapElementOneOf5 {
	return v.value
}

func (v *NullableTrailMapElementOneOf5) Set(val *TrailMapElementOneOf5) {
	v.value = val
	v.isSet = true
}

func (v NullableTrailMapElementOneOf5) IsSet() bool {
	return v.isSet
}

func (v *NullableTrailMapElementOneOf5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrailMapElementOneOf5(val *TrailMapElementOneOf5) *NullableTrailMapElementOneOf5 {
	return &NullableTrailMapElementOneOf5{value: val, isSet: true}
}

func (v NullableTrailMapElementOneOf5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrailMapElementOneOf5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


