/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GeoBounds type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoBounds{}

// GeoBounds Lat/lng bounding box and centroid for a trail map's georeferenced area.
type GeoBounds struct {
	MinLat float64 `json:"min_lat"`
	MaxLat float64 `json:"max_lat"`
	MinLng float64 `json:"min_lng"`
	MaxLng float64 `json:"max_lng"`
	Center GeoPoint `json:"center"`
}

type _GeoBounds GeoBounds

// NewGeoBounds instantiates a new GeoBounds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoBounds(minLat float64, maxLat float64, minLng float64, maxLng float64, center GeoPoint) *GeoBounds {
	this := GeoBounds{}
	this.MinLat = minLat
	this.MaxLat = maxLat
	this.MinLng = minLng
	this.MaxLng = maxLng
	this.Center = center
	return &this
}

// NewGeoBoundsWithDefaults instantiates a new GeoBounds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoBoundsWithDefaults() *GeoBounds {
	this := GeoBounds{}
	return &this
}

// GetMinLat returns the MinLat field value
func (o *GeoBounds) GetMinLat() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MinLat
}

// GetMinLatOk returns a tuple with the MinLat field value
// and a boolean to check if the value has been set.
func (o *GeoBounds) GetMinLatOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinLat, true
}

// SetMinLat sets field value
func (o *GeoBounds) SetMinLat(v float64) {
	o.MinLat = v
}

// GetMaxLat returns the MaxLat field value
func (o *GeoBounds) GetMaxLat() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxLat
}

// GetMaxLatOk returns a tuple with the MaxLat field value
// and a boolean to check if the value has been set.
func (o *GeoBounds) GetMaxLatOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxLat, true
}

// SetMaxLat sets field value
func (o *GeoBounds) SetMaxLat(v float64) {
	o.MaxLat = v
}

// GetMinLng returns the MinLng field value
func (o *GeoBounds) GetMinLng() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MinLng
}

// GetMinLngOk returns a tuple with the MinLng field value
// and a boolean to check if the value has been set.
func (o *GeoBounds) GetMinLngOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinLng, true
}

// SetMinLng sets field value
func (o *GeoBounds) SetMinLng(v float64) {
	o.MinLng = v
}

// GetMaxLng returns the MaxLng field value
func (o *GeoBounds) GetMaxLng() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MaxLng
}

// GetMaxLngOk returns a tuple with the MaxLng field value
// and a boolean to check if the value has been set.
func (o *GeoBounds) GetMaxLngOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxLng, true
}

// SetMaxLng sets field value
func (o *GeoBounds) SetMaxLng(v float64) {
	o.MaxLng = v
}

// GetCenter returns the Center field value
func (o *GeoBounds) GetCenter() GeoPoint {
	if o == nil {
		var ret GeoPoint
		return ret
	}

	return o.Center
}

// GetCenterOk returns a tuple with the Center field value
// and a boolean to check if the value has been set.
func (o *GeoBounds) GetCenterOk() (*GeoPoint, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Center, true
}

// SetCenter sets field value
func (o *GeoBounds) SetCenter(v GeoPoint) {
	o.Center = v
}

func (o GeoBounds) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoBounds) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["min_lat"] = o.MinLat
	toSerialize["max_lat"] = o.MaxLat
	toSerialize["min_lng"] = o.MinLng
	toSerialize["max_lng"] = o.MaxLng
	toSerialize["center"] = o.Center
	return toSerialize, nil
}

func (o *GeoBounds) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"min_lat",
		"max_lat",
		"min_lng",
		"max_lng",
		"center",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGeoBounds := _GeoBounds{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGeoBounds)

	if err != nil {
		return err
	}

	*o = GeoBounds(varGeoBounds)

	return err
}

type NullableGeoBounds struct {
	value *GeoBounds
	isSet bool
}

func (v NullableGeoBounds) Get() *GeoBounds {
	return v.value
}

func (v *NullableGeoBounds) Set(val *GeoBounds) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoBounds) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoBounds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoBounds(val *GeoBounds) *NullableGeoBounds {
	return &NullableGeoBounds{value: val, isSet: true}
}

func (v NullableGeoBounds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoBounds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


