/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AmenityCalendarEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AmenityCalendarEntry{}

// AmenityCalendarEntry Amenity entry within a CalendarDay, showing per-amenity hours for a specific date.
type AmenityCalendarEntry struct {
	// Amenity UUID.
	Uuid string `json:"uuid"`
	// Amenity name.
	Name string `json:"name"`
	// Amenity category.
	Category AmenityCategory `json:"category"`
	// Opening time in 24-hour format (HH:MM), in resort's local timezone.  `null` if this amenity is closed on this day.
	OpensAt NullableString `json:"opens_at,omitempty"`
	// Closing time in 24-hour format (HH:MM), in resort's local timezone.  `null` if this amenity is closed on this day.
	ClosesAt NullableString `json:"closes_at,omitempty"`
}

type _AmenityCalendarEntry AmenityCalendarEntry

// NewAmenityCalendarEntry instantiates a new AmenityCalendarEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmenityCalendarEntry(uuid string, name string, category AmenityCategory) *AmenityCalendarEntry {
	this := AmenityCalendarEntry{}
	this.Uuid = uuid
	this.Name = name
	this.Category = category
	return &this
}

// NewAmenityCalendarEntryWithDefaults instantiates a new AmenityCalendarEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmenityCalendarEntryWithDefaults() *AmenityCalendarEntry {
	this := AmenityCalendarEntry{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *AmenityCalendarEntry) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *AmenityCalendarEntry) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *AmenityCalendarEntry) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *AmenityCalendarEntry) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AmenityCalendarEntry) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AmenityCalendarEntry) SetName(v string) {
	o.Name = v
}

// GetCategory returns the Category field value
func (o *AmenityCalendarEntry) GetCategory() AmenityCategory {
	if o == nil {
		var ret AmenityCategory
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *AmenityCalendarEntry) GetCategoryOk() (*AmenityCategory, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *AmenityCalendarEntry) SetCategory(v AmenityCategory) {
	o.Category = v
}

// GetOpensAt returns the OpensAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AmenityCalendarEntry) GetOpensAt() string {
	if o == nil || IsNil(o.OpensAt.Get()) {
		var ret string
		return ret
	}
	return *o.OpensAt.Get()
}

// GetOpensAtOk returns a tuple with the OpensAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AmenityCalendarEntry) GetOpensAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OpensAt.Get(), o.OpensAt.IsSet()
}

// HasOpensAt returns a boolean if a field has been set.
func (o *AmenityCalendarEntry) HasOpensAt() bool {
	if o != nil && o.OpensAt.IsSet() {
		return true
	}

	return false
}

// SetOpensAt gets a reference to the given NullableString and assigns it to the OpensAt field.
func (o *AmenityCalendarEntry) SetOpensAt(v string) {
	o.OpensAt.Set(&v)
}
// SetOpensAtNil sets the value for OpensAt to be an explicit nil
func (o *AmenityCalendarEntry) SetOpensAtNil() {
	o.OpensAt.Set(nil)
}

// UnsetOpensAt ensures that no value is present for OpensAt, not even an explicit nil
func (o *AmenityCalendarEntry) UnsetOpensAt() {
	o.OpensAt.Unset()
}

// GetClosesAt returns the ClosesAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AmenityCalendarEntry) GetClosesAt() string {
	if o == nil || IsNil(o.ClosesAt.Get()) {
		var ret string
		return ret
	}
	return *o.ClosesAt.Get()
}

// GetClosesAtOk returns a tuple with the ClosesAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AmenityCalendarEntry) GetClosesAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClosesAt.Get(), o.ClosesAt.IsSet()
}

// HasClosesAt returns a boolean if a field has been set.
func (o *AmenityCalendarEntry) HasClosesAt() bool {
	if o != nil && o.ClosesAt.IsSet() {
		return true
	}

	return false
}

// SetClosesAt gets a reference to the given NullableString and assigns it to the ClosesAt field.
func (o *AmenityCalendarEntry) SetClosesAt(v string) {
	o.ClosesAt.Set(&v)
}
// SetClosesAtNil sets the value for ClosesAt to be an explicit nil
func (o *AmenityCalendarEntry) SetClosesAtNil() {
	o.ClosesAt.Set(nil)
}

// UnsetClosesAt ensures that no value is present for ClosesAt, not even an explicit nil
func (o *AmenityCalendarEntry) UnsetClosesAt() {
	o.ClosesAt.Unset()
}

func (o AmenityCalendarEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AmenityCalendarEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["category"] = o.Category
	if o.OpensAt.IsSet() {
		toSerialize["opens_at"] = o.OpensAt.Get()
	}
	if o.ClosesAt.IsSet() {
		toSerialize["closes_at"] = o.ClosesAt.Get()
	}
	return toSerialize, nil
}

func (o *AmenityCalendarEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
		"category",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAmenityCalendarEntry := _AmenityCalendarEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAmenityCalendarEntry)

	if err != nil {
		return err
	}

	*o = AmenityCalendarEntry(varAmenityCalendarEntry)

	return err
}

type NullableAmenityCalendarEntry struct {
	value *AmenityCalendarEntry
	isSet bool
}

func (v NullableAmenityCalendarEntry) Get() *AmenityCalendarEntry {
	return v.value
}

func (v *NullableAmenityCalendarEntry) Set(val *AmenityCalendarEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableAmenityCalendarEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableAmenityCalendarEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmenityCalendarEntry(val *AmenityCalendarEntry) *NullableAmenityCalendarEntry {
	return &NullableAmenityCalendarEntry{value: val, isSet: true}
}

func (v NullableAmenityCalendarEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmenityCalendarEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


