/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HourlyForecastMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HourlyForecastMetric{}

// HourlyForecastMetric Hourly forecast measurements in metric units
type HourlyForecastMetric struct {
	// Temperature in Celsius
	Temperature int32 `json:"temperature"`
	// Feels like temperature in Celsius
	FeelsLike NullableInt32 `json:"feels_like,omitempty"`
	// Snowfall amount expected this hour in centimeters
	Snowfall NullableInt32 `json:"snowfall,omitempty"`
	// Precipitation amount expected this hour in millimeters
	Precipitation NullableInt32 `json:"precipitation,omitempty"`
	// Wind speed in km/h
	WindSpeed int32 `json:"wind_speed"`
	// Wind gust in km/h
	WindGust NullableInt32 `json:"wind_gust,omitempty"`
}

type _HourlyForecastMetric HourlyForecastMetric

// NewHourlyForecastMetric instantiates a new HourlyForecastMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHourlyForecastMetric(temperature int32, windSpeed int32) *HourlyForecastMetric {
	this := HourlyForecastMetric{}
	this.Temperature = temperature
	this.WindSpeed = windSpeed
	return &this
}

// NewHourlyForecastMetricWithDefaults instantiates a new HourlyForecastMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHourlyForecastMetricWithDefaults() *HourlyForecastMetric {
	this := HourlyForecastMetric{}
	return &this
}

// GetTemperature returns the Temperature field value
func (o *HourlyForecastMetric) GetTemperature() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Temperature
}

// GetTemperatureOk returns a tuple with the Temperature field value
// and a boolean to check if the value has been set.
func (o *HourlyForecastMetric) GetTemperatureOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Temperature, true
}

// SetTemperature sets field value
func (o *HourlyForecastMetric) SetTemperature(v int32) {
	o.Temperature = v
}

// GetFeelsLike returns the FeelsLike field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HourlyForecastMetric) GetFeelsLike() int32 {
	if o == nil || IsNil(o.FeelsLike.Get()) {
		var ret int32
		return ret
	}
	return *o.FeelsLike.Get()
}

// GetFeelsLikeOk returns a tuple with the FeelsLike field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HourlyForecastMetric) GetFeelsLikeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeelsLike.Get(), o.FeelsLike.IsSet()
}

// HasFeelsLike returns a boolean if a field has been set.
func (o *HourlyForecastMetric) HasFeelsLike() bool {
	if o != nil && o.FeelsLike.IsSet() {
		return true
	}

	return false
}

// SetFeelsLike gets a reference to the given NullableInt32 and assigns it to the FeelsLike field.
func (o *HourlyForecastMetric) SetFeelsLike(v int32) {
	o.FeelsLike.Set(&v)
}
// SetFeelsLikeNil sets the value for FeelsLike to be an explicit nil
func (o *HourlyForecastMetric) SetFeelsLikeNil() {
	o.FeelsLike.Set(nil)
}

// UnsetFeelsLike ensures that no value is present for FeelsLike, not even an explicit nil
func (o *HourlyForecastMetric) UnsetFeelsLike() {
	o.FeelsLike.Unset()
}

// GetSnowfall returns the Snowfall field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HourlyForecastMetric) GetSnowfall() int32 {
	if o == nil || IsNil(o.Snowfall.Get()) {
		var ret int32
		return ret
	}
	return *o.Snowfall.Get()
}

// GetSnowfallOk returns a tuple with the Snowfall field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HourlyForecastMetric) GetSnowfallOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Snowfall.Get(), o.Snowfall.IsSet()
}

// HasSnowfall returns a boolean if a field has been set.
func (o *HourlyForecastMetric) HasSnowfall() bool {
	if o != nil && o.Snowfall.IsSet() {
		return true
	}

	return false
}

// SetSnowfall gets a reference to the given NullableInt32 and assigns it to the Snowfall field.
func (o *HourlyForecastMetric) SetSnowfall(v int32) {
	o.Snowfall.Set(&v)
}
// SetSnowfallNil sets the value for Snowfall to be an explicit nil
func (o *HourlyForecastMetric) SetSnowfallNil() {
	o.Snowfall.Set(nil)
}

// UnsetSnowfall ensures that no value is present for Snowfall, not even an explicit nil
func (o *HourlyForecastMetric) UnsetSnowfall() {
	o.Snowfall.Unset()
}

// GetPrecipitation returns the Precipitation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HourlyForecastMetric) GetPrecipitation() int32 {
	if o == nil || IsNil(o.Precipitation.Get()) {
		var ret int32
		return ret
	}
	return *o.Precipitation.Get()
}

// GetPrecipitationOk returns a tuple with the Precipitation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HourlyForecastMetric) GetPrecipitationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Precipitation.Get(), o.Precipitation.IsSet()
}

// HasPrecipitation returns a boolean if a field has been set.
func (o *HourlyForecastMetric) HasPrecipitation() bool {
	if o != nil && o.Precipitation.IsSet() {
		return true
	}

	return false
}

// SetPrecipitation gets a reference to the given NullableInt32 and assigns it to the Precipitation field.
func (o *HourlyForecastMetric) SetPrecipitation(v int32) {
	o.Precipitation.Set(&v)
}
// SetPrecipitationNil sets the value for Precipitation to be an explicit nil
func (o *HourlyForecastMetric) SetPrecipitationNil() {
	o.Precipitation.Set(nil)
}

// UnsetPrecipitation ensures that no value is present for Precipitation, not even an explicit nil
func (o *HourlyForecastMetric) UnsetPrecipitation() {
	o.Precipitation.Unset()
}

// GetWindSpeed returns the WindSpeed field value
func (o *HourlyForecastMetric) GetWindSpeed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WindSpeed
}

// GetWindSpeedOk returns a tuple with the WindSpeed field value
// and a boolean to check if the value has been set.
func (o *HourlyForecastMetric) GetWindSpeedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WindSpeed, true
}

// SetWindSpeed sets field value
func (o *HourlyForecastMetric) SetWindSpeed(v int32) {
	o.WindSpeed = v
}

// GetWindGust returns the WindGust field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HourlyForecastMetric) GetWindGust() int32 {
	if o == nil || IsNil(o.WindGust.Get()) {
		var ret int32
		return ret
	}
	return *o.WindGust.Get()
}

// GetWindGustOk returns a tuple with the WindGust field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HourlyForecastMetric) GetWindGustOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WindGust.Get(), o.WindGust.IsSet()
}

// HasWindGust returns a boolean if a field has been set.
func (o *HourlyForecastMetric) HasWindGust() bool {
	if o != nil && o.WindGust.IsSet() {
		return true
	}

	return false
}

// SetWindGust gets a reference to the given NullableInt32 and assigns it to the WindGust field.
func (o *HourlyForecastMetric) SetWindGust(v int32) {
	o.WindGust.Set(&v)
}
// SetWindGustNil sets the value for WindGust to be an explicit nil
func (o *HourlyForecastMetric) SetWindGustNil() {
	o.WindGust.Set(nil)
}

// UnsetWindGust ensures that no value is present for WindGust, not even an explicit nil
func (o *HourlyForecastMetric) UnsetWindGust() {
	o.WindGust.Unset()
}

func (o HourlyForecastMetric) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HourlyForecastMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["temperature"] = o.Temperature
	if o.FeelsLike.IsSet() {
		toSerialize["feels_like"] = o.FeelsLike.Get()
	}
	if o.Snowfall.IsSet() {
		toSerialize["snowfall"] = o.Snowfall.Get()
	}
	if o.Precipitation.IsSet() {
		toSerialize["precipitation"] = o.Precipitation.Get()
	}
	toSerialize["wind_speed"] = o.WindSpeed
	if o.WindGust.IsSet() {
		toSerialize["wind_gust"] = o.WindGust.Get()
	}
	return toSerialize, nil
}

func (o *HourlyForecastMetric) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"temperature",
		"wind_speed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHourlyForecastMetric := _HourlyForecastMetric{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHourlyForecastMetric)

	if err != nil {
		return err
	}

	*o = HourlyForecastMetric(varHourlyForecastMetric)

	return err
}

type NullableHourlyForecastMetric struct {
	value *HourlyForecastMetric
	isSet bool
}

func (v NullableHourlyForecastMetric) Get() *HourlyForecastMetric {
	return v.value
}

func (v *NullableHourlyForecastMetric) Set(val *HourlyForecastMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableHourlyForecastMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableHourlyForecastMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHourlyForecastMetric(val *HourlyForecastMetric) *NullableHourlyForecastMetric {
	return &NullableHourlyForecastMetric{value: val, isSet: true}
}

func (v NullableHourlyForecastMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHourlyForecastMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


