/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebcamHistoryFrame type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebcamHistoryFrame{}

// WebcamHistoryFrame A single archived historical frame.
type WebcamHistoryFrame struct {
	CapturedAt string `json:"captured_at"`
	ImageUrl string `json:"image_url"`
	ThumbUrl string `json:"thumb_url"`
}

type _WebcamHistoryFrame WebcamHistoryFrame

// NewWebcamHistoryFrame instantiates a new WebcamHistoryFrame object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebcamHistoryFrame(capturedAt string, imageUrl string, thumbUrl string) *WebcamHistoryFrame {
	this := WebcamHistoryFrame{}
	this.CapturedAt = capturedAt
	this.ImageUrl = imageUrl
	this.ThumbUrl = thumbUrl
	return &this
}

// NewWebcamHistoryFrameWithDefaults instantiates a new WebcamHistoryFrame object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebcamHistoryFrameWithDefaults() *WebcamHistoryFrame {
	this := WebcamHistoryFrame{}
	return &this
}

// GetCapturedAt returns the CapturedAt field value
func (o *WebcamHistoryFrame) GetCapturedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CapturedAt
}

// GetCapturedAtOk returns a tuple with the CapturedAt field value
// and a boolean to check if the value has been set.
func (o *WebcamHistoryFrame) GetCapturedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapturedAt, true
}

// SetCapturedAt sets field value
func (o *WebcamHistoryFrame) SetCapturedAt(v string) {
	o.CapturedAt = v
}

// GetImageUrl returns the ImageUrl field value
func (o *WebcamHistoryFrame) GetImageUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value
// and a boolean to check if the value has been set.
func (o *WebcamHistoryFrame) GetImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageUrl, true
}

// SetImageUrl sets field value
func (o *WebcamHistoryFrame) SetImageUrl(v string) {
	o.ImageUrl = v
}

// GetThumbUrl returns the ThumbUrl field value
func (o *WebcamHistoryFrame) GetThumbUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ThumbUrl
}

// GetThumbUrlOk returns a tuple with the ThumbUrl field value
// and a boolean to check if the value has been set.
func (o *WebcamHistoryFrame) GetThumbUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThumbUrl, true
}

// SetThumbUrl sets field value
func (o *WebcamHistoryFrame) SetThumbUrl(v string) {
	o.ThumbUrl = v
}

func (o WebcamHistoryFrame) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebcamHistoryFrame) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["captured_at"] = o.CapturedAt
	toSerialize["image_url"] = o.ImageUrl
	toSerialize["thumb_url"] = o.ThumbUrl
	return toSerialize, nil
}

func (o *WebcamHistoryFrame) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"captured_at",
		"image_url",
		"thumb_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebcamHistoryFrame := _WebcamHistoryFrame{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebcamHistoryFrame)

	if err != nil {
		return err
	}

	*o = WebcamHistoryFrame(varWebcamHistoryFrame)

	return err
}

type NullableWebcamHistoryFrame struct {
	value *WebcamHistoryFrame
	isSet bool
}

func (v NullableWebcamHistoryFrame) Get() *WebcamHistoryFrame {
	return v.value
}

func (v *NullableWebcamHistoryFrame) Set(val *WebcamHistoryFrame) {
	v.value = val
	v.isSet = true
}

func (v NullableWebcamHistoryFrame) IsSet() bool {
	return v.isSet
}

func (v *NullableWebcamHistoryFrame) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebcamHistoryFrame(val *WebcamHistoryFrame) *NullableWebcamHistoryFrame {
	return &NullableWebcamHistoryFrame{value: val, isSet: true}
}

func (v NullableWebcamHistoryFrame) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebcamHistoryFrame) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


