/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Run type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Run{}

// Run Represents a single run at the resort with its current status,  grooming information, and difficulty rating.
type Run struct {
	// Unique identifier for the run.
	Uuid string `json:"uuid"`
	// Display name of the run.
	Name string `json:"name"`
	// URL-friendly name of the run.
	Slug string `json:"slug"`
	// Optional run number.
	Number NullableInt32 `json:"number,omitempty"`
	// Difficulty rating of the run.
	Difficulty RunDifficulty `json:"difficulty"`
	// Current operational status (open, closed, or unknown).
	Status RunStatus `json:"status"`
	// When the run was last groomed.  `null` if never groomed, or if the runs grooming feature is disabled.
	LastGroomed NullableTime `json:"last_groomed,omitempty"`
	// Whether the run was groomed within the last 24 hours.
	GroomedToday bool `json:"groomed_today"`
	// Whether the run has snowmaking capabilities.
	Snowmaking bool `json:"snowmaking"`
	// Whether the run is available for night skiing.
	NightSkiing bool `json:"night_skiing"`
	// Notes about current conditions on this run.
	ConditionNotes string `json:"condition_notes"`
	// UUID of the area this run belongs to, if assigned.
	AreaUuid NullableString `json:"area_uuid,omitempty"`
	// Name of the area this run belongs to, if assigned.
	AreaName NullableString `json:"area_name,omitempty"`
	// Display order of the area this run belongs to, if assigned, for sorting purposes.
	AreaDisplayOrder NullableInt32 `json:"area_display_order,omitempty"`
	// When this run's information was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

type _Run Run

// NewRun instantiates a new Run object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRun(uuid string, name string, slug string, difficulty RunDifficulty, status RunStatus, groomedToday bool, snowmaking bool, nightSkiing bool, conditionNotes string, updatedAt time.Time) *Run {
	this := Run{}
	this.Uuid = uuid
	this.Name = name
	this.Slug = slug
	this.Difficulty = difficulty
	this.Status = status
	this.GroomedToday = groomedToday
	this.Snowmaking = snowmaking
	this.NightSkiing = nightSkiing
	this.ConditionNotes = conditionNotes
	this.UpdatedAt = updatedAt
	return &this
}

// NewRunWithDefaults instantiates a new Run object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunWithDefaults() *Run {
	this := Run{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *Run) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *Run) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *Run) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *Run) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Run) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Run) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *Run) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *Run) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *Run) SetSlug(v string) {
	o.Slug = v
}

// GetNumber returns the Number field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Run) GetNumber() int32 {
	if o == nil || IsNil(o.Number.Get()) {
		var ret int32
		return ret
	}
	return *o.Number.Get()
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Run) GetNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Number.Get(), o.Number.IsSet()
}

// HasNumber returns a boolean if a field has been set.
func (o *Run) HasNumber() bool {
	if o != nil && o.Number.IsSet() {
		return true
	}

	return false
}

// SetNumber gets a reference to the given NullableInt32 and assigns it to the Number field.
func (o *Run) SetNumber(v int32) {
	o.Number.Set(&v)
}
// SetNumberNil sets the value for Number to be an explicit nil
func (o *Run) SetNumberNil() {
	o.Number.Set(nil)
}

// UnsetNumber ensures that no value is present for Number, not even an explicit nil
func (o *Run) UnsetNumber() {
	o.Number.Unset()
}

// GetDifficulty returns the Difficulty field value
func (o *Run) GetDifficulty() RunDifficulty {
	if o == nil {
		var ret RunDifficulty
		return ret
	}

	return o.Difficulty
}

// GetDifficultyOk returns a tuple with the Difficulty field value
// and a boolean to check if the value has been set.
func (o *Run) GetDifficultyOk() (*RunDifficulty, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Difficulty, true
}

// SetDifficulty sets field value
func (o *Run) SetDifficulty(v RunDifficulty) {
	o.Difficulty = v
}

// GetStatus returns the Status field value
func (o *Run) GetStatus() RunStatus {
	if o == nil {
		var ret RunStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Run) GetStatusOk() (*RunStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Run) SetStatus(v RunStatus) {
	o.Status = v
}

// GetLastGroomed returns the LastGroomed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Run) GetLastGroomed() time.Time {
	if o == nil || IsNil(o.LastGroomed.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastGroomed.Get()
}

// GetLastGroomedOk returns a tuple with the LastGroomed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Run) GetLastGroomedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastGroomed.Get(), o.LastGroomed.IsSet()
}

// HasLastGroomed returns a boolean if a field has been set.
func (o *Run) HasLastGroomed() bool {
	if o != nil && o.LastGroomed.IsSet() {
		return true
	}

	return false
}

// SetLastGroomed gets a reference to the given NullableTime and assigns it to the LastGroomed field.
func (o *Run) SetLastGroomed(v time.Time) {
	o.LastGroomed.Set(&v)
}
// SetLastGroomedNil sets the value for LastGroomed to be an explicit nil
func (o *Run) SetLastGroomedNil() {
	o.LastGroomed.Set(nil)
}

// UnsetLastGroomed ensures that no value is present for LastGroomed, not even an explicit nil
func (o *Run) UnsetLastGroomed() {
	o.LastGroomed.Unset()
}

// GetGroomedToday returns the GroomedToday field value
func (o *Run) GetGroomedToday() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.GroomedToday
}

// GetGroomedTodayOk returns a tuple with the GroomedToday field value
// and a boolean to check if the value has been set.
func (o *Run) GetGroomedTodayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroomedToday, true
}

// SetGroomedToday sets field value
func (o *Run) SetGroomedToday(v bool) {
	o.GroomedToday = v
}

// GetSnowmaking returns the Snowmaking field value
func (o *Run) GetSnowmaking() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Snowmaking
}

// GetSnowmakingOk returns a tuple with the Snowmaking field value
// and a boolean to check if the value has been set.
func (o *Run) GetSnowmakingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Snowmaking, true
}

// SetSnowmaking sets field value
func (o *Run) SetSnowmaking(v bool) {
	o.Snowmaking = v
}

// GetNightSkiing returns the NightSkiing field value
func (o *Run) GetNightSkiing() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.NightSkiing
}

// GetNightSkiingOk returns a tuple with the NightSkiing field value
// and a boolean to check if the value has been set.
func (o *Run) GetNightSkiingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NightSkiing, true
}

// SetNightSkiing sets field value
func (o *Run) SetNightSkiing(v bool) {
	o.NightSkiing = v
}

// GetConditionNotes returns the ConditionNotes field value
func (o *Run) GetConditionNotes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConditionNotes
}

// GetConditionNotesOk returns a tuple with the ConditionNotes field value
// and a boolean to check if the value has been set.
func (o *Run) GetConditionNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionNotes, true
}

// SetConditionNotes sets field value
func (o *Run) SetConditionNotes(v string) {
	o.ConditionNotes = v
}

// GetAreaUuid returns the AreaUuid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Run) GetAreaUuid() string {
	if o == nil || IsNil(o.AreaUuid.Get()) {
		var ret string
		return ret
	}
	return *o.AreaUuid.Get()
}

// GetAreaUuidOk returns a tuple with the AreaUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Run) GetAreaUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaUuid.Get(), o.AreaUuid.IsSet()
}

// HasAreaUuid returns a boolean if a field has been set.
func (o *Run) HasAreaUuid() bool {
	if o != nil && o.AreaUuid.IsSet() {
		return true
	}

	return false
}

// SetAreaUuid gets a reference to the given NullableString and assigns it to the AreaUuid field.
func (o *Run) SetAreaUuid(v string) {
	o.AreaUuid.Set(&v)
}
// SetAreaUuidNil sets the value for AreaUuid to be an explicit nil
func (o *Run) SetAreaUuidNil() {
	o.AreaUuid.Set(nil)
}

// UnsetAreaUuid ensures that no value is present for AreaUuid, not even an explicit nil
func (o *Run) UnsetAreaUuid() {
	o.AreaUuid.Unset()
}

// GetAreaName returns the AreaName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Run) GetAreaName() string {
	if o == nil || IsNil(o.AreaName.Get()) {
		var ret string
		return ret
	}
	return *o.AreaName.Get()
}

// GetAreaNameOk returns a tuple with the AreaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Run) GetAreaNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaName.Get(), o.AreaName.IsSet()
}

// HasAreaName returns a boolean if a field has been set.
func (o *Run) HasAreaName() bool {
	if o != nil && o.AreaName.IsSet() {
		return true
	}

	return false
}

// SetAreaName gets a reference to the given NullableString and assigns it to the AreaName field.
func (o *Run) SetAreaName(v string) {
	o.AreaName.Set(&v)
}
// SetAreaNameNil sets the value for AreaName to be an explicit nil
func (o *Run) SetAreaNameNil() {
	o.AreaName.Set(nil)
}

// UnsetAreaName ensures that no value is present for AreaName, not even an explicit nil
func (o *Run) UnsetAreaName() {
	o.AreaName.Unset()
}

// GetAreaDisplayOrder returns the AreaDisplayOrder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Run) GetAreaDisplayOrder() int32 {
	if o == nil || IsNil(o.AreaDisplayOrder.Get()) {
		var ret int32
		return ret
	}
	return *o.AreaDisplayOrder.Get()
}

// GetAreaDisplayOrderOk returns a tuple with the AreaDisplayOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Run) GetAreaDisplayOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaDisplayOrder.Get(), o.AreaDisplayOrder.IsSet()
}

// HasAreaDisplayOrder returns a boolean if a field has been set.
func (o *Run) HasAreaDisplayOrder() bool {
	if o != nil && o.AreaDisplayOrder.IsSet() {
		return true
	}

	return false
}

// SetAreaDisplayOrder gets a reference to the given NullableInt32 and assigns it to the AreaDisplayOrder field.
func (o *Run) SetAreaDisplayOrder(v int32) {
	o.AreaDisplayOrder.Set(&v)
}
// SetAreaDisplayOrderNil sets the value for AreaDisplayOrder to be an explicit nil
func (o *Run) SetAreaDisplayOrderNil() {
	o.AreaDisplayOrder.Set(nil)
}

// UnsetAreaDisplayOrder ensures that no value is present for AreaDisplayOrder, not even an explicit nil
func (o *Run) UnsetAreaDisplayOrder() {
	o.AreaDisplayOrder.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Run) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Run) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Run) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o Run) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Run) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	if o.Number.IsSet() {
		toSerialize["number"] = o.Number.Get()
	}
	toSerialize["difficulty"] = o.Difficulty
	toSerialize["status"] = o.Status
	if o.LastGroomed.IsSet() {
		toSerialize["last_groomed"] = o.LastGroomed.Get()
	}
	toSerialize["groomed_today"] = o.GroomedToday
	toSerialize["snowmaking"] = o.Snowmaking
	toSerialize["night_skiing"] = o.NightSkiing
	toSerialize["condition_notes"] = o.ConditionNotes
	if o.AreaUuid.IsSet() {
		toSerialize["area_uuid"] = o.AreaUuid.Get()
	}
	if o.AreaName.IsSet() {
		toSerialize["area_name"] = o.AreaName.Get()
	}
	if o.AreaDisplayOrder.IsSet() {
		toSerialize["area_display_order"] = o.AreaDisplayOrder.Get()
	}
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *Run) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
		"slug",
		"difficulty",
		"status",
		"groomed_today",
		"snowmaking",
		"night_skiing",
		"condition_notes",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRun := _Run{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRun)

	if err != nil {
		return err
	}

	*o = Run(varRun)

	return err
}

type NullableRun struct {
	value *Run
	isSet bool
}

func (v NullableRun) Get() *Run {
	return v.value
}

func (v *NullableRun) Set(val *Run) {
	v.value = val
	v.isSet = true
}

func (v NullableRun) IsSet() bool {
	return v.isSet
}

func (v *NullableRun) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRun(val *Run) *NullableRun {
	return &NullableRun{value: val, isSet: true}
}

func (v NullableRun) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRun) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


