/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// SummerTrailStatus Operational status of a summer trail.
type SummerTrailStatus string

// List of SummerTrailStatus
const (
	OPEN SummerTrailStatus = "open"
	CLOSED SummerTrailStatus = "closed"
	UNKNOWN SummerTrailStatus = "unknown"
)

// All allowed values of SummerTrailStatus enum
var AllowedSummerTrailStatusEnumValues = []SummerTrailStatus{
	"open",
	"closed",
	"unknown",
}

func (v *SummerTrailStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SummerTrailStatus(value)
	for _, existing := range AllowedSummerTrailStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SummerTrailStatus", value)
}

// NewSummerTrailStatusFromValue returns a pointer to a valid SummerTrailStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSummerTrailStatusFromValue(v string) (*SummerTrailStatus, error) {
	ev := SummerTrailStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SummerTrailStatus: valid values are %v", v, AllowedSummerTrailStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SummerTrailStatus) IsValid() bool {
	for _, existing := range AllowedSummerTrailStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SummerTrailStatus value
func (v SummerTrailStatus) Ptr() *SummerTrailStatus {
	return &v
}

type NullableSummerTrailStatus struct {
	value *SummerTrailStatus
	isSet bool
}

func (v NullableSummerTrailStatus) Get() *SummerTrailStatus {
	return v.value
}

func (v *NullableSummerTrailStatus) Set(val *SummerTrailStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSummerTrailStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSummerTrailStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummerTrailStatus(val *SummerTrailStatus) *NullableSummerTrailStatus {
	return &NullableSummerTrailStatus{value: val, isSet: true}
}

func (v NullableSummerTrailStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummerTrailStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

