/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// LiftStatus Operational status of a ski lift.
type LiftStatus string

// List of LiftStatus
const (
	OPEN LiftStatus = "open"
	CLOSED LiftStatus = "closed"
	ON_HOLD LiftStatus = "on_hold"
	UNKNOWN LiftStatus = "unknown"
)

// All allowed values of LiftStatus enum
var AllowedLiftStatusEnumValues = []LiftStatus{
	"open",
	"closed",
	"on_hold",
	"unknown",
}

func (v *LiftStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LiftStatus(value)
	for _, existing := range AllowedLiftStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LiftStatus", value)
}

// NewLiftStatusFromValue returns a pointer to a valid LiftStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLiftStatusFromValue(v string) (*LiftStatus, error) {
	ev := LiftStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LiftStatus: valid values are %v", v, AllowedLiftStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LiftStatus) IsValid() bool {
	for _, existing := range AllowedLiftStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LiftStatus value
func (v LiftStatus) Ptr() *LiftStatus {
	return &v
}

type NullableLiftStatus struct {
	value *LiftStatus
	isSet bool
}

func (v NullableLiftStatus) Get() *LiftStatus {
	return v.value
}

func (v *NullableLiftStatus) Set(val *LiftStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableLiftStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableLiftStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiftStatus(val *LiftStatus) *NullableLiftStatus {
	return &NullableLiftStatus{value: val, isSet: true}
}

func (v NullableLiftStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLiftStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

