/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CurrentWeatherMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurrentWeatherMetric{}

// CurrentWeatherMetric Current temperature and precipitation measurements in metric units
type CurrentWeatherMetric struct {
	// Temperature in Celsius
	Temperature int32 `json:"temperature"`
	// Feels like temperature in Celsius
	FeelsLike int32 `json:"feels_like"`
	// Snowfall in centimeters
	Snowfall NullableInt32 `json:"snowfall,omitempty"`
	// Precipitation in millimeters
	Precipitation NullableInt32 `json:"precipitation,omitempty"`
	// Wind speed in km/h
	WindSpeed int32 `json:"wind_speed"`
	// Wind gust in km/h
	WindGust NullableInt32 `json:"wind_gust,omitempty"`
}

type _CurrentWeatherMetric CurrentWeatherMetric

// NewCurrentWeatherMetric instantiates a new CurrentWeatherMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurrentWeatherMetric(temperature int32, feelsLike int32, windSpeed int32) *CurrentWeatherMetric {
	this := CurrentWeatherMetric{}
	this.Temperature = temperature
	this.FeelsLike = feelsLike
	this.WindSpeed = windSpeed
	return &this
}

// NewCurrentWeatherMetricWithDefaults instantiates a new CurrentWeatherMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurrentWeatherMetricWithDefaults() *CurrentWeatherMetric {
	this := CurrentWeatherMetric{}
	return &this
}

// GetTemperature returns the Temperature field value
func (o *CurrentWeatherMetric) GetTemperature() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Temperature
}

// GetTemperatureOk returns a tuple with the Temperature field value
// and a boolean to check if the value has been set.
func (o *CurrentWeatherMetric) GetTemperatureOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Temperature, true
}

// SetTemperature sets field value
func (o *CurrentWeatherMetric) SetTemperature(v int32) {
	o.Temperature = v
}

// GetFeelsLike returns the FeelsLike field value
func (o *CurrentWeatherMetric) GetFeelsLike() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FeelsLike
}

// GetFeelsLikeOk returns a tuple with the FeelsLike field value
// and a boolean to check if the value has been set.
func (o *CurrentWeatherMetric) GetFeelsLikeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeelsLike, true
}

// SetFeelsLike sets field value
func (o *CurrentWeatherMetric) SetFeelsLike(v int32) {
	o.FeelsLike = v
}

// GetSnowfall returns the Snowfall field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurrentWeatherMetric) GetSnowfall() int32 {
	if o == nil || IsNil(o.Snowfall.Get()) {
		var ret int32
		return ret
	}
	return *o.Snowfall.Get()
}

// GetSnowfallOk returns a tuple with the Snowfall field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurrentWeatherMetric) GetSnowfallOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Snowfall.Get(), o.Snowfall.IsSet()
}

// HasSnowfall returns a boolean if a field has been set.
func (o *CurrentWeatherMetric) HasSnowfall() bool {
	if o != nil && o.Snowfall.IsSet() {
		return true
	}

	return false
}

// SetSnowfall gets a reference to the given NullableInt32 and assigns it to the Snowfall field.
func (o *CurrentWeatherMetric) SetSnowfall(v int32) {
	o.Snowfall.Set(&v)
}
// SetSnowfallNil sets the value for Snowfall to be an explicit nil
func (o *CurrentWeatherMetric) SetSnowfallNil() {
	o.Snowfall.Set(nil)
}

// UnsetSnowfall ensures that no value is present for Snowfall, not even an explicit nil
func (o *CurrentWeatherMetric) UnsetSnowfall() {
	o.Snowfall.Unset()
}

// GetPrecipitation returns the Precipitation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurrentWeatherMetric) GetPrecipitation() int32 {
	if o == nil || IsNil(o.Precipitation.Get()) {
		var ret int32
		return ret
	}
	return *o.Precipitation.Get()
}

// GetPrecipitationOk returns a tuple with the Precipitation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurrentWeatherMetric) GetPrecipitationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Precipitation.Get(), o.Precipitation.IsSet()
}

// HasPrecipitation returns a boolean if a field has been set.
func (o *CurrentWeatherMetric) HasPrecipitation() bool {
	if o != nil && o.Precipitation.IsSet() {
		return true
	}

	return false
}

// SetPrecipitation gets a reference to the given NullableInt32 and assigns it to the Precipitation field.
func (o *CurrentWeatherMetric) SetPrecipitation(v int32) {
	o.Precipitation.Set(&v)
}
// SetPrecipitationNil sets the value for Precipitation to be an explicit nil
func (o *CurrentWeatherMetric) SetPrecipitationNil() {
	o.Precipitation.Set(nil)
}

// UnsetPrecipitation ensures that no value is present for Precipitation, not even an explicit nil
func (o *CurrentWeatherMetric) UnsetPrecipitation() {
	o.Precipitation.Unset()
}

// GetWindSpeed returns the WindSpeed field value
func (o *CurrentWeatherMetric) GetWindSpeed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WindSpeed
}

// GetWindSpeedOk returns a tuple with the WindSpeed field value
// and a boolean to check if the value has been set.
func (o *CurrentWeatherMetric) GetWindSpeedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WindSpeed, true
}

// SetWindSpeed sets field value
func (o *CurrentWeatherMetric) SetWindSpeed(v int32) {
	o.WindSpeed = v
}

// GetWindGust returns the WindGust field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurrentWeatherMetric) GetWindGust() int32 {
	if o == nil || IsNil(o.WindGust.Get()) {
		var ret int32
		return ret
	}
	return *o.WindGust.Get()
}

// GetWindGustOk returns a tuple with the WindGust field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurrentWeatherMetric) GetWindGustOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WindGust.Get(), o.WindGust.IsSet()
}

// HasWindGust returns a boolean if a field has been set.
func (o *CurrentWeatherMetric) HasWindGust() bool {
	if o != nil && o.WindGust.IsSet() {
		return true
	}

	return false
}

// SetWindGust gets a reference to the given NullableInt32 and assigns it to the WindGust field.
func (o *CurrentWeatherMetric) SetWindGust(v int32) {
	o.WindGust.Set(&v)
}
// SetWindGustNil sets the value for WindGust to be an explicit nil
func (o *CurrentWeatherMetric) SetWindGustNil() {
	o.WindGust.Set(nil)
}

// UnsetWindGust ensures that no value is present for WindGust, not even an explicit nil
func (o *CurrentWeatherMetric) UnsetWindGust() {
	o.WindGust.Unset()
}

func (o CurrentWeatherMetric) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurrentWeatherMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["temperature"] = o.Temperature
	toSerialize["feels_like"] = o.FeelsLike
	if o.Snowfall.IsSet() {
		toSerialize["snowfall"] = o.Snowfall.Get()
	}
	if o.Precipitation.IsSet() {
		toSerialize["precipitation"] = o.Precipitation.Get()
	}
	toSerialize["wind_speed"] = o.WindSpeed
	if o.WindGust.IsSet() {
		toSerialize["wind_gust"] = o.WindGust.Get()
	}
	return toSerialize, nil
}

func (o *CurrentWeatherMetric) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"temperature",
		"feels_like",
		"wind_speed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurrentWeatherMetric := _CurrentWeatherMetric{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCurrentWeatherMetric)

	if err != nil {
		return err
	}

	*o = CurrentWeatherMetric(varCurrentWeatherMetric)

	return err
}

type NullableCurrentWeatherMetric struct {
	value *CurrentWeatherMetric
	isSet bool
}

func (v NullableCurrentWeatherMetric) Get() *CurrentWeatherMetric {
	return v.value
}

func (v *NullableCurrentWeatherMetric) Set(val *CurrentWeatherMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableCurrentWeatherMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableCurrentWeatherMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurrentWeatherMetric(val *CurrentWeatherMetric) *NullableCurrentWeatherMetric {
	return &NullableCurrentWeatherMetric{value: val, isSet: true}
}

func (v NullableCurrentWeatherMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurrentWeatherMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


