/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the HourlyForecast type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HourlyForecast{}

// HourlyForecast Hourly weather forecast entry with both metric and imperial units
type HourlyForecast struct {
	// Forecast timestamp
	Timestamp time.Time `json:"timestamp"`
	// Measurements in imperial units
	Imperial HourlyForecastImperial `json:"imperial"`
	// Measurements in metric units
	Metric HourlyForecastMetric `json:"metric"`
	// Human-readable condition
	Condition string `json:"condition"`
	// Weather condition code
	ConditionCode WeatherConditionCode `json:"condition_code"`
	// Probability of precipitation (0-100%)
	PrecipitationProbability NullableInt32 `json:"precipitation_probability,omitempty"`
}

type _HourlyForecast HourlyForecast

// NewHourlyForecast instantiates a new HourlyForecast object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHourlyForecast(timestamp time.Time, imperial HourlyForecastImperial, metric HourlyForecastMetric, condition string, conditionCode WeatherConditionCode) *HourlyForecast {
	this := HourlyForecast{}
	this.Timestamp = timestamp
	this.Imperial = imperial
	this.Metric = metric
	this.Condition = condition
	this.ConditionCode = conditionCode
	return &this
}

// NewHourlyForecastWithDefaults instantiates a new HourlyForecast object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHourlyForecastWithDefaults() *HourlyForecast {
	this := HourlyForecast{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *HourlyForecast) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *HourlyForecast) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *HourlyForecast) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetImperial returns the Imperial field value
func (o *HourlyForecast) GetImperial() HourlyForecastImperial {
	if o == nil {
		var ret HourlyForecastImperial
		return ret
	}

	return o.Imperial
}

// GetImperialOk returns a tuple with the Imperial field value
// and a boolean to check if the value has been set.
func (o *HourlyForecast) GetImperialOk() (*HourlyForecastImperial, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Imperial, true
}

// SetImperial sets field value
func (o *HourlyForecast) SetImperial(v HourlyForecastImperial) {
	o.Imperial = v
}

// GetMetric returns the Metric field value
func (o *HourlyForecast) GetMetric() HourlyForecastMetric {
	if o == nil {
		var ret HourlyForecastMetric
		return ret
	}

	return o.Metric
}

// GetMetricOk returns a tuple with the Metric field value
// and a boolean to check if the value has been set.
func (o *HourlyForecast) GetMetricOk() (*HourlyForecastMetric, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metric, true
}

// SetMetric sets field value
func (o *HourlyForecast) SetMetric(v HourlyForecastMetric) {
	o.Metric = v
}

// GetCondition returns the Condition field value
func (o *HourlyForecast) GetCondition() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *HourlyForecast) GetConditionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Condition, true
}

// SetCondition sets field value
func (o *HourlyForecast) SetCondition(v string) {
	o.Condition = v
}

// GetConditionCode returns the ConditionCode field value
func (o *HourlyForecast) GetConditionCode() WeatherConditionCode {
	if o == nil {
		var ret WeatherConditionCode
		return ret
	}

	return o.ConditionCode
}

// GetConditionCodeOk returns a tuple with the ConditionCode field value
// and a boolean to check if the value has been set.
func (o *HourlyForecast) GetConditionCodeOk() (*WeatherConditionCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionCode, true
}

// SetConditionCode sets field value
func (o *HourlyForecast) SetConditionCode(v WeatherConditionCode) {
	o.ConditionCode = v
}

// GetPrecipitationProbability returns the PrecipitationProbability field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HourlyForecast) GetPrecipitationProbability() int32 {
	if o == nil || IsNil(o.PrecipitationProbability.Get()) {
		var ret int32
		return ret
	}
	return *o.PrecipitationProbability.Get()
}

// GetPrecipitationProbabilityOk returns a tuple with the PrecipitationProbability field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HourlyForecast) GetPrecipitationProbabilityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrecipitationProbability.Get(), o.PrecipitationProbability.IsSet()
}

// HasPrecipitationProbability returns a boolean if a field has been set.
func (o *HourlyForecast) HasPrecipitationProbability() bool {
	if o != nil && o.PrecipitationProbability.IsSet() {
		return true
	}

	return false
}

// SetPrecipitationProbability gets a reference to the given NullableInt32 and assigns it to the PrecipitationProbability field.
func (o *HourlyForecast) SetPrecipitationProbability(v int32) {
	o.PrecipitationProbability.Set(&v)
}
// SetPrecipitationProbabilityNil sets the value for PrecipitationProbability to be an explicit nil
func (o *HourlyForecast) SetPrecipitationProbabilityNil() {
	o.PrecipitationProbability.Set(nil)
}

// UnsetPrecipitationProbability ensures that no value is present for PrecipitationProbability, not even an explicit nil
func (o *HourlyForecast) UnsetPrecipitationProbability() {
	o.PrecipitationProbability.Unset()
}

func (o HourlyForecast) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HourlyForecast) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["imperial"] = o.Imperial
	toSerialize["metric"] = o.Metric
	toSerialize["condition"] = o.Condition
	toSerialize["condition_code"] = o.ConditionCode
	if o.PrecipitationProbability.IsSet() {
		toSerialize["precipitation_probability"] = o.PrecipitationProbability.Get()
	}
	return toSerialize, nil
}

func (o *HourlyForecast) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timestamp",
		"imperial",
		"metric",
		"condition",
		"condition_code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHourlyForecast := _HourlyForecast{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHourlyForecast)

	if err != nil {
		return err
	}

	*o = HourlyForecast(varHourlyForecast)

	return err
}

type NullableHourlyForecast struct {
	value *HourlyForecast
	isSet bool
}

func (v NullableHourlyForecast) Get() *HourlyForecast {
	return v.value
}

func (v *NullableHourlyForecast) Set(val *HourlyForecast) {
	v.value = val
	v.isSet = true
}

func (v NullableHourlyForecast) IsSet() bool {
	return v.isSet
}

func (v *NullableHourlyForecast) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHourlyForecast(val *HourlyForecast) *NullableHourlyForecast {
	return &NullableHourlyForecast{value: val, isSet: true}
}

func (v NullableHourlyForecast) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHourlyForecast) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


