/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// TrailMapElement - A trail map element with full entity data from existing public models.
type TrailMapElement struct {
	TrailMapElementOneOf *TrailMapElementOneOf
	TrailMapElementOneOf1 *TrailMapElementOneOf1
	TrailMapElementOneOf2 *TrailMapElementOneOf2
	TrailMapElementOneOf3 *TrailMapElementOneOf3
	TrailMapElementOneOf4 *TrailMapElementOneOf4
}

// TrailMapElementOneOfAsTrailMapElement is a convenience function that returns TrailMapElementOneOf wrapped in TrailMapElement
func TrailMapElementOneOfAsTrailMapElement(v *TrailMapElementOneOf) TrailMapElement {
	return TrailMapElement{
		TrailMapElementOneOf: v,
	}
}

// TrailMapElementOneOf1AsTrailMapElement is a convenience function that returns TrailMapElementOneOf1 wrapped in TrailMapElement
func TrailMapElementOneOf1AsTrailMapElement(v *TrailMapElementOneOf1) TrailMapElement {
	return TrailMapElement{
		TrailMapElementOneOf1: v,
	}
}

// TrailMapElementOneOf2AsTrailMapElement is a convenience function that returns TrailMapElementOneOf2 wrapped in TrailMapElement
func TrailMapElementOneOf2AsTrailMapElement(v *TrailMapElementOneOf2) TrailMapElement {
	return TrailMapElement{
		TrailMapElementOneOf2: v,
	}
}

// TrailMapElementOneOf3AsTrailMapElement is a convenience function that returns TrailMapElementOneOf3 wrapped in TrailMapElement
func TrailMapElementOneOf3AsTrailMapElement(v *TrailMapElementOneOf3) TrailMapElement {
	return TrailMapElement{
		TrailMapElementOneOf3: v,
	}
}

// TrailMapElementOneOf4AsTrailMapElement is a convenience function that returns TrailMapElementOneOf4 wrapped in TrailMapElement
func TrailMapElementOneOf4AsTrailMapElement(v *TrailMapElementOneOf4) TrailMapElement {
	return TrailMapElement{
		TrailMapElementOneOf4: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *TrailMapElement) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into TrailMapElementOneOf
	err = newStrictDecoder(data).Decode(&dst.TrailMapElementOneOf)
	if err == nil {
		jsonTrailMapElementOneOf, _ := json.Marshal(dst.TrailMapElementOneOf)
		if string(jsonTrailMapElementOneOf) == "{}" { // empty struct
			dst.TrailMapElementOneOf = nil
		} else {
			if err = validator.Validate(dst.TrailMapElementOneOf); err != nil {
				dst.TrailMapElementOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.TrailMapElementOneOf = nil
	}

	// try to unmarshal data into TrailMapElementOneOf1
	err = newStrictDecoder(data).Decode(&dst.TrailMapElementOneOf1)
	if err == nil {
		jsonTrailMapElementOneOf1, _ := json.Marshal(dst.TrailMapElementOneOf1)
		if string(jsonTrailMapElementOneOf1) == "{}" { // empty struct
			dst.TrailMapElementOneOf1 = nil
		} else {
			if err = validator.Validate(dst.TrailMapElementOneOf1); err != nil {
				dst.TrailMapElementOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.TrailMapElementOneOf1 = nil
	}

	// try to unmarshal data into TrailMapElementOneOf2
	err = newStrictDecoder(data).Decode(&dst.TrailMapElementOneOf2)
	if err == nil {
		jsonTrailMapElementOneOf2, _ := json.Marshal(dst.TrailMapElementOneOf2)
		if string(jsonTrailMapElementOneOf2) == "{}" { // empty struct
			dst.TrailMapElementOneOf2 = nil
		} else {
			if err = validator.Validate(dst.TrailMapElementOneOf2); err != nil {
				dst.TrailMapElementOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.TrailMapElementOneOf2 = nil
	}

	// try to unmarshal data into TrailMapElementOneOf3
	err = newStrictDecoder(data).Decode(&dst.TrailMapElementOneOf3)
	if err == nil {
		jsonTrailMapElementOneOf3, _ := json.Marshal(dst.TrailMapElementOneOf3)
		if string(jsonTrailMapElementOneOf3) == "{}" { // empty struct
			dst.TrailMapElementOneOf3 = nil
		} else {
			if err = validator.Validate(dst.TrailMapElementOneOf3); err != nil {
				dst.TrailMapElementOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.TrailMapElementOneOf3 = nil
	}

	// try to unmarshal data into TrailMapElementOneOf4
	err = newStrictDecoder(data).Decode(&dst.TrailMapElementOneOf4)
	if err == nil {
		jsonTrailMapElementOneOf4, _ := json.Marshal(dst.TrailMapElementOneOf4)
		if string(jsonTrailMapElementOneOf4) == "{}" { // empty struct
			dst.TrailMapElementOneOf4 = nil
		} else {
			if err = validator.Validate(dst.TrailMapElementOneOf4); err != nil {
				dst.TrailMapElementOneOf4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.TrailMapElementOneOf4 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.TrailMapElementOneOf = nil
		dst.TrailMapElementOneOf1 = nil
		dst.TrailMapElementOneOf2 = nil
		dst.TrailMapElementOneOf3 = nil
		dst.TrailMapElementOneOf4 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TrailMapElement)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TrailMapElement)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TrailMapElement) MarshalJSON() ([]byte, error) {
	if src.TrailMapElementOneOf != nil {
		return json.Marshal(&src.TrailMapElementOneOf)
	}

	if src.TrailMapElementOneOf1 != nil {
		return json.Marshal(&src.TrailMapElementOneOf1)
	}

	if src.TrailMapElementOneOf2 != nil {
		return json.Marshal(&src.TrailMapElementOneOf2)
	}

	if src.TrailMapElementOneOf3 != nil {
		return json.Marshal(&src.TrailMapElementOneOf3)
	}

	if src.TrailMapElementOneOf4 != nil {
		return json.Marshal(&src.TrailMapElementOneOf4)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TrailMapElement) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.TrailMapElementOneOf != nil {
		return obj.TrailMapElementOneOf
	}

	if obj.TrailMapElementOneOf1 != nil {
		return obj.TrailMapElementOneOf1
	}

	if obj.TrailMapElementOneOf2 != nil {
		return obj.TrailMapElementOneOf2
	}

	if obj.TrailMapElementOneOf3 != nil {
		return obj.TrailMapElementOneOf3
	}

	if obj.TrailMapElementOneOf4 != nil {
		return obj.TrailMapElementOneOf4
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj TrailMapElement) GetActualInstanceValue() (interface{}) {
	if obj.TrailMapElementOneOf != nil {
		return *obj.TrailMapElementOneOf
	}

	if obj.TrailMapElementOneOf1 != nil {
		return *obj.TrailMapElementOneOf1
	}

	if obj.TrailMapElementOneOf2 != nil {
		return *obj.TrailMapElementOneOf2
	}

	if obj.TrailMapElementOneOf3 != nil {
		return *obj.TrailMapElementOneOf3
	}

	if obj.TrailMapElementOneOf4 != nil {
		return *obj.TrailMapElementOneOf4
	}

	// all schemas are nil
	return nil
}

type NullableTrailMapElement struct {
	value *TrailMapElement
	isSet bool
}

func (v NullableTrailMapElement) Get() *TrailMapElement {
	return v.value
}

func (v *NullableTrailMapElement) Set(val *TrailMapElement) {
	v.value = val
	v.isSet = true
}

func (v NullableTrailMapElement) IsSet() bool {
	return v.isSet
}

func (v *NullableTrailMapElement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrailMapElement(val *TrailMapElement) *NullableTrailMapElement {
	return &NullableTrailMapElement{value: val, isSet: true}
}

func (v NullableTrailMapElement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrailMapElement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


