/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppConfig{}

// AppConfig App-level configuration bundled into the aggregated report.
type AppConfig struct {
	// The resort's hosted base URL — scheme + host with no path, e.g.  `https://powder-mountain.mtnmanager.net`, or the resort's own custom  domain when one is configured.
	HostedBaseUrl string `json:"hosted_base_url"`
	// Last time the static trail-map assets were re-published, ISO 8601 UTC.  Bumped when those assets change so clients can cache-bust.
	TrailMapAssetsUpdatedAt string `json:"trail_map_assets_updated_at"`
}

type _AppConfig AppConfig

// NewAppConfig instantiates a new AppConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppConfig(hostedBaseUrl string, trailMapAssetsUpdatedAt string) *AppConfig {
	this := AppConfig{}
	this.HostedBaseUrl = hostedBaseUrl
	this.TrailMapAssetsUpdatedAt = trailMapAssetsUpdatedAt
	return &this
}

// NewAppConfigWithDefaults instantiates a new AppConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppConfigWithDefaults() *AppConfig {
	this := AppConfig{}
	return &this
}

// GetHostedBaseUrl returns the HostedBaseUrl field value
func (o *AppConfig) GetHostedBaseUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HostedBaseUrl
}

// GetHostedBaseUrlOk returns a tuple with the HostedBaseUrl field value
// and a boolean to check if the value has been set.
func (o *AppConfig) GetHostedBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostedBaseUrl, true
}

// SetHostedBaseUrl sets field value
func (o *AppConfig) SetHostedBaseUrl(v string) {
	o.HostedBaseUrl = v
}

// GetTrailMapAssetsUpdatedAt returns the TrailMapAssetsUpdatedAt field value
func (o *AppConfig) GetTrailMapAssetsUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrailMapAssetsUpdatedAt
}

// GetTrailMapAssetsUpdatedAtOk returns a tuple with the TrailMapAssetsUpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AppConfig) GetTrailMapAssetsUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrailMapAssetsUpdatedAt, true
}

// SetTrailMapAssetsUpdatedAt sets field value
func (o *AppConfig) SetTrailMapAssetsUpdatedAt(v string) {
	o.TrailMapAssetsUpdatedAt = v
}

func (o AppConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hosted_base_url"] = o.HostedBaseUrl
	toSerialize["trail_map_assets_updated_at"] = o.TrailMapAssetsUpdatedAt
	return toSerialize, nil
}

func (o *AppConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hosted_base_url",
		"trail_map_assets_updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppConfig := _AppConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppConfig)

	if err != nil {
		return err
	}

	*o = AppConfig(varAppConfig)

	return err
}

type NullableAppConfig struct {
	value *AppConfig
	isSet bool
}

func (v NullableAppConfig) Get() *AppConfig {
	return v.value
}

func (v *NullableAppConfig) Set(val *AppConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableAppConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableAppConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppConfig(val *AppConfig) *NullableAppConfig {
	return &NullableAppConfig{value: val, isSet: true}
}

func (v NullableAppConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


