/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// SummerTrailDifficulty Difficulty rating for a summer trail.
type SummerTrailDifficulty string

// List of SummerTrailDifficulty
const (
	BEGINNER SummerTrailDifficulty = "beginner"
	INTERMEDIATE SummerTrailDifficulty = "intermediate"
	ADVANCED SummerTrailDifficulty = "advanced"
	EXPERT SummerTrailDifficulty = "expert"
)

// All allowed values of SummerTrailDifficulty enum
var AllowedSummerTrailDifficultyEnumValues = []SummerTrailDifficulty{
	"beginner",
	"intermediate",
	"advanced",
	"expert",
}

func (v *SummerTrailDifficulty) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SummerTrailDifficulty(value)
	for _, existing := range AllowedSummerTrailDifficultyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SummerTrailDifficulty", value)
}

// NewSummerTrailDifficultyFromValue returns a pointer to a valid SummerTrailDifficulty
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSummerTrailDifficultyFromValue(v string) (*SummerTrailDifficulty, error) {
	ev := SummerTrailDifficulty(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SummerTrailDifficulty: valid values are %v", v, AllowedSummerTrailDifficultyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SummerTrailDifficulty) IsValid() bool {
	for _, existing := range AllowedSummerTrailDifficultyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SummerTrailDifficulty value
func (v SummerTrailDifficulty) Ptr() *SummerTrailDifficulty {
	return &v
}

type NullableSummerTrailDifficulty struct {
	value *SummerTrailDifficulty
	isSet bool
}

func (v NullableSummerTrailDifficulty) Get() *SummerTrailDifficulty {
	return v.value
}

func (v *NullableSummerTrailDifficulty) Set(val *SummerTrailDifficulty) {
	v.value = val
	v.isSet = true
}

func (v NullableSummerTrailDifficulty) IsSet() bool {
	return v.isSet
}

func (v *NullableSummerTrailDifficulty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummerTrailDifficulty(val *SummerTrailDifficulty) *NullableSummerTrailDifficulty {
	return &NullableSummerTrailDifficulty{value: val, isSet: true}
}

func (v NullableSummerTrailDifficulty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummerTrailDifficulty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

