/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"fmt"
)

// LiftType Type of ski lift
type LiftType string

// List of LiftType
const (
	GONDOLA LiftType = "gondola"
	TRAM LiftType = "tram"
	EIGHT_PACK LiftType = "eight_pack"
	SIX_PACK LiftType = "six_pack"
	QUAD LiftType = "quad"
	TRIPLE LiftType = "triple"
	DOUBLE LiftType = "double"
	MAGIC_CARPET LiftType = "magic_carpet"
	T_BAR LiftType = "t_bar"
	PLATTER LiftType = "platter"
	ROPE_TOW LiftType = "rope_tow"
	FUNICULAR LiftType = "funicular"
	OTHER LiftType = "other"
)

// All allowed values of LiftType enum
var AllowedLiftTypeEnumValues = []LiftType{
	"gondola",
	"tram",
	"eight_pack",
	"six_pack",
	"quad",
	"triple",
	"double",
	"magic_carpet",
	"t_bar",
	"platter",
	"rope_tow",
	"funicular",
	"other",
}

func (v *LiftType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LiftType(value)
	for _, existing := range AllowedLiftTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LiftType", value)
}

// NewLiftTypeFromValue returns a pointer to a valid LiftType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLiftTypeFromValue(v string) (*LiftType, error) {
	ev := LiftType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LiftType: valid values are %v", v, AllowedLiftTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LiftType) IsValid() bool {
	for _, existing := range AllowedLiftTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LiftType value
func (v LiftType) Ptr() *LiftType {
	return &v
}

type NullableLiftType struct {
	value *LiftType
	isSet bool
}

func (v NullableLiftType) Get() *LiftType {
	return v.value
}

func (v *NullableLiftType) Set(val *LiftType) {
	v.value = val
	v.isSet = true
}

func (v NullableLiftType) IsSet() bool {
	return v.isSet
}

func (v *NullableLiftType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiftType(val *LiftType) *NullableLiftType {
	return &NullableLiftType{value: val, isSet: true}
}

func (v NullableLiftType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLiftType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

