/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GeoPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeoPoint{}

// GeoPoint A latitude/longitude point.
type GeoPoint struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type _GeoPoint GeoPoint

// NewGeoPoint instantiates a new GeoPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeoPoint(lat float64, lng float64) *GeoPoint {
	this := GeoPoint{}
	this.Lat = lat
	this.Lng = lng
	return &this
}

// NewGeoPointWithDefaults instantiates a new GeoPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeoPointWithDefaults() *GeoPoint {
	this := GeoPoint{}
	return &this
}

// GetLat returns the Lat field value
func (o *GeoPoint) GetLat() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Lat
}

// GetLatOk returns a tuple with the Lat field value
// and a boolean to check if the value has been set.
func (o *GeoPoint) GetLatOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lat, true
}

// SetLat sets field value
func (o *GeoPoint) SetLat(v float64) {
	o.Lat = v
}

// GetLng returns the Lng field value
func (o *GeoPoint) GetLng() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Lng
}

// GetLngOk returns a tuple with the Lng field value
// and a boolean to check if the value has been set.
func (o *GeoPoint) GetLngOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lng, true
}

// SetLng sets field value
func (o *GeoPoint) SetLng(v float64) {
	o.Lng = v
}

func (o GeoPoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeoPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lat"] = o.Lat
	toSerialize["lng"] = o.Lng
	return toSerialize, nil
}

func (o *GeoPoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lat",
		"lng",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGeoPoint := _GeoPoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGeoPoint)

	if err != nil {
		return err
	}

	*o = GeoPoint(varGeoPoint)

	return err
}

type NullableGeoPoint struct {
	value *GeoPoint
	isSet bool
}

func (v NullableGeoPoint) Get() *GeoPoint {
	return v.value
}

func (v *NullableGeoPoint) Set(val *GeoPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableGeoPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableGeoPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeoPoint(val *GeoPoint) *NullableGeoPoint {
	return &NullableGeoPoint{value: val, isSet: true}
}

func (v NullableGeoPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeoPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


