/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TerrainPark type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerrainPark{}

// TerrainPark Represents a terrain park at the resort with its current status,  condition notes, and list of features (jumps, boxes, rails, etc.) within it.
type TerrainPark struct {
	// Unique identifier for the terrain park.
	Uuid string `json:"uuid"`
	// Display name of the terrain park.
	Name string `json:"name"`
	// URL-friendly name of the terrain park.
	Slug string `json:"slug"`
	// Optional terrain park number.
	Number NullableInt32 `json:"number,omitempty"`
	// Current operational status (open, closed, or unknown).
	Status TerrainParkStatus `json:"status"`
	// Notes about current conditions in this terrain park.
	ConditionNotes string `json:"condition_notes"`
	// UUID of the area this terrain park belongs to, if assigned.
	AreaUuid NullableString `json:"area_uuid,omitempty"`
	// Name of the area this terrain park belongs to, if assigned.
	AreaName NullableString `json:"area_name,omitempty"`
	// Display order of the area this terrain park belongs to, if assigned, for sorting purposes.
	AreaDisplayOrder NullableInt32 `json:"area_display_order,omitempty"`
	// Features within this terrain park (jumps, boxes, rails, etc.).
	Features []TerrainParkFeature `json:"features"`
	// When this terrain park or any of its features was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

type _TerrainPark TerrainPark

// NewTerrainPark instantiates a new TerrainPark object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerrainPark(uuid string, name string, slug string, status TerrainParkStatus, conditionNotes string, features []TerrainParkFeature, updatedAt time.Time) *TerrainPark {
	this := TerrainPark{}
	this.Uuid = uuid
	this.Name = name
	this.Slug = slug
	this.Status = status
	this.ConditionNotes = conditionNotes
	this.Features = features
	this.UpdatedAt = updatedAt
	return &this
}

// NewTerrainParkWithDefaults instantiates a new TerrainPark object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerrainParkWithDefaults() *TerrainPark {
	this := TerrainPark{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *TerrainPark) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *TerrainPark) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *TerrainPark) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *TerrainPark) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TerrainPark) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TerrainPark) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *TerrainPark) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *TerrainPark) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *TerrainPark) SetSlug(v string) {
	o.Slug = v
}

// GetNumber returns the Number field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TerrainPark) GetNumber() int32 {
	if o == nil || IsNil(o.Number.Get()) {
		var ret int32
		return ret
	}
	return *o.Number.Get()
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TerrainPark) GetNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Number.Get(), o.Number.IsSet()
}

// HasNumber returns a boolean if a field has been set.
func (o *TerrainPark) HasNumber() bool {
	if o != nil && o.Number.IsSet() {
		return true
	}

	return false
}

// SetNumber gets a reference to the given NullableInt32 and assigns it to the Number field.
func (o *TerrainPark) SetNumber(v int32) {
	o.Number.Set(&v)
}
// SetNumberNil sets the value for Number to be an explicit nil
func (o *TerrainPark) SetNumberNil() {
	o.Number.Set(nil)
}

// UnsetNumber ensures that no value is present for Number, not even an explicit nil
func (o *TerrainPark) UnsetNumber() {
	o.Number.Unset()
}

// GetStatus returns the Status field value
func (o *TerrainPark) GetStatus() TerrainParkStatus {
	if o == nil {
		var ret TerrainParkStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TerrainPark) GetStatusOk() (*TerrainParkStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TerrainPark) SetStatus(v TerrainParkStatus) {
	o.Status = v
}

// GetConditionNotes returns the ConditionNotes field value
func (o *TerrainPark) GetConditionNotes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConditionNotes
}

// GetConditionNotesOk returns a tuple with the ConditionNotes field value
// and a boolean to check if the value has been set.
func (o *TerrainPark) GetConditionNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionNotes, true
}

// SetConditionNotes sets field value
func (o *TerrainPark) SetConditionNotes(v string) {
	o.ConditionNotes = v
}

// GetAreaUuid returns the AreaUuid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TerrainPark) GetAreaUuid() string {
	if o == nil || IsNil(o.AreaUuid.Get()) {
		var ret string
		return ret
	}
	return *o.AreaUuid.Get()
}

// GetAreaUuidOk returns a tuple with the AreaUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TerrainPark) GetAreaUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaUuid.Get(), o.AreaUuid.IsSet()
}

// HasAreaUuid returns a boolean if a field has been set.
func (o *TerrainPark) HasAreaUuid() bool {
	if o != nil && o.AreaUuid.IsSet() {
		return true
	}

	return false
}

// SetAreaUuid gets a reference to the given NullableString and assigns it to the AreaUuid field.
func (o *TerrainPark) SetAreaUuid(v string) {
	o.AreaUuid.Set(&v)
}
// SetAreaUuidNil sets the value for AreaUuid to be an explicit nil
func (o *TerrainPark) SetAreaUuidNil() {
	o.AreaUuid.Set(nil)
}

// UnsetAreaUuid ensures that no value is present for AreaUuid, not even an explicit nil
func (o *TerrainPark) UnsetAreaUuid() {
	o.AreaUuid.Unset()
}

// GetAreaName returns the AreaName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TerrainPark) GetAreaName() string {
	if o == nil || IsNil(o.AreaName.Get()) {
		var ret string
		return ret
	}
	return *o.AreaName.Get()
}

// GetAreaNameOk returns a tuple with the AreaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TerrainPark) GetAreaNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaName.Get(), o.AreaName.IsSet()
}

// HasAreaName returns a boolean if a field has been set.
func (o *TerrainPark) HasAreaName() bool {
	if o != nil && o.AreaName.IsSet() {
		return true
	}

	return false
}

// SetAreaName gets a reference to the given NullableString and assigns it to the AreaName field.
func (o *TerrainPark) SetAreaName(v string) {
	o.AreaName.Set(&v)
}
// SetAreaNameNil sets the value for AreaName to be an explicit nil
func (o *TerrainPark) SetAreaNameNil() {
	o.AreaName.Set(nil)
}

// UnsetAreaName ensures that no value is present for AreaName, not even an explicit nil
func (o *TerrainPark) UnsetAreaName() {
	o.AreaName.Unset()
}

// GetAreaDisplayOrder returns the AreaDisplayOrder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TerrainPark) GetAreaDisplayOrder() int32 {
	if o == nil || IsNil(o.AreaDisplayOrder.Get()) {
		var ret int32
		return ret
	}
	return *o.AreaDisplayOrder.Get()
}

// GetAreaDisplayOrderOk returns a tuple with the AreaDisplayOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TerrainPark) GetAreaDisplayOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaDisplayOrder.Get(), o.AreaDisplayOrder.IsSet()
}

// HasAreaDisplayOrder returns a boolean if a field has been set.
func (o *TerrainPark) HasAreaDisplayOrder() bool {
	if o != nil && o.AreaDisplayOrder.IsSet() {
		return true
	}

	return false
}

// SetAreaDisplayOrder gets a reference to the given NullableInt32 and assigns it to the AreaDisplayOrder field.
func (o *TerrainPark) SetAreaDisplayOrder(v int32) {
	o.AreaDisplayOrder.Set(&v)
}
// SetAreaDisplayOrderNil sets the value for AreaDisplayOrder to be an explicit nil
func (o *TerrainPark) SetAreaDisplayOrderNil() {
	o.AreaDisplayOrder.Set(nil)
}

// UnsetAreaDisplayOrder ensures that no value is present for AreaDisplayOrder, not even an explicit nil
func (o *TerrainPark) UnsetAreaDisplayOrder() {
	o.AreaDisplayOrder.Unset()
}

// GetFeatures returns the Features field value
func (o *TerrainPark) GetFeatures() []TerrainParkFeature {
	if o == nil {
		var ret []TerrainParkFeature
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *TerrainPark) GetFeaturesOk() ([]TerrainParkFeature, bool) {
	if o == nil {
		return nil, false
	}
	return o.Features, true
}

// SetFeatures sets field value
func (o *TerrainPark) SetFeatures(v []TerrainParkFeature) {
	o.Features = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *TerrainPark) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *TerrainPark) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *TerrainPark) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o TerrainPark) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerrainPark) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	if o.Number.IsSet() {
		toSerialize["number"] = o.Number.Get()
	}
	toSerialize["status"] = o.Status
	toSerialize["condition_notes"] = o.ConditionNotes
	if o.AreaUuid.IsSet() {
		toSerialize["area_uuid"] = o.AreaUuid.Get()
	}
	if o.AreaName.IsSet() {
		toSerialize["area_name"] = o.AreaName.Get()
	}
	if o.AreaDisplayOrder.IsSet() {
		toSerialize["area_display_order"] = o.AreaDisplayOrder.Get()
	}
	toSerialize["features"] = o.Features
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *TerrainPark) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
		"slug",
		"status",
		"condition_notes",
		"features",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTerrainPark := _TerrainPark{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTerrainPark)

	if err != nil {
		return err
	}

	*o = TerrainPark(varTerrainPark)

	return err
}

type NullableTerrainPark struct {
	value *TerrainPark
	isSet bool
}

func (v NullableTerrainPark) Get() *TerrainPark {
	return v.value
}

func (v *NullableTerrainPark) Set(val *TerrainPark) {
	v.value = val
	v.isSet = true
}

func (v NullableTerrainPark) IsSet() bool {
	return v.isSet
}

func (v *NullableTerrainPark) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerrainPark(val *TerrainPark) *NullableTerrainPark {
	return &NullableTerrainPark{value: val, isSet: true}
}

func (v NullableTerrainPark) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerrainPark) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


