/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Lift type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Lift{}

// Lift Represents a single lift at the resort with its current operational status,  type, and optional wait time information.
type Lift struct {
	// Unique identifier for the lift.
	Uuid string `json:"uuid"`
	// Display name of the lift.
	Name string `json:"name"`
	// URL-friendly name of the lift.
	Slug string `json:"slug"`
	// Optional lift number.
	Number NullableInt32 `json:"number,omitempty"`
	// Type of lift (e.g. gondola, quad).
	LiftType LiftType `json:"lift_type"`
	// Whether this is a high-speed/detachable lift.
	HighSpeed bool `json:"high_speed"`
	// Current operational status (open, closed, on_hold, or unknown).
	Status LiftStatus `json:"status"`
	// Current estimated wait time in minutes, if available.
	WaitTimeMinutes NullableInt64 `json:"wait_time_minutes,omitempty"`
	// UUID of the area this lift belongs to, if assigned.
	AreaUuid NullableString `json:"area_uuid,omitempty"`
	// Name of the area this lift belongs to, if assigned.
	AreaName NullableString `json:"area_name,omitempty"`
	// Display order of the area this lift belongs to, if assigned, for sorting purposes.
	AreaDisplayOrder NullableInt32 `json:"area_display_order,omitempty"`
	// When this lift's information was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

type _Lift Lift

// NewLift instantiates a new Lift object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLift(uuid string, name string, slug string, liftType LiftType, highSpeed bool, status LiftStatus, updatedAt time.Time) *Lift {
	this := Lift{}
	this.Uuid = uuid
	this.Name = name
	this.Slug = slug
	this.LiftType = liftType
	this.HighSpeed = highSpeed
	this.Status = status
	this.UpdatedAt = updatedAt
	return &this
}

// NewLiftWithDefaults instantiates a new Lift object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiftWithDefaults() *Lift {
	this := Lift{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *Lift) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *Lift) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *Lift) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *Lift) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Lift) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Lift) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *Lift) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *Lift) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *Lift) SetSlug(v string) {
	o.Slug = v
}

// GetNumber returns the Number field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Lift) GetNumber() int32 {
	if o == nil || IsNil(o.Number.Get()) {
		var ret int32
		return ret
	}
	return *o.Number.Get()
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Lift) GetNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Number.Get(), o.Number.IsSet()
}

// HasNumber returns a boolean if a field has been set.
func (o *Lift) HasNumber() bool {
	if o != nil && o.Number.IsSet() {
		return true
	}

	return false
}

// SetNumber gets a reference to the given NullableInt32 and assigns it to the Number field.
func (o *Lift) SetNumber(v int32) {
	o.Number.Set(&v)
}
// SetNumberNil sets the value for Number to be an explicit nil
func (o *Lift) SetNumberNil() {
	o.Number.Set(nil)
}

// UnsetNumber ensures that no value is present for Number, not even an explicit nil
func (o *Lift) UnsetNumber() {
	o.Number.Unset()
}

// GetLiftType returns the LiftType field value
func (o *Lift) GetLiftType() LiftType {
	if o == nil {
		var ret LiftType
		return ret
	}

	return o.LiftType
}

// GetLiftTypeOk returns a tuple with the LiftType field value
// and a boolean to check if the value has been set.
func (o *Lift) GetLiftTypeOk() (*LiftType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LiftType, true
}

// SetLiftType sets field value
func (o *Lift) SetLiftType(v LiftType) {
	o.LiftType = v
}

// GetHighSpeed returns the HighSpeed field value
func (o *Lift) GetHighSpeed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HighSpeed
}

// GetHighSpeedOk returns a tuple with the HighSpeed field value
// and a boolean to check if the value has been set.
func (o *Lift) GetHighSpeedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HighSpeed, true
}

// SetHighSpeed sets field value
func (o *Lift) SetHighSpeed(v bool) {
	o.HighSpeed = v
}

// GetStatus returns the Status field value
func (o *Lift) GetStatus() LiftStatus {
	if o == nil {
		var ret LiftStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Lift) GetStatusOk() (*LiftStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Lift) SetStatus(v LiftStatus) {
	o.Status = v
}

// GetWaitTimeMinutes returns the WaitTimeMinutes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Lift) GetWaitTimeMinutes() int64 {
	if o == nil || IsNil(o.WaitTimeMinutes.Get()) {
		var ret int64
		return ret
	}
	return *o.WaitTimeMinutes.Get()
}

// GetWaitTimeMinutesOk returns a tuple with the WaitTimeMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Lift) GetWaitTimeMinutesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.WaitTimeMinutes.Get(), o.WaitTimeMinutes.IsSet()
}

// HasWaitTimeMinutes returns a boolean if a field has been set.
func (o *Lift) HasWaitTimeMinutes() bool {
	if o != nil && o.WaitTimeMinutes.IsSet() {
		return true
	}

	return false
}

// SetWaitTimeMinutes gets a reference to the given NullableInt64 and assigns it to the WaitTimeMinutes field.
func (o *Lift) SetWaitTimeMinutes(v int64) {
	o.WaitTimeMinutes.Set(&v)
}
// SetWaitTimeMinutesNil sets the value for WaitTimeMinutes to be an explicit nil
func (o *Lift) SetWaitTimeMinutesNil() {
	o.WaitTimeMinutes.Set(nil)
}

// UnsetWaitTimeMinutes ensures that no value is present for WaitTimeMinutes, not even an explicit nil
func (o *Lift) UnsetWaitTimeMinutes() {
	o.WaitTimeMinutes.Unset()
}

// GetAreaUuid returns the AreaUuid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Lift) GetAreaUuid() string {
	if o == nil || IsNil(o.AreaUuid.Get()) {
		var ret string
		return ret
	}
	return *o.AreaUuid.Get()
}

// GetAreaUuidOk returns a tuple with the AreaUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Lift) GetAreaUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaUuid.Get(), o.AreaUuid.IsSet()
}

// HasAreaUuid returns a boolean if a field has been set.
func (o *Lift) HasAreaUuid() bool {
	if o != nil && o.AreaUuid.IsSet() {
		return true
	}

	return false
}

// SetAreaUuid gets a reference to the given NullableString and assigns it to the AreaUuid field.
func (o *Lift) SetAreaUuid(v string) {
	o.AreaUuid.Set(&v)
}
// SetAreaUuidNil sets the value for AreaUuid to be an explicit nil
func (o *Lift) SetAreaUuidNil() {
	o.AreaUuid.Set(nil)
}

// UnsetAreaUuid ensures that no value is present for AreaUuid, not even an explicit nil
func (o *Lift) UnsetAreaUuid() {
	o.AreaUuid.Unset()
}

// GetAreaName returns the AreaName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Lift) GetAreaName() string {
	if o == nil || IsNil(o.AreaName.Get()) {
		var ret string
		return ret
	}
	return *o.AreaName.Get()
}

// GetAreaNameOk returns a tuple with the AreaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Lift) GetAreaNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaName.Get(), o.AreaName.IsSet()
}

// HasAreaName returns a boolean if a field has been set.
func (o *Lift) HasAreaName() bool {
	if o != nil && o.AreaName.IsSet() {
		return true
	}

	return false
}

// SetAreaName gets a reference to the given NullableString and assigns it to the AreaName field.
func (o *Lift) SetAreaName(v string) {
	o.AreaName.Set(&v)
}
// SetAreaNameNil sets the value for AreaName to be an explicit nil
func (o *Lift) SetAreaNameNil() {
	o.AreaName.Set(nil)
}

// UnsetAreaName ensures that no value is present for AreaName, not even an explicit nil
func (o *Lift) UnsetAreaName() {
	o.AreaName.Unset()
}

// GetAreaDisplayOrder returns the AreaDisplayOrder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Lift) GetAreaDisplayOrder() int32 {
	if o == nil || IsNil(o.AreaDisplayOrder.Get()) {
		var ret int32
		return ret
	}
	return *o.AreaDisplayOrder.Get()
}

// GetAreaDisplayOrderOk returns a tuple with the AreaDisplayOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Lift) GetAreaDisplayOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaDisplayOrder.Get(), o.AreaDisplayOrder.IsSet()
}

// HasAreaDisplayOrder returns a boolean if a field has been set.
func (o *Lift) HasAreaDisplayOrder() bool {
	if o != nil && o.AreaDisplayOrder.IsSet() {
		return true
	}

	return false
}

// SetAreaDisplayOrder gets a reference to the given NullableInt32 and assigns it to the AreaDisplayOrder field.
func (o *Lift) SetAreaDisplayOrder(v int32) {
	o.AreaDisplayOrder.Set(&v)
}
// SetAreaDisplayOrderNil sets the value for AreaDisplayOrder to be an explicit nil
func (o *Lift) SetAreaDisplayOrderNil() {
	o.AreaDisplayOrder.Set(nil)
}

// UnsetAreaDisplayOrder ensures that no value is present for AreaDisplayOrder, not even an explicit nil
func (o *Lift) UnsetAreaDisplayOrder() {
	o.AreaDisplayOrder.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Lift) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Lift) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Lift) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o Lift) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Lift) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	if o.Number.IsSet() {
		toSerialize["number"] = o.Number.Get()
	}
	toSerialize["lift_type"] = o.LiftType
	toSerialize["high_speed"] = o.HighSpeed
	toSerialize["status"] = o.Status
	if o.WaitTimeMinutes.IsSet() {
		toSerialize["wait_time_minutes"] = o.WaitTimeMinutes.Get()
	}
	if o.AreaUuid.IsSet() {
		toSerialize["area_uuid"] = o.AreaUuid.Get()
	}
	if o.AreaName.IsSet() {
		toSerialize["area_name"] = o.AreaName.Get()
	}
	if o.AreaDisplayOrder.IsSet() {
		toSerialize["area_display_order"] = o.AreaDisplayOrder.Get()
	}
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *Lift) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
		"slug",
		"lift_type",
		"high_speed",
		"status",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLift := _Lift{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLift)

	if err != nil {
		return err
	}

	*o = Lift(varLift)

	return err
}

type NullableLift struct {
	value *Lift
	isSet bool
}

func (v NullableLift) Get() *Lift {
	return v.value
}

func (v *NullableLift) Set(val *Lift) {
	v.value = val
	v.isSet = true
}

func (v NullableLift) IsSet() bool {
	return v.isSet
}

func (v *NullableLift) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLift(val *Lift) *NullableLift {
	return &NullableLift{value: val, isSet: true}
}

func (v NullableLift) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLift) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


