/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrailMapElementOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrailMapElementOneOf2{}

// TrailMapElementOneOf2 struct for TrailMapElementOneOf2
type TrailMapElementOneOf2 struct {
	Type string `json:"type"`
	Uuid string `json:"uuid"`
	Points []float64 `json:"points"`
	Tension NullableFloat64 `json:"tension,omitempty"`
	LabelOffset NullableLabelOffset `json:"label_offset,omitempty"`
	TerrainPark NullableTerrainPark `json:"terrain_park,omitempty"`
}

type _TrailMapElementOneOf2 TrailMapElementOneOf2

// NewTrailMapElementOneOf2 instantiates a new TrailMapElementOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrailMapElementOneOf2(type_ string, uuid string, points []float64) *TrailMapElementOneOf2 {
	this := TrailMapElementOneOf2{}
	this.Type = type_
	this.Uuid = uuid
	this.Points = points
	return &this
}

// NewTrailMapElementOneOf2WithDefaults instantiates a new TrailMapElementOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrailMapElementOneOf2WithDefaults() *TrailMapElementOneOf2 {
	this := TrailMapElementOneOf2{}
	return &this
}

// GetType returns the Type field value
func (o *TrailMapElementOneOf2) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf2) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TrailMapElementOneOf2) SetType(v string) {
	o.Type = v
}

// GetUuid returns the Uuid field value
func (o *TrailMapElementOneOf2) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf2) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *TrailMapElementOneOf2) SetUuid(v string) {
	o.Uuid = v
}

// GetPoints returns the Points field value
func (o *TrailMapElementOneOf2) GetPoints() []float64 {
	if o == nil {
		var ret []float64
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *TrailMapElementOneOf2) GetPointsOk() ([]float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Points, true
}

// SetPoints sets field value
func (o *TrailMapElementOneOf2) SetPoints(v []float64) {
	o.Points = v
}

// GetTension returns the Tension field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf2) GetTension() float64 {
	if o == nil || IsNil(o.Tension.Get()) {
		var ret float64
		return ret
	}
	return *o.Tension.Get()
}

// GetTensionOk returns a tuple with the Tension field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf2) GetTensionOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tension.Get(), o.Tension.IsSet()
}

// HasTension returns a boolean if a field has been set.
func (o *TrailMapElementOneOf2) HasTension() bool {
	if o != nil && o.Tension.IsSet() {
		return true
	}

	return false
}

// SetTension gets a reference to the given NullableFloat64 and assigns it to the Tension field.
func (o *TrailMapElementOneOf2) SetTension(v float64) {
	o.Tension.Set(&v)
}
// SetTensionNil sets the value for Tension to be an explicit nil
func (o *TrailMapElementOneOf2) SetTensionNil() {
	o.Tension.Set(nil)
}

// UnsetTension ensures that no value is present for Tension, not even an explicit nil
func (o *TrailMapElementOneOf2) UnsetTension() {
	o.Tension.Unset()
}

// GetLabelOffset returns the LabelOffset field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf2) GetLabelOffset() LabelOffset {
	if o == nil || IsNil(o.LabelOffset.Get()) {
		var ret LabelOffset
		return ret
	}
	return *o.LabelOffset.Get()
}

// GetLabelOffsetOk returns a tuple with the LabelOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf2) GetLabelOffsetOk() (*LabelOffset, bool) {
	if o == nil {
		return nil, false
	}
	return o.LabelOffset.Get(), o.LabelOffset.IsSet()
}

// HasLabelOffset returns a boolean if a field has been set.
func (o *TrailMapElementOneOf2) HasLabelOffset() bool {
	if o != nil && o.LabelOffset.IsSet() {
		return true
	}

	return false
}

// SetLabelOffset gets a reference to the given NullableLabelOffset and assigns it to the LabelOffset field.
func (o *TrailMapElementOneOf2) SetLabelOffset(v LabelOffset) {
	o.LabelOffset.Set(&v)
}
// SetLabelOffsetNil sets the value for LabelOffset to be an explicit nil
func (o *TrailMapElementOneOf2) SetLabelOffsetNil() {
	o.LabelOffset.Set(nil)
}

// UnsetLabelOffset ensures that no value is present for LabelOffset, not even an explicit nil
func (o *TrailMapElementOneOf2) UnsetLabelOffset() {
	o.LabelOffset.Unset()
}

// GetTerrainPark returns the TerrainPark field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrailMapElementOneOf2) GetTerrainPark() TerrainPark {
	if o == nil || IsNil(o.TerrainPark.Get()) {
		var ret TerrainPark
		return ret
	}
	return *o.TerrainPark.Get()
}

// GetTerrainParkOk returns a tuple with the TerrainPark field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrailMapElementOneOf2) GetTerrainParkOk() (*TerrainPark, bool) {
	if o == nil {
		return nil, false
	}
	return o.TerrainPark.Get(), o.TerrainPark.IsSet()
}

// HasTerrainPark returns a boolean if a field has been set.
func (o *TrailMapElementOneOf2) HasTerrainPark() bool {
	if o != nil && o.TerrainPark.IsSet() {
		return true
	}

	return false
}

// SetTerrainPark gets a reference to the given NullableTerrainPark and assigns it to the TerrainPark field.
func (o *TrailMapElementOneOf2) SetTerrainPark(v TerrainPark) {
	o.TerrainPark.Set(&v)
}
// SetTerrainParkNil sets the value for TerrainPark to be an explicit nil
func (o *TrailMapElementOneOf2) SetTerrainParkNil() {
	o.TerrainPark.Set(nil)
}

// UnsetTerrainPark ensures that no value is present for TerrainPark, not even an explicit nil
func (o *TrailMapElementOneOf2) UnsetTerrainPark() {
	o.TerrainPark.Unset()
}

func (o TrailMapElementOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrailMapElementOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["uuid"] = o.Uuid
	toSerialize["points"] = o.Points
	if o.Tension.IsSet() {
		toSerialize["tension"] = o.Tension.Get()
	}
	if o.LabelOffset.IsSet() {
		toSerialize["label_offset"] = o.LabelOffset.Get()
	}
	if o.TerrainPark.IsSet() {
		toSerialize["terrain_park"] = o.TerrainPark.Get()
	}
	return toSerialize, nil
}

func (o *TrailMapElementOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"uuid",
		"points",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrailMapElementOneOf2 := _TrailMapElementOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrailMapElementOneOf2)

	if err != nil {
		return err
	}

	*o = TrailMapElementOneOf2(varTrailMapElementOneOf2)

	return err
}

type NullableTrailMapElementOneOf2 struct {
	value *TrailMapElementOneOf2
	isSet bool
}

func (v NullableTrailMapElementOneOf2) Get() *TrailMapElementOneOf2 {
	return v.value
}

func (v *NullableTrailMapElementOneOf2) Set(val *TrailMapElementOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableTrailMapElementOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableTrailMapElementOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrailMapElementOneOf2(val *TrailMapElementOneOf2) *NullableTrailMapElementOneOf2 {
	return &NullableTrailMapElementOneOf2{value: val, isSet: true}
}

func (v NullableTrailMapElementOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrailMapElementOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


