/*
MtnManager API

The MtnManager API provides real-time access to your ski resort’s public operational data. Use it to display current conditions on your website, mobile app, or digital signage.

API version: 1.0.0
Contact: support@mtnmanager.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mtnmanager

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SummerTrail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SummerTrail{}

// SummerTrail Represents a single summer trail at the resort with its current status,  type (e.g. hiking, mountain biking), and optional difficulty rating.
type SummerTrail struct {
	// Unique identifier for the trail.
	Uuid string `json:"uuid"`
	// Display name of the trail.
	Name string `json:"name"`
	// URL-friendly name of the trail.
	Slug string `json:"slug"`
	// Optional trail number.
	Number NullableInt32 `json:"number,omitempty"`
	// Type of trail activity (e.g. hiking, mountain_biking). Can have multiple.
	TrailType []SummerTrailType `json:"trail_type"`
	Difficulty NullableSummerTrailDifficulty `json:"difficulty,omitempty"`
	// Current operational status (open, closed, or unknown).
	Status SummerTrailStatus `json:"status"`
	// Notes about current conditions on this trail.
	ConditionNotes string `json:"condition_notes"`
	// UUID of the area this trail belongs to, if assigned.
	AreaUuid NullableString `json:"area_uuid,omitempty"`
	// Name of the area this trail belongs to, if assigned.
	AreaName NullableString `json:"area_name,omitempty"`
	// Display order of the area this trail belongs to, if assigned, for sorting purposes.
	AreaDisplayOrder NullableInt32 `json:"area_display_order,omitempty"`
	// When this trail's information was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

type _SummerTrail SummerTrail

// NewSummerTrail instantiates a new SummerTrail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummerTrail(uuid string, name string, slug string, trailType []SummerTrailType, status SummerTrailStatus, conditionNotes string, updatedAt time.Time) *SummerTrail {
	this := SummerTrail{}
	this.Uuid = uuid
	this.Name = name
	this.Slug = slug
	this.TrailType = trailType
	this.Status = status
	this.ConditionNotes = conditionNotes
	this.UpdatedAt = updatedAt
	return &this
}

// NewSummerTrailWithDefaults instantiates a new SummerTrail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummerTrailWithDefaults() *SummerTrail {
	this := SummerTrail{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *SummerTrail) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *SummerTrail) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *SummerTrail) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *SummerTrail) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SummerTrail) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SummerTrail) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *SummerTrail) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *SummerTrail) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *SummerTrail) SetSlug(v string) {
	o.Slug = v
}

// GetNumber returns the Number field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SummerTrail) GetNumber() int32 {
	if o == nil || IsNil(o.Number.Get()) {
		var ret int32
		return ret
	}
	return *o.Number.Get()
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SummerTrail) GetNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Number.Get(), o.Number.IsSet()
}

// HasNumber returns a boolean if a field has been set.
func (o *SummerTrail) HasNumber() bool {
	if o != nil && o.Number.IsSet() {
		return true
	}

	return false
}

// SetNumber gets a reference to the given NullableInt32 and assigns it to the Number field.
func (o *SummerTrail) SetNumber(v int32) {
	o.Number.Set(&v)
}
// SetNumberNil sets the value for Number to be an explicit nil
func (o *SummerTrail) SetNumberNil() {
	o.Number.Set(nil)
}

// UnsetNumber ensures that no value is present for Number, not even an explicit nil
func (o *SummerTrail) UnsetNumber() {
	o.Number.Unset()
}

// GetTrailType returns the TrailType field value
func (o *SummerTrail) GetTrailType() []SummerTrailType {
	if o == nil {
		var ret []SummerTrailType
		return ret
	}

	return o.TrailType
}

// GetTrailTypeOk returns a tuple with the TrailType field value
// and a boolean to check if the value has been set.
func (o *SummerTrail) GetTrailTypeOk() ([]SummerTrailType, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrailType, true
}

// SetTrailType sets field value
func (o *SummerTrail) SetTrailType(v []SummerTrailType) {
	o.TrailType = v
}

// GetDifficulty returns the Difficulty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SummerTrail) GetDifficulty() SummerTrailDifficulty {
	if o == nil || IsNil(o.Difficulty.Get()) {
		var ret SummerTrailDifficulty
		return ret
	}
	return *o.Difficulty.Get()
}

// GetDifficultyOk returns a tuple with the Difficulty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SummerTrail) GetDifficultyOk() (*SummerTrailDifficulty, bool) {
	if o == nil {
		return nil, false
	}
	return o.Difficulty.Get(), o.Difficulty.IsSet()
}

// HasDifficulty returns a boolean if a field has been set.
func (o *SummerTrail) HasDifficulty() bool {
	if o != nil && o.Difficulty.IsSet() {
		return true
	}

	return false
}

// SetDifficulty gets a reference to the given NullableSummerTrailDifficulty and assigns it to the Difficulty field.
func (o *SummerTrail) SetDifficulty(v SummerTrailDifficulty) {
	o.Difficulty.Set(&v)
}
// SetDifficultyNil sets the value for Difficulty to be an explicit nil
func (o *SummerTrail) SetDifficultyNil() {
	o.Difficulty.Set(nil)
}

// UnsetDifficulty ensures that no value is present for Difficulty, not even an explicit nil
func (o *SummerTrail) UnsetDifficulty() {
	o.Difficulty.Unset()
}

// GetStatus returns the Status field value
func (o *SummerTrail) GetStatus() SummerTrailStatus {
	if o == nil {
		var ret SummerTrailStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SummerTrail) GetStatusOk() (*SummerTrailStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SummerTrail) SetStatus(v SummerTrailStatus) {
	o.Status = v
}

// GetConditionNotes returns the ConditionNotes field value
func (o *SummerTrail) GetConditionNotes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConditionNotes
}

// GetConditionNotesOk returns a tuple with the ConditionNotes field value
// and a boolean to check if the value has been set.
func (o *SummerTrail) GetConditionNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionNotes, true
}

// SetConditionNotes sets field value
func (o *SummerTrail) SetConditionNotes(v string) {
	o.ConditionNotes = v
}

// GetAreaUuid returns the AreaUuid field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SummerTrail) GetAreaUuid() string {
	if o == nil || IsNil(o.AreaUuid.Get()) {
		var ret string
		return ret
	}
	return *o.AreaUuid.Get()
}

// GetAreaUuidOk returns a tuple with the AreaUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SummerTrail) GetAreaUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaUuid.Get(), o.AreaUuid.IsSet()
}

// HasAreaUuid returns a boolean if a field has been set.
func (o *SummerTrail) HasAreaUuid() bool {
	if o != nil && o.AreaUuid.IsSet() {
		return true
	}

	return false
}

// SetAreaUuid gets a reference to the given NullableString and assigns it to the AreaUuid field.
func (o *SummerTrail) SetAreaUuid(v string) {
	o.AreaUuid.Set(&v)
}
// SetAreaUuidNil sets the value for AreaUuid to be an explicit nil
func (o *SummerTrail) SetAreaUuidNil() {
	o.AreaUuid.Set(nil)
}

// UnsetAreaUuid ensures that no value is present for AreaUuid, not even an explicit nil
func (o *SummerTrail) UnsetAreaUuid() {
	o.AreaUuid.Unset()
}

// GetAreaName returns the AreaName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SummerTrail) GetAreaName() string {
	if o == nil || IsNil(o.AreaName.Get()) {
		var ret string
		return ret
	}
	return *o.AreaName.Get()
}

// GetAreaNameOk returns a tuple with the AreaName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SummerTrail) GetAreaNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaName.Get(), o.AreaName.IsSet()
}

// HasAreaName returns a boolean if a field has been set.
func (o *SummerTrail) HasAreaName() bool {
	if o != nil && o.AreaName.IsSet() {
		return true
	}

	return false
}

// SetAreaName gets a reference to the given NullableString and assigns it to the AreaName field.
func (o *SummerTrail) SetAreaName(v string) {
	o.AreaName.Set(&v)
}
// SetAreaNameNil sets the value for AreaName to be an explicit nil
func (o *SummerTrail) SetAreaNameNil() {
	o.AreaName.Set(nil)
}

// UnsetAreaName ensures that no value is present for AreaName, not even an explicit nil
func (o *SummerTrail) UnsetAreaName() {
	o.AreaName.Unset()
}

// GetAreaDisplayOrder returns the AreaDisplayOrder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SummerTrail) GetAreaDisplayOrder() int32 {
	if o == nil || IsNil(o.AreaDisplayOrder.Get()) {
		var ret int32
		return ret
	}
	return *o.AreaDisplayOrder.Get()
}

// GetAreaDisplayOrderOk returns a tuple with the AreaDisplayOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SummerTrail) GetAreaDisplayOrderOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AreaDisplayOrder.Get(), o.AreaDisplayOrder.IsSet()
}

// HasAreaDisplayOrder returns a boolean if a field has been set.
func (o *SummerTrail) HasAreaDisplayOrder() bool {
	if o != nil && o.AreaDisplayOrder.IsSet() {
		return true
	}

	return false
}

// SetAreaDisplayOrder gets a reference to the given NullableInt32 and assigns it to the AreaDisplayOrder field.
func (o *SummerTrail) SetAreaDisplayOrder(v int32) {
	o.AreaDisplayOrder.Set(&v)
}
// SetAreaDisplayOrderNil sets the value for AreaDisplayOrder to be an explicit nil
func (o *SummerTrail) SetAreaDisplayOrderNil() {
	o.AreaDisplayOrder.Set(nil)
}

// UnsetAreaDisplayOrder ensures that no value is present for AreaDisplayOrder, not even an explicit nil
func (o *SummerTrail) UnsetAreaDisplayOrder() {
	o.AreaDisplayOrder.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SummerTrail) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SummerTrail) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SummerTrail) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o SummerTrail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SummerTrail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	if o.Number.IsSet() {
		toSerialize["number"] = o.Number.Get()
	}
	toSerialize["trail_type"] = o.TrailType
	if o.Difficulty.IsSet() {
		toSerialize["difficulty"] = o.Difficulty.Get()
	}
	toSerialize["status"] = o.Status
	toSerialize["condition_notes"] = o.ConditionNotes
	if o.AreaUuid.IsSet() {
		toSerialize["area_uuid"] = o.AreaUuid.Get()
	}
	if o.AreaName.IsSet() {
		toSerialize["area_name"] = o.AreaName.Get()
	}
	if o.AreaDisplayOrder.IsSet() {
		toSerialize["area_display_order"] = o.AreaDisplayOrder.Get()
	}
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *SummerTrail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
		"slug",
		"trail_type",
		"status",
		"condition_notes",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSummerTrail := _SummerTrail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSummerTrail)

	if err != nil {
		return err
	}

	*o = SummerTrail(varSummerTrail)

	return err
}

type NullableSummerTrail struct {
	value *SummerTrail
	isSet bool
}

func (v NullableSummerTrail) Get() *SummerTrail {
	return v.value
}

func (v *NullableSummerTrail) Set(val *SummerTrail) {
	v.value = val
	v.isSet = true
}

func (v NullableSummerTrail) IsSet() bool {
	return v.isSet
}

func (v *NullableSummerTrail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummerTrail(val *SummerTrail) *NullableSummerTrail {
	return &NullableSummerTrail{value: val, isSet: true}
}

func (v NullableSummerTrail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummerTrail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


